### ISSUE TITLE
Unity Rect Value Wrong

### ISSUE THREAD

**Issue by goodcxm** [Ourpalm/ILRuntime#102]
static void Test()
        {
            var canvasObject = new GameObject("co");
            var canvas = canvasObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;

            var cs = canvasObject.AddComponent<CanvasScaler>();
            cs.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            cs.referenceResolution = new Vector2(1136,640);
            cs.screenMatchMode = CanvasScaler.ScreenMatchMode.Expand;

            var to = new GameObject("to");

            var rtf = to.AddComponent<RectTransform>();
            rtf.transform.SetParent(canvas.transform, false);
            rtf.anchorMin = new Vector2(0, 0);
            rtf.anchorMax = new Vector2(1, 1);
            rtf.sizeDelta = Vector2.zero;

            Debug.LogWarning("r: "+ rtf.rect+" x:"+ rtf.rect.x+ " y:" + rtf.rect.y + " w:" + rtf.rect.width + " h:" + rtf.rect.height);
        }

x,y,width,height always zero

**Comment by liiir1985** [comment]
Rect是否进行了ValueTypeBinding，是否运行了自动分析CLR绑定？

**Comment by goodcxm** [comment]
Rect没有进行绑定，只有vector2和vector3,不过后来取消了结果也一样

**Comment by liiir1985** [comment]
r: (x:-574.50, y:-294.00, width:1149.00, height:588.00) x:-574.5 y:-294 w:1149 h:588

在最新版ILruntime以及ILRuntime 1.3的Demo工程中均无法重现，输出值如上
