### ISSUE TITLE
CLR绑定代码生成的时候报错：类型转换错误

### ISSUE THREAD

**Issue by clayzx** [Ourpalm/ILRuntime#103]
namespace HotFix_Project
{
    class BugTest
    {
        public void Test()
        {
            TestClass<int> r;
            dict.TryGetValue(0, out r);
        }

        Dictionary<int, TestClass<int>> dict = new Dictionary<int, TestClass<int>>();
    }

    public class TestClass<T>
    {

    }
}

复制以上代码放到HotFix_Project任意地方，编译后执行分析Assembly生成CLR Binding Code就会重现报错！

**Comment by liiir1985** [comment]
Fixed
