### ISSUE TITLE
显式实现接口

### ISSUE THREAD

**Issue by liufujingwen** [Ourpalm/ILRuntime#105]
public interface IState
 {
          void Start();
 }

public class TestState : IState
{
         void IState.Start()
          {
                UnityEngine.Debug.Log("TestState.Start");
           }

        //这种没有问题
        //    public void Start()
        //    {
        //        UnityEngine.Debug.Log("TestState.Start");
        //    }
 }

static void RunTest()
{
         IState test = new TestState();
         test.Start();
}

报错：
NullReferenceException: A null value was found where an object instance was required.
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:95)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1699)
Rethrow as ILRuntimeException: A null value was found where an object instance was required.
IL_0008: callvirt System.Void HotFix_Project.TestProtocol/State::Start()
HotFix_Project.TestProtocol.Start() D:/HotFix_Project/TestProtocol.cs:Line 111
HotFix_Project.TestProtocol.RunTest() D:/HotFix_Project/TestProtocol.cs:Line 131

**Comment by jinqi166** [comment]
你换个名字呢？不要叫start

**Comment by liufujingwen** [comment]
这和方法名没关系

**Comment by liiir1985** [comment]
已修复
