### ISSUE TITLE
CheckGenericParams error II    object[][] -> object[]

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#114]
`     
public static void test3()
        {

            Foo2(new object[][] { }, Bar2); //NullReferenceException: Object reference not set to an instance of an object (at Assets/ILRuntime/CLR/TypeSystem/ILType.cs:760)
        }
        

        public static object Bar2(object o)
        {
            return o;
        }
        public static void Foo2<T1, T2>(T1[] t, Func<T1, T2> func)
        {

        }`

**Comment by liiir1985** [comment]
已修复
