### ISSUE TITLE
跨域继承问题

### ISSUE THREAD

**Issue by xujieming** [Ourpalm/ILRuntime#115]
在主工程的代码
`    public class M_MainProjClass
    {
        public I_MainProjInterface TestField;
    }
    public interface I_MainProjInterface
    {
        void Foo();
    }`

在热更层的代码
`public class H_HotFixProjClass : I_MainProjInterface
    {
        public void Foo()
        {
            throw new NotImplementedException();
        }
    }

    public class H_HotFixProjSubClass : H_HotFixProjClass
    {

    }`

`#region 热更层

                M_MainProjClass b = new M_MainProjClass();
                Debug.Log("unlucky step 1");
                var v1 = new H_HotFixProjClass();
                object obj1 = v1;
                Debug.Log("unlucky obj1 " + obj1.GetType().ToString());
                b.TestField = v1;
                Debug.Log("unlucky step 2");
                var v2 = new H_HotFixProjSubClass();
                object obj2 = v2;
                Debug.Log("unlucky obj2 " + obj2.GetType().ToString());
                b.TestField = v2;
                Debug.Log("unlucky step 3");

#endregion`

报错
![35th 2 c n emb6 i7u8a](https://user-images.githubusercontent.com/3971050/36976809-db3ace98-20b9-11e8-8a2d-0582f7dcbc41.png)

**Comment by xujieming** [comment]
`using System;
using System.Collections;
using System.Collections.Generic;
using ILRuntime.CLR.Method;
using ILRuntime.Runtime.Enviorment;
using ILRuntime.Runtime.Intepreter;
using com.xa;

public class I_MainProjInterfaceInheritanceAdapter : CrossBindingAdaptor
{
    public override Type BaseCLRType
    {
        get
        {
            return typeof(I_MainProjInterface);//这是你想继承的那个类
        }
    }

    public override Type AdaptorType
    {
        get
        {
            return typeof(Adaptor);//这是实际的适配器类
        }
    }

    public override object CreateCLRInstance(ILRuntime.Runtime.Enviorment.AppDomain appdomain, ILTypeInstance instance)
    {
        return new Adaptor(appdomain, instance);//创建一个新的实例
    }

    //实际的适配器类需要继承你想继承的那个类，并且实现CrossBindingAdaptorType接口
    class Adaptor : I_MainProjInterface, CrossBindingAdaptorType
    {
        ILTypeInstance instance;
        ILRuntime.Runtime.Enviorment.AppDomain appdomain;
        IMethod mMoveElsewhere;
        bool mMoveElsewhereGot;
        bool isMoveElsewhereInvoking = false;
        //缓存这个数组来避免调用时的GC Alloc
        object[] param1 = new object[1];

        public Adaptor()
        {

        }

        public Adaptor(ILRuntime.Runtime.Enviorment.AppDomain appdomain, ILTypeInstance instance)
        {
            this.appdomain = appdomain;
            this.instance = instance;
        }

        public ILTypeInstance ILInstance { get { return instance; } }

        //你需要重写所有你希望在热更脚本里面重写的方法，并且将控制权转到脚本里去
        public void Foo()
        {
            if (!mMoveElsewhereGot)
            {
                mMoveElsewhere = instance.Type.GetMethod("Foo", 0);
                mMoveElsewhereGot = true;
            }
            //对于虚函数而言，必须设定一个标识位来确定是否当前已经在调用中，否则如果脚本类中调用base.TestVirtual()就会造成无限循环，最终导致爆栈
            if (mMoveElsewhere != null && !isMoveElsewhereInvoking)
            {
                isMoveElsewhereInvoking = true;
                appdomain.Invoke(mMoveElsewhere, instance);
                isMoveElsewhereInvoking = false;
            }
            else
                return;
        }
    }
}`

这是适配器

**Comment by liiir1985** [comment]
已修复
