### ISSUE TITLE
泛型约束，方法之间调用异常

### ISSUE THREAD

**Issue by blueberryWT** [Ourpalm/ILRuntime#117]
在Fetch里面调用了Test，同样的泛型约束，也会导致报错

![tim 20180306135522](https://user-images.githubusercontent.com/3376480/37016220-239934a4-2146-11e8-8532-e9347d72286f.png)

ps:此问题在老版本的ilrt中没问题，最新master分支的会出现

//====================分割线，复现流程============================
// 接口Disposer定义
   public interface IDisposer
    {
        int Id { get; set; }
        void Dispose();
    }
//  实现IDiposer的类
    public class Test : IDisposer
    {
        public int Id { get; set; }
        public void Dispose()
        {
        }
    }

// main 调用
public static T Test<T>() where T : IDisposer
        {
            var type = typeof(Test);
            var result = Activator.CreateInstance(type);
            return (T) result;
        }

public static T Fetch<T>() where T : IDisposer
        {
            var t = Test<T>();
//            ((IDisposer)t).Id = 111; // 正确
            t.Id = 111; // 报错
            return t;
        }

**Comment by liiir1985** [comment]
已修复
