### ISSUE TITLE
自动分析CLR时，泛型类中泛型方法参数获取异常

### ISSUE THREAD

**Issue by blueberryWT** [Ourpalm/ILRuntime#118]
`public class BinderCollection<T> : IBinderCollection<T>
{
      void BindToGList<TListItem>(GList _list, Action<T, TListItem> _bindItemAction){};
}
`
类似于这个方法，在分析的时候，获取到的params列表中，数量是2，但是第二个参数为null，导致分析失败

![default](https://user-images.githubusercontent.com/3376480/37017040-f57a8da8-2149-11e8-8553-7ac3341c8c9b.png)

**Comment by liiir1985** [comment]
已修复
