### ISSUE TITLE
Can support P/Invoke?

### ISSUE THREAD

**Issue by clayzx** [Ourpalm/ILRuntime#12]
My unity project will use the third party plug-in(NoesisGUI), the plug-in used the C++ DLL , and the plug-in C# part of the use of P/Invoke.
My class needs to be registered to the plug-in, or plug-ins need to be registered by reflection of my class. 
My class needs to execute in Runner IL, so I think the only way is to run the plugin in Runner IL.

Do you have any other ideas?

**Comment by liiir1985** [comment]
Pinvoke isn't supported by ilruntime. However, the plugin should already have a wrapper which imported all methods through dllimport. Keep that in Unity side. Use it just like in unity directly shoud work



发自我的小米手机
在 Clay Zhang <notifications@github.com>，2016年12月5日 下午4:04写道：

My unity project will use the third party plug-in(NoesisGUI), the plug-in used the C++ DLL , and the plug-in C# part of the use of P/Invoke.
My class needs to be registered to the plug-in, or plug-ins need to be registered by reflection of my class.
My class needs to execute in Runner IL, so I think the only way is to run the plugin in Runner IL.

Do you have any other ideas?

**Comment by clayzx** [comment]
你是中国有人？ 能否把你的QQ发我邮箱一下，我们QQ交流下。
Email：clayzx@qq.com

**Comment by clayzx** [comment]
You can try this solution:
http://stackoverflow.com/questions/13461989/p-invoke-to-dynamically-loaded-library-on-mono

**Comment by liiir1985** [comment]
QQ群：512079820

**Comment by benidris** [comment]
Can you please send me your email. I need to discuss with you some issues about Technical Debt on your source code. My email : mobenidris@gmail.com
Thanks

**Comment by liiir1985** [comment]
My email is liiir1985@hotmail.com the same as my github account
