### ISSUE TITLE
override Equals get wrong with Action camparison

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#120]
`        static Action act1 = null;
        public static void test4()
        {
            act1 = foo4;
            Action act2 = foo4;
            UnityEngine.Debug.Log(new Test4().Equals2(act2));//true
            UnityEngine.Debug.Log(new Test4().Equals(act2));//false
        }

        static void foo4() { }

        class Test4
        {
            public bool Equals2(object obj)
            {
                return act1.Equals(obj);
            }

            public override bool Equals(object obj)
            {
                return act1.Equals(obj);
            }
        }`

**Comment by liiir1985** [comment]
一直就没有处理过Equals的重载，现在已加上
