### ISSUE TITLE
pass malloc struct instance to out parameter function error #1

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#123]
static void test6()
        {
            Quaternion q = Quaternion.identity;
            float angel = new float();
            Vector3 v3 = new Vector3();
            //note: both error with binding or non binding code
            q.ToAngleAxis(out angel, out v3);//NotImplementedException: The requested feature is not implemented.
        }

**Comment by liiir1985** [comment]
已修复
