### ISSUE TITLE
CanAssignTo error from cross binding types.

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#124]
Edit OnHotFixLoaded() from [MonoBehaviourDemo.cs](https://github.com/Ourpalm/ILRuntimeU3D/blob/master/ILRuntimeDemo/Assets/Scripts/Examples/08_MonoBehaviour/MonoBehaviourDemo.cs)

    unsafe void OnHotFixLoaded()
    {
        SetupCLRRedirection();
        var t1 = appdomain.LoadedTypes["HotFix_Project.SomeMonoBehaviour"];
        var t2 = appdomain.LoadedTypes["HotFix_Project.SomeMonoBehaviour2"];
        Debug.Log(t1.CanAssignTo(t2)); //return true which is clearly wrong
        Debug.Log(t2.CanAssignTo(t1)); //return true which is clearly wrong
        return;
   }

**Comment by liiir1985** [comment]
已修复
