### ISSUE TITLE
unbox error in object[]

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#128]
static void test11()
        {

            f11_1((byte)1); //wrong
            f11_2(new object[] { (byte)1 }); //wrong
            print11((byte)1); //right
        }

        static void f11_1(params object[] o)
        {
            print11(o[0]);
        }
        static void f11_2(object[] o)
        {
            print11(o[0]);
        }
        
        static void print11(object o)
        {
            List<object> l = new List<object>() { o };
            Debug.Log("contains int:" + l.Contains(1));
            Debug.Log("contains byte:" + l.Contains((byte)1));
        }

**Comment by fpywzywzy** [comment]
with the author's words,you should:
f11_1(new object[] { (byte)1 });

**Comment by liiir1985** [comment]
已修复
