### ISSUE TITLE
在Mac环境下编译的DLL无法用ILRuntime加载运行

### ISSUE THREAD

**Issue by fantastxu** [Ourpalm/ILRuntime#129]
按照Demo，在win下用VS编译测试用HotFix_Project.dll没有任何问题，但是在Mac下用VS编译出的dll无法加载，是否dll只能用.NetFramework来编译，用mono或者.NetCore不行？能否提供在Mac下也能编译出可加载运行dll的方案？

**Comment by liiir1985** [comment]
Mac下编译的dll没问题，pdb文件不行，要用mac下编译的，pdb那个参数得传null，不过就没有行号提示了
pdb仅支持windows的vs生成的版本
