### ISSUE TITLE
vs for mac编译无法找到unityengine

### ISSUE THREAD

**Issue by hello32768** [Ourpalm/ILRuntime#130]
您好，我用vs for mac编译例子工程里的hotfix_project，显示无法找到unityengine，教程上说要重新指认，我要如何重新指认？

ps. 如果在references里直接引用unityengine.core.dll文件，编译后在unity运行会报out of memory,不加载pdb文件就不会出问题

**Comment by liiir1985** [comment]
仅支持windows的VS生成的pdb， mac下的不支持
