### ISSUE TITLE
Error with Action/Func GetType()

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#131]
static void test17()
        {
            System.Action a = () => { };
            System.Action<int> a_2 = (i) => { };
            Debug.Log(typeof(System.Action) == a.GetType());  //false, should be true
            Debug.Log(typeof(System.Action<int>) == a_2.GetType());  //false, should be true
        }

**Comment by liiir1985** [comment]
原理上无法实现
ILRuntime中的所有委托实例均为DelegateAdapter，无法跟CLR委托类型进行对比
