### ISSUE TITLE
热更新工程委托的参数含有主工程class类，会导致反射产生

### ISSUE THREAD

**Issue by qq576067421** [Ourpalm/ILRuntime#137]
1、以下是热更新工程的。其中WfPacket是主工程的，并且有做过自动分析，也就是说有WfPacket_Binding.cs文件并且正确注册了。     
         public void ProcessPacket(WfPacket packet)
        {
            ushort msgType = 0;
            ushort msgLength = 0;
            packet.ReadHeader(ref msgType, ref msgLength);
            if (LCL.NetworkManager.GetInstance().GetEnableDebug( LCL.NetworkProtol.Tcp))
            {
                Debug.Log("收到:" + Convert.ToString(msgType, 16));
            }
            System.Action<WfPacket> hander = null;
            if (!m_Handlers.TryGetValue(msgType, out hander))
            {
                Debug.Log("消息没有处理 ID：" + msgType.ToString());
            }
            else
            {
                try
                {
                    Debug.Log("Start Handler");
                    hander(packet);
                    Debug.Log("End Handler");
                }
                catch (Exception ex)
                {
                    Debug.LogException(ex);
                }
            }
        }

2、m_Handlers这个dic里面注册的一个相应函数，我已经注释掉所有可能干扰因素，测试发现，在上面的"Start Handler"和"End Handler"之间 产生了3的日志。
        private void CheckAccountResult(WfPacket packet)
        {
            ////获取登录服务器信息
            //SC_LoginRst pak = new SC_LoginRst();
            //pak.DeSerialize(packet);
            //int result = pak.m_rst;
            //if (result == 0)
            //{
            //    m_Login.m_GameServers.Clear();
            //    GameServerInfo info = new GameServerInfo();
            //    info.m_szIp = m_Login.m_LoginInfo.m_szIp;
            //    info.m_iPort = 24000;
            //    info.m_SessionId = pak.m_sessionid;
            //    m_Login.m_GameServers.Add(info);
            //    Debug.Log("获取服务器信息成功："+ info.m_SessionId);

            //    m_LoginRst = (int)emLoginResult.emLoginResult_OK;
            //    CGameProcedure.SetProcedureStatus(LoginStatus.LoginRst);
            //}
            //else
            //{
            //    m_LoginRst = (int)emLoginResult.emLoginResult_Failed;
            //    CGameProcedure.SetProcedureStatus(LoginStatus.LoginRst);
            //}
        }
3、日志（本人保证代码已经更新到最新的ILRuntime版本），由于这里涉及到热更新的消息处理，可能确实需要处理下。
Not Binding, Invoke:Void Invoke(WfPacket)
UnityEngine.Debug:LogWarning(Object)
CSHotFix.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/CSHotFixLibaray/Core/Runtime/Intepreter/ILIntepreter.cs:1746)
CSHotFix.Runtime.Intepreter.ILIntepreter:Run(ILMethod, Object, Object[]) (at Assets/CSHotFixLibaray/Core/Runtime/Intepreter/ILIntepreter.cs:76)
CSHotFix.Runtime.Enviorment.AppDomain:Invoke(IMethod, Object, Object[]) (at Assets/CSHotFixLibaray/Core/Runtime/Enviorment/AppDomain.cs:999)
CSHotFix.Runtime.Intepreter.MethodDelegateAdapter`1:InvokeILMethod(WfPacket) (at Assets/CSHotFixLibaray/Core/Runtime/Intepreter/DelegateAdapter.cs:367)
GameDll.PacketHandlerManager:ProcessPacket(WfPacket) (at Assets/Scripts/Local/Classes/Network/Net/PacketHandlerManager.cs:47)
Net:Update() (at Assets/Scripts/Local/Classes/Network/Net/Net.cs:154)
LCL.NetworkManager:Update() (at Assets/Scripts/Local/Classes/Network/NetworkManager.cs:136)
GameDll.CGameProcedure:Update() (at Assets/Scripts/GameDll/Procedure/CGameProcedure.cs:216)
LogicMain:Update() (at Assets/Scripts/GameDll/Base/LogicMain.cs:84)
Main:Update() (at Assets/Scripts/Local/Classes/Main.cs:67)

**Comment by liiir1985** [comment]
新版中已修改
