### ISSUE TITLE
There is a issue of ldfld

### ISSUE THREAD

**Issue by Cherish18** [Ourpalm/ILRuntime#14]
error:
Rethrow as ILRuntimeException: Object reference not set to an instance of an object
IL_0045: ldfld UnityEngine.Object AssetsData::assetsData

error line:
if (ad.assetsData == null)

code:
        AssetsData ad = apm.GetAssetByAssetName<AudioClip>(iconName, eAssetsType.Texture);

        if (ad == null)
        {
            DebugLoger.LogError("PlayBGMSound 失败 没有加载到对应的资源" + iconName);
            return;
        }

        if (ad.assetsData == null)
        {
            DebugLoger.Log("Loger ad.assetsData null");
            return;
        }

**Comment by ourpalmadmin** [comment]
应该已经ok了
