### ISSUE TITLE
ILRuntime 是否可以在需修复的工程里 调用 原工程的代码

### ISSUE THREAD

**Issue by cloudfreexiao** [Ourpalm/ILRuntime#142]
如题 由于我们项目 已经基本完成 想引入 ILRuntime 但是有个疑问就是 
不管保证 之前的csharp 代码是否有问题  可能会 在 hotfix里调用 之前的api 类之类 请问 ILRuntime 是否可以 支持 或者 怎么做到 这点 谢谢！！！

**Comment by liiir1985** [comment]
不是很懂你想问的是什么……能否用具体代码举例
