### ISSUE TITLE
带ref 参数的函数绑定时，hotfixdll中对象上定义的字段作为实参传下去的值错误，另外long的值超过intmax时也会有错误

### ISSUE THREAD

**Issue by HoseaJiang** [Ourpalm/ILRuntime#143]
//底层代码
public static class TestLong
{
    public static void TestLongRef(ref long i)
    {
        Debug.LogErrorFormat("TestLongRef:{0}", i);
    }
}

//hotfix dll代码
class LongHolder
{
    public long lv;
}

public class Entry
{
    static void Start()
    {
        long stackof = 4200000000L;
        long stackl = 24;
        var heapLong = new LongHolder();
        TestLong.TestLongRef(ref stackof);//无论代码是否binding，输出TestLongRef:-94967296
        TestLong.TestLongRef(ref stackl);//无论代码是否binding，输出TestLongRef:24
        TestLong.TestLongRef(ref heapLong.lv);//若代码binding，输出TestLongRef:4（或者其他莫名的值），否则输出TestLongRef:0，换成ref int也一样，class对象的话没测试过。
    }
}

**Comment by liiir1985** [comment]
已修复
