### ISSUE TITLE
Mono.Cecil版本过低，是否考虑更新？

### ISSUE THREAD

**Issue by raytaylorlin** [Ourpalm/ILRuntime#145]
项目需要使用Mono.Cecil做注入及ILRuntime做热更新，但发现ILRuntime带的Cecil版本已经和现在Cecil版本相去甚远，没有带WriteAssembly的功能。自行将Cecil更到最新的话，DebugService又有诸多报错，请问是否能更新Cecil的版本？（如果不打算更新的话，只能自行修改DebugService源码或放弃debug的功能了）

**Comment by liiir1985** [comment]
之前尝试过升级mono cecil，但是由于新版mono cecil有很多运行时bug，导致ilruntime 运行时很多执行不可预期的结果，因此又回滚回到这个版本了
