### ISSUE TITLE
ReflectionType.GetProperties error

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#146]
class test24Class
        {
            public int this[int index] { get { return 0; } }
        }
        static void test24()
        {
            HelloWorld.Test23_CLR(new test24Class());
        }

in CLR

    public static void Test23_CLR(object o)
    {
        if(o is ILTypeInstance)
        {
            (o as ILTypeInstance).Type.ReflectionType.GetProperties(BindingFlags.Public | BindingFlags.Instance);//error
        }
    }

**Comment by liiir1985** [comment]
已修复
