### ISSUE TITLE
ilruntime使用dotween回调报错

### ISSUE THREAD

**Issue by ghostwolfliu** [Ourpalm/ILRuntime#147]
最小复现代码:
                Action test = () => { UnityEngine.Debug.Log("!!!!!!!!!!!!!!"); };
                TweenCallback callback = new TweenCallback(test);
报错:
ArgumentException: method arguments are incompatible
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method, System.Boolean throwOnBindFailure, System.Boolean allowClosed) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
System.Delegate.CreateDelegate (System.Type type, System.Object firstArgument, System.Reflection.MethodInfo method) (at <c95265f74fdf4905bfb0d5a4b652216c>:0)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/Plugins/LTGame/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:2429)
Rethrow as ILRuntimeException: method arguments are incompatible
IL_0091: newobj System.Void DG.Tweening.TweenCallback::.ctor(System.Object,System.IntPtr)

**Comment by liiir1985** [comment]
System.Void DG.Tweening.TweenCallback
你需要发一下这个类型的定义

**Comment by ghostwolfliu** [comment]
namespace DG.Tweening
{
    public delegate void TweenCallback();
}

**Comment by liiir1985** [comment]
无法将委托作为调用target传给另外一个委托，请直接传方法作为target
