### ISSUE TITLE
在ilrt中用反射调用一个 枚举属性的getter方法，会崩溃

### ISSUE THREAD

**Issue by fujaja2002** [Ourpalm/ILRuntime#148]
发现如果用反射调用一个 枚举属性的getter方法，会崩溃

最小测试用例
using System.Reflection;

namespace FjjTest
{
    public class CrashTest
    {
        public void TestCrashPb()
        {
            var data = new enum_crash_type();
            var t = data.GetType();
            var fields = t.GetProperties(BindingFlags.Public | BindingFlags.Instance);
            if (fields.Length > 0)
            {
                foreach (var info in fields)
                {
                    object value = info.GetGetMethod().Invoke(data, null);
                }
            }
        }
    }
    
    public class enum_crash_type
    {
        public Test TestEnum
        {
            get;set;
        }

        public enum Test
        {
            test1,
            test2,
        }
    }
}

**Comment by liiir1985** [comment]
已修复
