### ISSUE TITLE
热更中的type.IsGenericType()判断出错

### ISSUE THREAD

**Issue by Minamiyama** [Ourpalm/ILRuntime#151]
using System;
using System.Collections.Generic;

namespace TestCases
{
    public class GenericTestClass<T>
    {

    }

    class GenericClassTypeTest
    {
        public static void GenericClassTypeTest1()
        {
            var testInst = new GenericTestClass<int>();

            var clzType = typeof(GenericTestClass<int>);
            var instType = testInst.GetType();

            var nativeType = typeof(List<int>);

            Console.WriteLine($"clzType is generic type? {clzType.IsGenericType}"); //Should be true
            Console.WriteLine($"instType is generic type? {instType.IsGenericType}"); //Should be true
            Console.WriteLine($"nativeType is generic type? {nativeType.IsGenericType}");

            if (clzType.IsGenericType == false || instType.IsGenericType == false)
            {
                throw new Exception("IsGenericType shoud be true");
            }
        }
    }
}

**Comment by liiir1985** [comment]
已修复
