### ISSUE TITLE
multi dimension array support?

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#157]
public static void test26() {
            int[,] a = new int[2, 3];
            a[0, 0] = 1; //ios il2cpp ipad test: invocation exception
            a[0, 0].ToString(); //unityeditor crash on windows pc test
        }

**Comment by liiir1985** [comment]
a[0,0] = 1的这个你需要尝试CLR自动绑定生成int[,].Set方法的绑定，应该是没法通过反射来设置

a[0,0].ToString()调用了int[,].Adress取数组指针，这方法无法在clr外部调用，所以没法支持
