### ISSUE TITLE
GetHashCode 报错

### ISSUE THREAD

**Issue by mydodolookdo** [Ourpalm/ILRuntime#159]
Action act = () => {  };
int code = act.GetHashCode();
第二句会报错

**Comment by liiir1985** [comment]
在最新版中无法重现

**Comment by mydodolookdo** [comment]
NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Intepreter.ILTypeInstance.GetHashCode () (at Assets/ILRuntime/Runtime/Intepreter/ILTypeInstance.cs:468)
System.Delegate.GetHashCode () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Delegate.cs:475)
System.MulticastDelegate.GetHashCode () (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/MulticastDelegate.cs:102)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
ILRuntime.CLR.Method.CLRMethod.Invoke (ILRuntime.Runtime.Intepreter.ILIntepreter intepreter, ILRuntime.Runtime.Stack.StackObject* esp, IList`1 mStack, Boolean isNewObj) (at Assets/ILRuntime/CLR/Method/CLRMethod.cs:282)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1778)
Rethrow as ILRuntimeException: Exception has been thrown by the target of an invocation.
IL_0040: callvirt System.Int32 System.Object::GetHashCode()
HotFix_Project.InstanceClass.OnAct(Int32 mid, String clsname, String msg) M:/projects/ILRuntime/svn/ILRuntimeU3D/trunk/HotFix_Project/InstanceClass.cs:Line 132

用了新版还是会报错
