### ISSUE TITLE
float莫名其妙的GC问题

### ISSUE THREAD

**Issue by huanhecao** [Ourpalm/ILRuntime#164]
using System;
using System.Collections.Generic;
using UnityEngine;

namespace HotFix_Project
{
    public class InstanceClass
    {
        static Vector3 a1 = new Vector3();
        static Vector3 a2 = new Vector3();
        public static void Update(float time)
        {
            Vector3 leftBottom = a1;

            Vector3 rightTop = a2;

            //float width = (rightTop.x - leftBottom.x) / 2; //如果是/2,在release下这行语句会直接产生20GC

            float width = (rightTop.x - leftBottom.x) * 0.5f;//如果为*0.5f，那么这句就不会有GC，而在下面使用的时候会产生一次GC

            float height = (rightTop.y - leftBottom.y) * 0.5f;

            float f1 = width;//如果上面为/2，那这句就不再有GC，如果*0.5f，那么这句就会产生20GC

            float f2 = height;

            //使用Debug生成的dll，是正常的，使用release生成的才会有问题
        }
    }
}

附unity3d工程和dll生成工程
[test-Demo.zip](https://github.com/Ourpalm/ILRuntime/files/2117704/test-Demo.zip)

**Comment by liiir1985** [comment]
在release模式下会被优化成直接使用成员变量，存取成员变量的字段都不可避免会产生gc，目前暂时无解
