### ISSUE TITLE
使用async/await

### ISSUE THREAD

**Issue by leejack1000** [Ourpalm/ILRuntime#167]
呼叫async的函式時候報錯
TypeLoadException: Cannot find Adaptor for:System.Runtime.CompilerServices.IAsyncStateMachine
請問要如何使用async/await呢?

**Comment by liiir1985** [comment]
这个提示说明缺少跨域继承适配器，
代码中继承了System.Runtime.CompilerServices.IAsyncStateMachine，因此需要添加对应的适配器，Github的master中有async的TestCase，里面有写好的现成的这个接口的适配器

**Comment by leejack1000** [comment]
嗯嗯  感謝  原來master上就有@@

2018-06-28 10:30 GMT+08:00 liiir1985 <notifications@github.com>:

**Comment by leejack1000** [comment]
既這個問題之後
我在iOS運行的時候出現問題:
ExecutionEngineException: Attempting to call method
'System.Runtime.CompilerServices.AsyncTaskMethodBuilder::AwaitUnsafeOnCompleted'
for which no ahead of time (AOT) code was generated.
  at System.Reflection.MonoMethod.Invoke (System.Object obj,
System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder,
System.Object[] parameters, System.Globalization.CultureInfo culture)
[0x00000] in <00000000000000000000000000000000>:0
...
...
...

請問這問題是我應該要在
Link.xml裡加上什麼東西嗎?

如果不是我應該要如何解決?

2018-06-28 10:30 GMT+08:00 liiir1985 <notifications@github.com>:

**Comment by liiir1985** [comment]
你这个被il2cpp剪裁的是泛型方法，
link.xml无法预留泛型方法，你需要使用CLR自动分析绑定将你所有使用到的接口都绑定了

**Comment by aaa333000** [comment]
有具体办法吗？或者Demo？谢谢大神
