### ISSUE TITLE
Conv_U8 等转换错误

### ISSUE THREAD

**Issue by soarwell** [Ourpalm/ILRuntime#169]
Conv_U8 转换错误，
long value = 0;
value = value + 0xffffffff;
算出的结果是-1
可以参考coreclr的实现，interpreter.cpp line 2693
        case CEE_CONV_U8:
            Conv<UINT64, /*TIsUnsigned*/true, /*TCanHoldPtr*/true, /*TIsShort*/false, CORINFO_TYPE_LONG>();
            break;

**Comment by liiir1985** [comment]
```Csharp
public static void UnitTest_1011()
        {
            long value = 0;
            value = value + 0xffffffff;
            Console.WriteLine(value);
        }
```
用ilruntime最新版试验以上代码输出的结果是4294967295，无法重现你的问题
