### ISSUE TITLE
使用LitJson.JsonMapper序列化继承自主工程的类时缺失父类的字段

### ISSUE THREAD

**Issue by hoxily** [Ourpalm/ILRuntime#171]
## 复现方法

- 在 https://github.com/Ourpalm/ILRuntimeU3D 的1f4732b6ccb3de151567c869e2757e77233a8c5e 版本的基础上添加附件中提供的Unity资源包；
- 把TestJson2.cs.txt文件去掉.txt扩展名，并纳入热更工程中；
- 生成热更dll到StreamingAssets中；
- 运行mytest场景，可以发现序列化的JSON中缺失父类的result字段和type字段；

## 期望的结果

在热更的代码里序列化的JSON里能含有父类的result和type字段值。

## 附件

[LitJson.Mapper_Serialize_Problem.unitypackage.zip](https://github.com/Ourpalm/ILRuntime/files/2152553/LitJson.Mapper_Serialize_Problem.unitypackage.zip)

**Comment by liiir1985** [comment]
已修复
