### ISSUE TITLE
值绑定NotSupportedException异常

### ISSUE THREAD

**Issue by huanhecao** [Ourpalm/ILRuntime#173]
public class InstanceClass
    {
        static Transform Player = new GameObject().transform;
        public static void Update(float time)
        {
            float py = (1 - Player.position.y);
            //Player.position += Vector3.up * py;//这样是不会有异常
            Player.position += Vector3.up * (1 - Player.position.y);//这样会有
        }
    }

**Comment by huanhecao** [comment]
[test-Demo.zip](https://github.com/Ourpalm/ILRuntime/files/2165328/test-Demo.zip)

**Comment by liiir1985** [comment]
已修复
