### ISSUE TITLE
NotImplementedException错误

### ISSUE THREAD

**Issue by huanhecao** [Ourpalm/ILRuntime#180]
public class InstanceClass
    {
        static List<Vector3> points = new List<Vector3>();
        static Vector3[] tmp_points = new Vector3[1];
        public static void Update(float time)
        {
            points.Add(new Vector3());
            float t = 0.1f;
            tmp_points[0].x = (float)(points[0].x * (1 - t) + points[0].x * t);//会报NotImplementedException: The requested feature is not implemented.
            tmp_points[0].y = (float)(points[0].y * (1 - t) + points[0].y * t);
            tmp_points[0].z = (float)(points[0].z * (1 - t) + points[0].z * t);
        }
    }
[test-Demo.zip](https://github.com/Ourpalm/ILRuntime/files/2204702/test-Demo.zip)

**Comment by huanhecao** [comment]
不需要那么复杂。。。。其实就是Vector[]，不支持.x这样赋值

tmp_points[0].x = 0.1f;//单纯这样就可以报错了

**Comment by liiir1985** [comment]
已修复
