### ISSUE TITLE
ILRuntime 热更代码域中，定义的枚举数组，在开启VS编译器优化选项之后，默认构造函数初始化异常。

### ISSUE THREAD

**Issue by CP-Bloom** [Ourpalm/ILRuntime#182]
using UnityEngine;
using System;

public enum eSystemType
{
   NULL
}

public class SystemType
{
    public int value = 10;
}

public class TestConstructor
{
    int[] ArrayTest = null;
    eSystemType[] ArrayTest2 = new eSystemType[9];
    eSystemType[] ArrayTest3 = null;
    SystemType ReferenceTest1 = null;

    //如反注释此构造函数 则表现正常
    //public TestConstructor()
    //{
    //    ArrayTest = null;
    //    ArrayTest2 = null;
    //    ArrayTest2 = null;
    //    ReferenceTest1 = null;
    //}

    public void ArrayLengthTest()
    {
        if (ArrayTest == null)
            ArrayTest = new int[5];
        Debug.LogErrorFormat("Int array type {0}", ArrayTest.GetType().Name);
        Debug.LogErrorFormat("Int array length {0}", ArrayTest.Length);
        if (ArrayTest2 == null)
            ArrayTest2 = new eSystemType[10];
        Debug.LogErrorFormat("Enum array type {0}", ArrayTest2.GetType().Name);
        Debug.LogErrorFormat("Enum array length {0}", ArrayTest2.Length);
        if (ReferenceTest1 == null)
            ReferenceTest1 = new SystemType();
        Debug.LogErrorFormat("SystemType type {0}", ReferenceTest1.GetType().Name);
        Debug.LogErrorFormat("SystemType va {0}", ReferenceTest1.value);
        if (ArrayTest3 == null)
            ArrayTest3 = new eSystemType[15];
        Debug.LogErrorFormat("Enum array type {0}", ArrayTest3.GetType().Name);
        Debug.LogErrorFormat("Enum array length {0}", ArrayTest3.Length);
    }
}

将以上代码复制到 热更代码域中, 构建TestConstructor 实例，然后调用ArrayLengthTest 方法。 当开启VS2015 编译器优化代码选项时，ArrayTest3 对象非null，获取ArrayTest3.Length异常。

**Comment by liiir1985** [comment]
已修复
