### ISSUE TITLE
NotSupportedException: Operation is not supported问题

### ISSUE THREAD

**Issue by huanhecao** [Ourpalm/ILRuntime#183]
public class InstanceClass
    {
        static Transform Player = new GameObject().transform;
        public static void Update(float time)
        {
            Camera Camera2D = GameObject.Find("Camera2D").GetComponent<Camera>();
            Vector3 pos = Camera2D.ScreenToWorldPoint(Input.mousePosition);
            float offsetX = pos.x - 0.1f;
            float offsetY = pos.y - 0.1f;//报错行数在这里
            if (offsetX > 1)
                Debug.LogError("");
            else if (offsetX < -1)
                Debug.LogError("");
            //注释下面的代码就不会出错了
            else if (offsetY > 1)
                Debug.LogError("");
            else if (offsetY < -1)
                Debug.LogError("");
        }
    }

[test-Demo.zip](https://github.com/Ourpalm/ILRuntime/files/2215969/test-Demo.zip)

**Comment by liiir1985** [comment]
已修复
