### ISSUE TITLE
对于作为对象Field或者Property的Struct回写导致的崩溃或者回写不生效问题

### ISSUE THREAD

**Issue by HoseaJiang** [Ourpalm/ILRuntime#184]
public class Vector3BindingTest
    {
        public Vector3 Value = new Vector3(20f, 10f, 1f);
    }

    class TestValueType
    {
        public static void RunTest()
        {
            Vector3BindingTest VTest = new Vector3BindingTest();
            Vector3 value = VTest.Value;
            value.Normalize();
            VTest.Value.Normalize();
            Debug.LogError("Vector3BindingTest local Vector3 normalized = " + value);
            Debug.LogError("Vector3BindingTest Vector3 normalized = " + VTest.Value);
        }
    }

以上为HotFix测试代码，U3DDemo Unity工程
通过代码绑定生成器生成绑定代码，编辑器中执行，输出的第二行
Vector3BindingTest Vector3 normalized = (20,10,1)，没有回写，如果发布到IL2CPP执行VTest.Value.Normalize()时抛null异常，如果在编辑器定义DISABLE_ILRUNTIME_DEBUG宏则抛out of range异常。如果Vector3BindingTest.Value定义为property，则无论如何不抛异常，但回写WriteBackValue函数内部不会有任何分支被执行，输出Vector3BindingTest Vector3 normalized = (20,10,1)

**Comment by liiir1985** [comment]
已修复
