### ISSUE TITLE
热更DLL中[Serializable]字段失效，所有类型都是不可序列化的？

### ISSUE THREAD

**Issue by zzzxxccvv** [Ourpalm/ILRuntime#189]
热更DLL中创建的类即使有[Serializable]字段，typeof(DynamicClass).IsSerializable也返回false

**Comment by liiir1985** [comment]
IsSerializable是系统实现，他无法获取热更中的type。 你再热更里通过typeof(X).GetCustomAttribute是可以取到Serializable的
