### ISSUE TITLE
使用 CodeGenerationTools 工具发生错误

### ISSUE THREAD

**Issue by ToroCheng** [Ourpalm/ILRuntime#193]
使用 CodeGenerationTools 工具发生错误，System.InvalidCastException: 无法将类型 'Mono.Cecil.TypeReference' 的物件转换为类型 'Mono.Cecil.GenericInstanceType'。

**Comment by ToroCheng** [comment]
System.InvalidCastException: 无法将类型 'Mono.Cecil.TypeReference' 的物件转换为类型 'Mono.Cecil.GenericInstanceType'。
   于 CodeGenerationTools.Generator.DelegateRegisterGenerator.LoadData(Object data) 于 C:\ILRuntime-master\CodeGenerationTools\Generator\DelegateRegisterGenerator.cs: 行 38
   于 CodeGenerationTools.Generator.Base.GeneratorBase`1.InitFromFile(String tmpdFilePath, TData data) 于 C:\ILRuntime-master\CodeGenerationTools\Generator\Base\GeneratorBase.cs: 行 90
   于 CodeGenerationTools.Generator.HelperGenerator.CreateDelegateRegisterInit(Object type) 于 C:\ILRuntime-master\CodeGenerationTools\Generator\HelperGenerator.cs: 行 92
   于 CodeGenerationTools.Generator.HelperGenerator.LoadData(Tuple`3 data) 于 C:\ILRuntime-master\CodeGenerationTools\Generator\HelperGenerator.cs: 行 61
   于 CodeGenerationTools.MainForm.CreateILRuntimeHelper() 于 C:\ILRuntime-master\CodeGenerationTools\MainForm.cs: 行 383
   于 CodeGenerationTools.MainForm.GenerateClick(Object sender, EventArgs e) 于 C:\ILRuntime-master\CodeGenerationTools\MainForm.cs: 行 257

**Comment by liiir1985** [comment]
这个工具已经outdated，并且没有人维护了
