### ISSUE TITLE
appdomain如何释放当前dll

### ISSUE THREAD

**Issue by huqiang0204** [Ourpalm/ILRuntime#195]
我的dll是实时获取的，当appdomain第二次载入dll时，各种随机触发报错

**Comment by liiir1985** [comment]
无法卸载， 可以弃用当前appdomain重新new一个，不过你需要自行将之前appdoamin的引用清空，用到了这个里面创建出来的东西的地方都需要自己手动置空

**Comment by huqiang0204** [comment]
好的，谢谢

发送自我的 Windows 10 手机

________________________________
发件人: liiir1985 <notifications@github.com>
发送时间: Thursday, August 9, 2018 12:52:14 PM
收件人: Ourpalm/ILRuntime
抄送: TecntVideo; Author
主题: Re: [Ourpalm/ILRuntime] appdomain如何释放当前dll (#195)


无法卸载， 可以弃用当前appdomain重新new一个，不过你需要自行将之前appdoamin的引用清空，用到了这个里面创建出来的东西的地方都需要自己手动置空

―
