### ISSUE TITLE
Ref参数传递数据超过32位丢失

### ISSUE THREAD

**Issue by a4765041** [Ourpalm/ILRuntime#196]
在热更工程中使用Ref参数传递long值, 并在里面移位超过32位会出现数据丢失,测试工程链接,[测试demo链接](https://pan.baidu.com/s/1fPls__hxtv2UZ1UEV27NWQ)

` private static void TestRef(ref long mask)
        {
            for (int i = 0; i < 50; i++)
            {
                mask |= (long)1 << i;
            }
        }`

**Comment by liiir1985** [comment]
已修复
