### ISSUE TITLE
char和object转换导致结果值错误

### ISSUE THREAD

**Issue by JasonPool** [Ourpalm/ILRuntime#198]
`
object och = 'd';
char ch1 = (char)och;
Debug.LogError("test1:" + (int)ch1 + " " + ch1);
`
在非ilrt下输出：	test1:100 d
在ilrt下输出：		test1:-65436 d

**Comment by JasonPool** [comment]
在非ilrt下输出：	test1:100 d
在ilrt下输出：		test1:-65436 d

**Comment by liiir1985** [comment]
已修复
