### ISSUE TITLE
获取自定义Attribute导致Unity崩溃

### ISSUE THREAD

**Issue by liufujingwen** [Ourpalm/ILRuntime#199]
Unity版本 Unity 2017.4.7f1 
type.GetCustomAttributes(typeof(FacadeAttribute), false)    这个导致Unity崩溃

//在mono层缓存所有hotfixTypes
void OnHotFixLoaded()
    {
        hotfixTypes = appdomain.LoadedTypes.Values.Select(x => x.ReflectionType).ToArray();
        appdomain.Invoke("HotFix_Project.TestAttribute", "Run", null, null);
    }

//Hotfix代码
namespace HotFix_Project
{
    public class FacadeAttribute : Attribute
    {
        public FacadeAttribute(int model)
        {
            this.model = model;
        }
        public int model;
    }

    [FacadeAttribute(1)]
    public sealed class TestController
    {
        public static TestController instance = new TestController();
    }

    public static class TestAttribute
    {
        public static void Run()
        {
            Type[] types = HelloWorld.hotfixTypes;

            for (int i = 0; i < types.Length; i++)
            {
                Type type = types[i];

                //if (type.BaseType != null && (type.BaseType == typeof(Attribute) || type.BaseType.Name == "Attribute"))
                //    continue;

                //if (type.BaseType != null && type.BaseType.Name == "Void")
                //    continue;

                object[] attrs = type.GetCustomAttributes(typeof(FacadeAttribute), false);
            }
        }
    }
}

**Comment by liiir1985** [comment]
没有重现出来
