### ISSUE TITLE
Type.GetCustomAttributes 导致的bug

### ISSUE THREAD

**Issue by liufujingwen** [Ourpalm/ILRuntime#201]
object[] attrs = typeof(TestController).GetCustomAttributes(typeof(ObjectEventAttribute), false);
TestController没有打ObjectEventAttribute标签，attrs.Length 应该等于0，
结果attrs.Length == 1 是错误的

namespace HotFix_Project
{
    public class FacadeAttribute : Attribute
    {
        public FacadeAttribute(int model)
        {
            this.model = model;
        }
        public int model;
    }

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    public class ObjectEventAttribute : Attribute
    {
    }

    [FacadeAttribute(1)]
    public sealed class TestController
    {
        public static TestController instance = new TestController();
    }

    public static class TestAttribute
    {
        public static void Run()
        {
            object[] attrs = typeof(TestController).GetCustomAttributes(typeof(ObjectEventAttribute), false);
            //结果attrs的Length > 0 , 这是错误的结果吧
            Debug.LogError(attrs.Length);

        }
    }
}

**Comment by liiir1985** [comment]
已修复
