### ISSUE TITLE
反序列化dll外部的enum值會異常

### ISSUE THREAD

**Issue by leejack1000** [Ourpalm/ILRuntime#203]
class Test
{
    class MyClass
    {
        public MyEnum myEnum;
    }

    public void start()
    {
        MyClass myClass = new MyClass();
        myClass.myEnum = MyEnum.A;

        string json = LitJson.JsonMapper.ToJson(myClass);

        MyClass myNewClass = LitJson.JsonMapper.ToObject<MyClass>(json);
        if (MyEnum.A == myNewClass.myEnum)
        {
            Debug.Log("Ok");
        }
        else
        {
            Debug.Log("Fail");
        }
    }
}
--------我是分隔線-----
public enum MyEnum
{
    None,
    A,
}

如果MyEnum放在DLL裡面就會正常
但如果放在Unity裡面就會失敗

**Comment by liiir1985** [comment]
已修复
