### ISSUE TITLE
两条小建议

### ISSUE THREAD

**Issue by HypnusJie** [Ourpalm/ILRuntime#206]
1、在线文档中跨域继承的部分建议最后写一下，需要手动去注册，而不仅仅是实现相应适配器就可以。（建议可以配置特性，统一注册）
2、Demo工程中加载dll的那段代码，有关平台判断的部分，建议改用Application.platform来判断，以避免工程在编辑器中转换到其他平台时加载出错（虽然只是个demo）

**Comment by HypnusJie** [comment]
另外还有一个小的点，关于特性的，如果采用
var a = typeof(TestCl).GetCustomAttributes(typeof(TestAttribute), false);这样的方式去获取是可以的，
但如果用 var a = Attribute.GetCustomAttribute(typeof(TestClass), typeof(TestAttribute)) as TestAttribute;这样的方式去获取则会报错

**Comment by liiir1985** [comment]
在线文档关于继承那个后期会加上需要注册的提示

demo加载dll那段只是抛砖引玉，因为不同项目加载需求不尽相同，不希望这里误导用户用何种加载方式

Attribute的方法暂未做支持，后期可加入
