### ISSUE TITLE
TypeAssignableFrom

### ISSUE THREAD

**Issue by leejack1000** [Ourpalm/ILRuntime#209]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

public class TestTypeAssignableFrom
{
    public TestTypeAssignableFrom() : this((new PlayerInfo()).GetType())
    {
    }

    private TestTypeAssignableFrom(Type targetType)
    {
        foreach (System.Reflection.PropertyInfo property in targetType.GetProperties())
        {
            if (!property.CanWrite)
            {
                continue;
            }
            Debug.LogWarning(property.Name + "|" + typeof(System.Collections.ICollection).IsAssignableFrom(property.PropertyType));
        }

        foreach (System.Reflection.FieldInfo field in targetType.GetFields())
        {
            Debug.LogWarning(field.Name + "|" + typeof(System.Collections.ICollection).IsAssignableFrom(field.FieldType));
        }
    }

    public class PlayerInfo
    {
        public string[] tags_F;

        public Detail[] Details_F;

        public string[] tags_P { get; set; }

        public Detail[] Details_P { get; set; }
    }

    public class Detail
    {
    }
}

已上cs在Unity跑與ILRuntime裡面跑出來的結果不一樣

Unity:
tags_P|True
Details_P|True
tags_F|True
Details_F|True
---------------------
ILRuntime:
tags_P|True
Details_P|False
tags_F|True
Details_F|False

**Comment by liiir1985** [comment]
已修复
