### ISSUE TITLE
Task.Run + async 得 lambda function 會報錯

### ISSUE THREAD

**Issue by leejack1000** [Ourpalm/ILRuntime#213]
public static async Task<int> Test()
        {
            try
            {
                return await Task.Run<int>(async () =>
                {
                    await Task.Delay(0);
                    return 0;
                });
            }
            catch (System.Exception e)
            {
                Debug.LogError(e.Data["StackTrace"]);
            }

            return 0;
        }

以上Code在ILRumtime裡面執行會報錯
IL_0037: call System.Threading.Tasks.Task`1<!!0> System.Threading.Tasks.Task::Run<System.Int32>(System.Func`1<System.Threading.Tasks.Task`1<!!0>>)

**Comment by liiir1985** [comment]
已修复
