### ISSUE TITLE
热更里面断点，子类调用base.xxx()，无法进入父类的xxx()方法

### ISSUE THREAD

**Issue by EricCai1991** [Ourpalm/ILRuntime#218]
public class A : B
{
    protected override ovid OnDestroy()
    {
         Debug.Log("测试1");
         base.OnDestroy();
    }
}
public class B
{
    public ovid OnDestroy()
    {
         Debug.Log("测试2");
    }
}

测试1是A类，测试2是B类，A继承了B，AB都在热更里面，断电调试的时候跳不进B里面，但是log打印出是进去了

**Comment by liiir1985** [comment]
用最新版ILRuntime无法重现， 可以正常在b中断点
