### ISSUE TITLE
Struct里有枚举会抛出异常【NotSupportedException: Specified method is not supported】

### ISSUE THREAD

**Issue by 111304037** [Ourpalm/ILRuntime#221]
`enum BonusType
        {
            b,
            Bomb,
            aa
        }
        private struct FuckStruct
        {
            public BonusType type;

            public float percentage;

            public int weight;
            public FuckStruct(BonusType type, float percantage, int weight)
            {
                this.type = type;
                percentage = percantage;
                this.weight = weight;
            }
        }

        public static readonly Main Instance = new Main();

        public static void OnAwake()
        {
            var a = new FuckStruct(BonusType.Bomb,100,50);
            var b = a;
            UnityEngine.Debug.LogError(a.type + " " + a.percentage + " " + b.weight);
            UnityEngine.Debug.LogError(b.type + " " + b.percentage + " " + b.weight);
        }`

`NotSupportedException: Specified method is not supported.
ILRuntime.Runtime.Intepreter.ILIntepreter.CopyStackValueType (ILRuntime.Runtime.Stack.StackObject* src, ILRuntime.Runtime.Stack.StackObject* dst, System.Collections.Generic.IList`1[T] mStack) (at Assets/Plugins/3rd/ILR/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:4191)
ILRuntime.Runtime.Intepreter.ILIntepreter.StLocSub (ILRuntime.Runtime.Stack.StackObject* esp, ILRuntime.Runtime.Stack.StackObject* v, ILRuntime.Runtime.Stack.StackObject* bp, System.Int32 idx, System.Collections.Generic.IList`1[T] mStack) (at Assets/Plugins/3rd/ILR/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:4311)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/Plugins/3rd/ILR/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:325)
Rethrow as ILRuntimeException: Specified method is not supported.
IL_0011: stloc.1`

**Comment by 111304037** [comment]
unity2017.3.p4 ILRuntime 是从github最新拉的

**Comment by liiir1985** [comment]
已修复
