### ISSUE TITLE
关于不支持int?，float?等Nullable写法

### ISSUE THREAD

**Issue by 111304037** [Ourpalm/ILRuntime#222]
取值报空，是bug还是本身不支持呢

**Comment by WilsonUnity** [comment]
我也想知道这个问题，你后来是怎么解决的

**Comment by WilsonUnity** [comment]
> 取值报空，是bug还是本身不支持呢

我也想知道这个问题，你后来是怎么解决的

**Comment by 111304037** [comment]
> > 取值报空，是bug还是本身不支持呢
> 
> 我也想知道这个问题，你后来是怎么解决的

弃坑了，现在写lua，贼溜

**Comment by fatfatson** [comment]
> > 取值报空，是bug还是本身不支持呢
> 
> 我也想知道这个问题，你后来是怎么解决的

@WilsonUnity 见  #313
