### ISSUE TITLE
蓝大, 麻烦帮我一下.测试用例已经提上github

### ISSUE THREAD

**Issue by Ron3** [Ourpalm/ILRuntime#224]
蓝大: 我的问题是这样的. 我想在dll工程里.想通过反射来创建带有泛型参数的实例
https://github.com/Ron3/ILRuntimeU3D
你只需要在项目里搜索 TODO 蓝大.即能看到2个测试用例
入口在HelloWorld.cs

附部分测试代码(方便你找)

// TODO 蓝大 测试代码
Type t = typeof(Ron<>);
UnityEngine.Debug.Log("t Type ==> " + t);
Type constructed = t.MakeGenericType(new Type[]{typeof(string)});
object obj = Activator.CreateInstance(constructed, new object[]{"Test Success"});

如果有任何问题,也可以在QQ群里艾特我. 我叫Ron
谢谢

**Comment by liiir1985** [comment]
已修复

**Comment by Ron3** [comment]
感谢
