### ISSUE TITLE
方法中带out 泛型参数找不方法

### ISSUE THREAD

**Issue by zhengOscar** [Ourpalm/ILRuntime#230]
GetSpecifiedOrder(ushort mapArea, byte type, uint subType, out ObjectOrder <T> order)
方法调用时在，AppDomain中打印到是这样的，一直找不到方法。
System.UInt16 ==== System.UInt16
System.Byte ==== System.Byte
System.UInt32 ==== System.UInt32
ObjectOrder`1<T>&      ====   ObjectOrder`1&

**Comment by liiir1985** [comment]
你是再执行什么操作的时候找不到方法？

**Comment by zhengOscar** [comment]
按钮点击

**Comment by zhengOscar** [comment]
点击按钮调用该方法，报错找不到方法

**Comment by liiir1985** [comment]
这个问题应该已经修复，用最新版试试吧
