### ISSUE TITLE
静态字段实例化类型不明确导致栈溢出

### ISSUE THREAD

**Issue by wangjun19879527** [Ourpalm/ILRuntime#231]
//以下是热更代码
public class Test
{
    private static string m_rootFolder = "jun.wang";
	
    public static string rootFolder => m_rootFolder;

    private static bool m_isPersistent = false;
    public static bool isPersistent
    {
        set
        {
            m_isPersistent = value;
            m_rootFolder = "我设置。。。。";
        }
    }

    public static void Invoke()
    {
        isPersistent = true;
    }
}
//以下是主工程调用代码
m_domain.Invoke("Test", "Invoke", null);

**Comment by liiir1985** [comment]
在最新master版上测试并没有办法重现
