### ISSUE TITLE
ILRuntime基于.Net 4.x上绑定Type时，可以获取internal的属性,比如isSZArray?

### ISSUE THREAD

**Issue by SixGodZhang** [Ourpalm/ILRuntime#232]

**Comment by SixGodZhang** [comment]
```
        Type type = typeof(Type);
        MethodInfo[] methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly);
        foreach (var method in methods)
        {
            Debug.Log(method.Name);
        }
```
1.在输出的方法名中包含了get_IsSZArray,而get_IsSZArray在Type类中是一个internal的属性，按道理说应该是获取不到的.
2.我自己写的类型,internal声明的是完全获取不到的,但是在获取Type的时候却可以获取到,不知道为什么?
3.而且在测试过程中，我发现Unity项目工程的mscorlib引用会发生变化,由mono指向.NetFramework,
而将两个dll反解过来看Type，其实两个Type类并不相同,mono下的dll是不含有isSZArray,.NetFramework下面是含有isSZArray

**Comment by SixGodZhang** [comment]
已解决.Unity使用的DLL,和项目工程中的DLL有区别,并不是同一个条件下编译出来的。

**Comment by hanyingjun** [comment]
你好，请问你这个问题怎么解决的？我也遇到了
