### ISSUE TITLE
在重载的情况下，可能出现函数不能正确定位的bug

### ISSUE THREAD

**Issue by yb199478** [Ourpalm/ILRuntime#242]
**复现方式**

在主工程，或者动态链接库中，声明函数重载:

```csharp
public static void Extend<TService, TConcrete>(Func<TConcrete, IContainer, object> closure);
```

```csharp
public static void Extend<TService, TConcrete>(Func<TConcrete, object> closure);
```

然后尝试在热更新中调用：
```csharp
App.Extend<IExtend, IExtend>((instance, c) =>
 {
    return instance;
});
```

观察`CLRMethod.cs`会发现没有调用指定的Method。

![1](https://user-images.githubusercontent.com/12524356/50588503-6190d400-0ebd-11e9-92ca-9a46d7a33a7f.png)

**Comment by yb199478** [comment]
[CatLib.ILRuntime.zip](https://github.com/Ourpalm/ILRuntime/files/2720489/CatLib.ILRuntime.zip)

**Comment by mybios** [comment]
我也遇到一样的问题
