### ISSUE TITLE
使用 Task.Run 報錯

### ISSUE THREAD

**Issue by leejack1000** [Ourpalm/ILRuntime#246]
public class Test
{
    public async void readText()
    {
        List<Task> tasks = new List<Task>();
        for (int i = 1; i <= 3; ++i)
        {
            string path = $"C://{i}.txt";
            Debug.Log(path);
            Task task = Task.Run(async () =>
            {
                return await readText(path);
            });
            tasks.Add(task);
        }
        await Task.WhenAll(tasks);
    }

    private async Task<List<string>> readText(string path)
    {
        Debug.Log(path);
        List<string> lines = new List<string>();
        using (System.IO.StreamReader reader = System.IO.File.OpenText(path))
        {
            string line;
            while (null != (line = await reader.ReadLineAsync()))
            {
                lines.Add(line);
            }
        }

        return lines;
    }
}

先在C槽建立3个空的txt档案 1.txt 2.txt 3.txt
在 ILRuntime 里面执行以上 Code(呼叫 Test().readText()) 时候会报错:
NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:165)
ILRuntime.Runtime.Intepreter.ILIntepreter.Run (ILRuntime.CLR.Method.ILMethod method, System.Object instance, System.Object[] p) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:82)
ILRuntime.Runtime.Enviorment.AppDomain.Invoke (ILRuntime.CLR.Method.IMethod m, System.Object instance, System.Object[] p) (at Assets/ILRuntime/ILRuntime/Runtime/Enviorment/AppDomain.cs:1089)
ILRuntime.Runtime.Adaptors.IAsyncStateMachineClassInheritanceAdaptor+IAsyncStateMachineAdaptor.MoveNext () (at Assets/ILRuntime/Adapters/IAsyncStateMachineAdaptor.cs:68)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) (at <cfc149f8218b496788d8493c87de777a>:0)
ILRuntime.Runtime.Generated.System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_List_1_String_Binding.Start_1 (ILRuntime.Runtime.Intepreter.ILIntepreter __intp, ILRuntime.Runtime.Stack.StackObject* __esp, System.Collections.Generic.IList`1[T] __mStack, ILRuntime.CLR.Method.CLRMethod __method, System.Boolean isNewObj) (at Assets/ILRuntime/Generated/System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_List_1_String_Bi_t.cs:169)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1767)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <cfc149f8218b496788d8493c87de777a>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <cfc149f8218b496788d8493c87de777a>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:92)
UnityEngine.UnitySynchronizationContext.Exec () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:53)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at C:/buildslave/unity/build/Runtime/Export/UnitySynchronizationContext.cs:74)

**Comment by liiir1985** [comment]
该用例使用多线程同时执行同一个方法，造成多个线程重复初始化同一个方法，并且初始化进度不一致

ILRuntime不是线程安全的，必须避免这种情况，否则执行结果是不可预期的

**Comment by leejack1000** [comment]
请问有办法在 ILRuntime 用多线程解决这问题吗?
因为表太多 不这样读会卡很久

**Comment by liiir1985** [comment]
你可以尝试先等待一个文件完全读取完毕，再多线程并行

**Comment by leejack1000** [comment]
大概了解了
只要方法有人初始化完成之后就可以了吧?
目前是把方法搬回 Unity 里面给 ILRuntime 呼叫
谢谢
