### ISSUE TITLE
out 修饰的 dictionary 形参，ilr类型解析出错

### ISSUE THREAD

**Issue by yimengfan** [Ourpalm/ILRuntime#248]
`public class a
{
    
}
public class issue001 
{
    public issue001()
    {
        Dictionary<string, a> adic = new Dictionary<string, a>();
        TestOutPramas( out adic);
    }
    

    private void TestOutPramas( out Dictionary<string, a> adic)
    {
        adic= new Dictionary<string, a>();
    }
}`

**Comment by liiir1985** [comment]
应该已经修复
