### ISSUE TITLE
【问题】提交苹果商店有问题吗？

### ISSUE THREAD

**Issue by wavebit** [Ourpalm/ILRuntime#25]
你好，不知道这个库可以用于苹果商店的热更新吗？

**Comment by liiir1985** [comment]
根据苹果的条例，使用解译型的脚本语言是允许，目前也有其他朋友提交苹果审核没有遇到问题。
不过用脚本来做热更新（审核通过后修改游戏功能和行为）是条例里禁止的。目前并没有针对游戏进行限制，目前来说是安全的（这个规定跟什么热更方案没有关系，lua之类的也是一样的，原则来说lua能用，ILRuntime就能用，要不能用就都不能用了）
