### ISSUE TITLE
unity2018.3 pdb加载报错

### ISSUE THREAD

**Issue by dingxiaowei** [Ourpalm/ILRuntime#255]
![image](https://user-images.githubusercontent.com/5206472/51658050-b2d64400-1fe1-11e9-95b0-f97e790b8fdf.png)
![image](https://user-images.githubusercontent.com/5206472/51658057-bcf84280-1fe1-11e9-8683-718a43fd7e5e.png)

**Comment by liiir1985** [comment]
需要使用最新master版本才能打开unity 2018.3以上版本生成的dll
