### ISSUE TITLE
最新版本生成CLR绑定报错

### ISSUE THREAD

**Issue by leiguoqiang** [Ourpalm/ILRuntime#256]
ObjectDisposedException: Cannot access a disposed object.
Object name: 'Stream has been closed'.
System.IO.FileStream.get_Position () (at <ac823e2bb42b41bda67924a45a0173c3>:0)
Mono.Cecil.PE.BinaryStreamReader.get_Position () (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.Cil.CodeReader.MoveTo (Mono.Cecil.MethodDefinition method) (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.Cil.CodeReader.ReadMethodBody (Mono.Cecil.MethodDefinition method) (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.MetadataReader.ReadMethodBody (Mono.Cecil.MethodDefinition method) (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.MethodDefinition+<>c.<get_Body>b__41_0 (Mono.Cecil.MethodDefinition method, Mono.Cecil.MetadataReader reader) (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.ModuleDefinition.Read[TItem,TRet] (TRet& variable, TItem item, System.Func`3[T1,T2,TResult] read) (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.MethodDefinition.get_Body () (at <37a6c1d8164842d6bc3afc0155808942>:0)
Mono.Cecil.MethodDefinition.get_DebugInformation () (at <37a6c1d8164842d6bc3afc0155808942>:0)
ILRuntime.CLR.Method.ILMethod.GetValidSequence (System.Int32 startIdx, System.Int32 dir) (at Assets/Scripts/ILRT/ILRuntime/CLR/Method/ILMethod.cs:161)
ILRuntime.CLR.Method.ILMethod..ctor (Mono.Cecil.MethodDefinition def, ILRuntime.CLR.TypeSystem.ILType type, ILRuntime.Runtime.Enviorment.AppDomain domain) (at Assets/Scripts/ILRT/ILRuntime/CLR/Method/ILMethod.cs:145)
ILRuntime.CLR.TypeSystem.ILType.InitializeMethods () (at Assets/Scripts/ILRT/ILRuntime/CLR/TypeSystem/ILType.cs:670)
ILRuntime.CLR.TypeSystem.ILType.GetMethods () (at Assets/Scripts/ILRT/ILRuntime/CLR/TypeSystem/ILType.cs:475)
ILRuntime.Runtime.CLRBinding.BindingCodeGenerator.CrawlAppdomain (ILRuntime.Runtime.Enviorment.AppDomain domain, System.Collections.Generic.Dictionary`2[TKey,TValue] infos) (at Assets/Scripts/ILRT/ILRuntime/Runtime/CLRBinding/BindingCodeGenerator.cs:351)
ILRuntime.Runtime.CLRBinding.BindingCodeGenerator.GenerateBindingCode (ILRuntime.Runtime.Enviorment.AppDomain domain, System.String outputPath, System.Collections.Generic.List`1[T] valueTypeBinders, System.Collections.Generic.List`1[T] delegateTypes) (at Assets/Scripts/ILRT/ILRuntime/Runtime/CLRBinding/BindingCodeGenerator.cs:166)
ILRT.CLRBindingGenerator.GenerateCLRBindingByAnalysis () (at Assets/Editor/Scripts/CLRBindingGenerator.cs:30)

**Comment by liiir1985** [comment]
新版Cecil要求加载Assembly的stream全程不能关闭，需要修改相关代码（去掉using段，等所有操作完毕后再关闭流等）

**Comment by dingxiaowei** [comment]
不能using  加载dll和pdb的memorystream
