### ISSUE TITLE
字典获取Enumerator转换成基类接口报错

### ISSUE THREAD

**Issue by xiangchunsong520** [Ourpalm/ILRuntime#26]
public class DictionaryEnumeratorTest<TKey, TValue>
    {
        Dictionary<TKey, TValue> dic = new Dictionary<TKey, TValue>();
        public void Add(TKey key, TValue value)
        {
            dic.Add(key, value);
        }

        public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator()
        {
            return dic.GetEnumerator();    //报错
        }

        public void GetEnumeratorTest()
        {
            var e = dic.GetEnumerator();   //正常
            while (e.MoveNext())
            {
                UnityEngine.Debug.Log(e.Current.Key + "  " + e.Current.Value);
            }
        }

        public void GetEnumeratorTest2()
        {
            IEnumerator<KeyValuePair<TKey, TValue>> e = dic.GetEnumerator();   //报错
            while (e.MoveNext())
            {
                UnityEngine.Debug.Log(e.Current.Key + "  " + e.Current.Value);
            }
        }
    }

    public class MyTest
    {
        public static void Test()
        {
            DictionaryEnumeratorTest<int, int> t = new DictionaryEnumeratorTest<int, int>();
            t.Add(1, 1);
            t.GetEnumeratorTest();
            t.GetEnumeratorTest2();
            var e = t.GetEnumerator();
            while (e.MoveNext())
            {
                UnityEngine.Debug.Log(e.Current.Key + "  " + e.Current.Value);
            }
        }
    }

**Comment by liiir1985** [comment]
已修复
