### ISSUE TITLE
继承泛型接口生成adaptor报错

### ISSUE THREAD

**Issue by dingxiaowei** [Ourpalm/ILRuntime#260]
界面用法
![2ashu l bf2oi p4 jpx5d](https://user-images.githubusercontent.com/5206472/52829094-5fe63d00-3106-11e9-8f09-ea3aaf10439a.jpg)

adaptor生成
![image](https://user-images.githubusercontent.com/5206472/52829121-75f3fd80-3106-11e9-8f8c-c1266806e2e4.png)

生成报错

**Comment by dingxiaowei** [comment]
已解决  尽量避免出现这种情况

**Comment by AllenKashiwa** [comment]
所以跨域继承不支持泛型是吗？
