### ISSUE TITLE
泛型接口类型识别错误

### ISSUE THREAD

**Issue by zhuxianzhiniko** [Ourpalm/ILRuntime#269]
在使用泛型接口的时候，不能正确识别类型
<code>
public interface IGenericType<T>
{
    
}
public class GenericType<T>:IGenericType<T>
{
   
}

 public static void GenericTypeTest6<TView, TData>(IGenericType<TData> source)
 {
   
        Debug.Log("run Test6");
 }
调用使用接口类型，类型识别错误
  GenericType<int> reactiveCollection1 = new GenericType<int>();
  TestType.GenericTypeTest6<int, int>(reactiveCollection1);
</code>

调用不使用接口类型，类型识别正确

<code>
 public static void GenericTypeTest5<TView, TData>(GenericType<TData> source)
 {
        //不使用接口类型能正确识别
        Debug.Log("run Test6");
 }
</code>

## error: ##
<code>
KeyNotFoundException: Cannot find method:GenericTypeTest6 in type:TestType, token=System.Void TestType::GenericTypeTest6<System.Int32,System.Int32>(IGenericType`1<!!1>)
ILRuntime.Runtime.Enviorment.AppDomain.GetMethod (System.Object token, ILRuntime.CLR.TypeSystem.ILType contextType, ILRuntime.CLR.Method.ILMethod contextMethod, System.Boolean& invalidToken) (at Assets/ILRuntime/Runtime/Enviorment/AppDomain.cs:1214)
ILRuntime.CLR.Method.ILMethod.InitToken (ILRuntime.Runtime.Intepreter.OpCodes.OpCode& code, System.Object token, System.Collections.Generic.Dictionary`2[TKey,TValue] addr) (at Assets/ILRuntime/CLR/Method/ILMethod.cs:421)
ILRuntime.CLR.Method.ILMethod.InitCodeBody () (at Assets/ILRuntime/CLR/Method/ILMethod.cs:291)
ILRuntime.CLR.Method.ILMethod.get_Body () (at Assets/ILRuntime/CLR/Method/ILMethod.cs:198)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:120)
ILRuntime.Runtime.Intepreter.ILIntepreter.Run (ILRuntime.CLR.Method.ILMethod method, System.Object instance, System.Object[] p) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:96)
ILRuntime.Runtime.Enviorment.AppDomain.Invoke (ILRuntime.CLR.Method.IMethod m, System.Object instance, System.Object[] p) (at Assets/ILRuntime/Runtime/Enviorment/AppDomain.cs:1086)
ILRuntime.Runtime.Enviorment.AppDomain.Invoke (System.String type, System.String method, System.Object instance, System.Object[] p) (at Assets/ILRuntime/Runtime/Enviorment/AppDomain.cs:989)
ILRuntimeAppDomain.Invoke (System.String type, System.String method, System.Object instance, System.Object[] p) (at Assets/Scripts/ILRuntimeAppDomain.cs:41)
</code>

## 这是一个最小的测试案例 ##
[ILTest.zip](https://github.com/Ourpalm/ILRuntime/files/3126160/ILTest.zip)

**Comment by liiir1985** [comment]
应该已经修复了，试一下master版
