### ISSUE TITLE
Dictionary中处理数组的问题

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#27]
Dictionary中加出数组会报错，代码：

		public static Dictionary<string, MyData[]> data = new Dictionary<string, MyData[]>();

		public static void UnitTest_Test1()
		{
			data["test"] = new MyData[5];
		}

错误信息：

Test:TestCases.MyTest.UnitTest_Test1
TestResult:False
Log:
类型“ILRuntime.Runtime.Intepreter.ILTypeInstance[]”的对象无法转换为类型“ILRuntime.Runtime.Intepreter.ILTypeInstance”。
Local Variables:

IL_0011: callvirt System.Void System.Collections.Generic.Dictionary`2<System.String,TestCases.MyData[]>::set_Item(!0,!1)
at TestCases.MyTest.UnitTest_Test1() D:\lib\ILRuntime\TestCases\MyTest.cs:Line 14

System.ArgumentException: 类型“ILRuntime.Runtime.Intepreter.ILTypeInstance[]”的对象无法转换为类型“ILRuntime.Runtime.Intepreter.ILTypeInstance”。
   在 System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   在 System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture, Boolean skipVisibilityChecks)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   在 ILRuntime.CLR.Method.CLRMethod.Invoke(ILIntepreter intepreter, StackObject* esp, List`1 mStack, Boolean isNewObj) 位置 D:\lib\ILRuntime\ILRuntime\CLR\Method\CLRMethod.cs:行号 271
   在 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute(ILMethod method, StackObject* esp, Boolean& unhandledException) 位置 D:\lib\ILRuntime\ILRuntime\Runtime\Intepreter\ILIntepreter.cs:行号 1729

=======================

**Comment by liiir1985** [comment]
已修复
