### ISSUE TITLE
结构体的值在热更新中赋值的问题

### ISSUE THREAD

**Issue by yingnierxiao** [Ourpalm/ILRuntime#270]
m_freelook.m_XAxis.Value += dx  这样写热更新就没法赋值

下面这样写可以正常赋值
m_freelook.m_XAxis.Value = m_freelook.m_XAxis.Value + dx;

**Comment by liiir1985** [comment]
m_freelook在哪儿申明的？
他和m_XAxis分别什么类型，该类型又是哪儿申明的

**Comment by kaclok** [comment]
是不是 在生成绑定代码之前  没做值类型binder的注册啊

**Comment by liiir1985** [comment]
master版已修复
