### ISSUE TITLE
ilruntime中,如何通过反射拿到List<T>中的T类型,T是ilruntime中定义的对象

### ISSUE THREAD

**Issue by AlienJack** [Ourpalm/ILRuntime#275]
ILRuntimeWrapperType中重写了GetGenericArguments
当List<T>中的T是mono中定义的对象,可以拿到类型,如果是ilruntime中的对象,拿到的类型是ILTypeInstance

**Comment by liiir1985** [comment]
你需要拿到ILRuntimeWrapperType的CLRType，用ILRuntime的接口取拿

**Comment by chenhuomain** [comment]
你好，我不太懂你们说的，请问具体该怎么做 我该调用ILRuntime的哪个接口？`


        public List<Data> dataList = new List<Data>();

        public class Data
        {
            public List<Transform> transfrom = new List<Transform>();
            public GameObject go;
        }

        public static void SetObject(List<Transform> list, object obj)
        {
            Activator.CreateInstance(obj.GetType().GetField("dataList").GetValue(obj).GetType().GetGenericArguments()[0]);
}`

我在热更的dll里像这样试着创建 Data的对象 但失败了。 得到这样的报错 Default constructor not found for type ILRuntime.Runtime.Intepreter.ILTypeInstance
