### ISSUE TITLE
热更工程中  现在只能获取Type的特性Attribute，不能获取方法的特性

### ISSUE THREAD

**Issue by dabengying** [Ourpalm/ILRuntime#277]
热更工程中  现在只能获取Type的特性Attribute，不能获取方法的特性

**Comment by dabengying** [comment]
[Network.MsgFuncClass]
    public class TestClass
    {
        [Network.MsgFunc(typeof(TestACK))]
        public static void TestACK(Proto.IProtoMessage raw)
        {

        }
    }

**Comment by liiir1985** [comment]
ILRuntime最新版测试用MethodInfo.GetCustomAttribute可以拿到

**Comment by yomunsam** [comment]
> ILRuntime最新版测试用MethodInfo.GetCustomAttribute可以拿到

请问这个问题现在怎么用了？好像发现Field也拿不到Attribute

**Comment by ZhaoFengChaoChina** [comment]
Field 和 MethodInfo都拿不到。
