### ISSUE TITLE
Json处理时，有使用了Adaptor的类时会出错

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#28]
测试用例如下：

	class MyTest1
	{
		public static void UnitTest_Test1()
		{
			string json = "[{\"Name\":\"MyName\"}]";
			List<MyTestDataA> data = JsonMapper.ToObject<List<MyTestDataA>>(json);
			Console.WriteLine("Name : "+data[0].Name);
		}
	}

	class MyTestDataA  : TestClass3
	{
		public string Name;
	}

TestClass3即现有用例中的ILRuntimeTest.TestFramework.TestClass3。

**Comment by larlf** [comment]
另外发现，静态的字段没有被处理，而在LitJson下是可以的。测试用例如下：

	class MyTest1
	{
		public static void UnitTest_Test1()
		{
			string json = "{\"Name\":\"MyName\"}";
			JsonMapper.ToObject<MyTestDataA>(json);
			Console.WriteLine("Name : "+ MyTestDataA.Name);
		}
	}

	class MyTestDataA
	{
		public static string Name;
	}

**Comment by liiir1985** [comment]
已修复
