### ISSUE TITLE
CLR 如何重定向？

### ISSUE THREAD

**Issue by platefaces** [Ourpalm/ILRuntime#281]
你好作者
ILRuntime  框架内部 真正CLR重定向的代码在哪里？  我看框架就是没有找到。
我自己想实现一个new A() 创建的是new B() 功能，  CLR 重定向可以实现吗？

**Comment by liiir1985** [comment]
CLR只能实现在ILRuntime内部调用外部一个A方法时，挟持后做另外一段逻辑
