### ISSUE TITLE
Coroutine里面使用TaskCompletionSource报错

### ISSUE THREAD

**Issue by aaa333000** [Ourpalm/ILRuntime#284]
/// <summary>
        /// 这样写是没问题的
        /// </summary>
        /// <returns></returns>
        private Task<string> GetStringTask1()
        {
            TaskCompletionSource<string> tsk = new TaskCompletionSource<string>();
            tsk.SetResult("123456789");

            return tsk.Task;
        }

        /// <summary>
        /// 这样写报AOT错误
        /// </summary>
        /// <returns></returns>
        private Task<string> GetStringTask()
        {
            TaskCompletionSource<string> tsk = new TaskCompletionSource<string>();
            StartCoroutine(TaskTestAtTime(() =>
            {
                tsk.SetResult("123456789");
            }));
            return tsk.Task;
        }
        private IEnumerator TaskTestAtTime(System.Action r_action)
        {
            yield return new WaitForSeconds(1);
            r_action.Invoke();
        }

**Comment by liiir1985** [comment]
报AOT错误说明被剪裁，CLR自动分析绑定是唯一有效能够绑定所有所需接口的方法，你可以自行检查报AOT错误的方法在生成的clr绑定文件中是否存在
另外你也可以通过link.xml来保留类型，详细请参考unity的文档
