### ISSUE TITLE
使用静态变量时, t.StaticInstance为空,抛出NullReferenceException的问题

### ISSUE THREAD

**Issue by coldfox** [Ourpalm/ILRuntime#285]
public struct Number
    {
        public static readonly Number maxValue = new Number(Double.MaxValue);
        public static readonly Number minValue = new Number(Double.MinValue);
   }

当在sturct内, 像这样使用静态变量时, 会报如下的错误...

NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/3rd/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:2041)
Rethrow as ILRuntimeException: Object reference not set to an instance of an object
IL_000e: stsfld Hotfix.xGame.Battle.XMath.Number Hotfix.xGame.Battle.XMath.Number::maxValue
Hotfix.xGame.Battle.XMath.Number..cctor() Z:/works/AFK/Developer/Client/xgame_project/src/xGame/Battle/XMath/Number.cs:Line 18
Rethrow as ILRuntimeException: Object reference not set to an instance of an object
IL_000e: stsfld Hotfix.xGame.Battle.XMath.Number Hotfix.xGame.Battle.XMath.Number::maxValue
Hotfix.xGame.Battle.XMath.Number..cctor() Z:/works/AFK/Developer/Client/xgame_project/src/xGame/Battle/XMath/Number.cs:Line 18

查看ILR代码的话,是StaticInstance对象为空了...下面代码的t.StaticInstance为空..
                            case OpCodeEnum.Ldsfld:
                                {
                                    type = AppDomain.GetType((int)(ip->TokenLong >> 32));
                                    if (type != null)
                                    {
                                        if (type is ILType)
                                        {
                                            ILType t = type as ILType;
                                            t.StaticInstance.PushToStack((int)ip->TokenLong, esp, AppDomain, mStack);
                                        }

找到一个临时的处理办法..   在使用到该类之前, 任一地方主动调用一次new对象, 如: Number n = new Number(0.0);  则该问题即可被暂时处理...

此处代码均为dll内代码, 并且确定已经使用CLR自动分析功能, 分析了最新的dll...

**Comment by liiir1985** [comment]
public struct Number
        {
            public static readonly Number maxValue = new Number(Double.MaxValue);
            public static readonly Number minValue = new Number(Double.MinValue);
            public double val;
            public Number(double val)
            {
                this.val = val;
            }
        }

        public static void StructTest4()
        {
            Console.WriteLine(Number.minValue.val);
        }

用master版ilruntime和以上测试代码，无法重现问题
