### ISSUE TITLE
Hotfix.dll 能否拆成多个

### ISSUE THREAD

**Issue by kingdachong** [Ourpalm/ILRuntime#287]
因为项目分层开发，代码保护的需要希望达到的效果就是热更的工程可以拆成多个比如 Hotfix1.project Hotfix2.project 最后生成 Hotfix1.dll,Hotfix2.dll，这两个dll可能互相依赖或者至少单向依赖。 然后我尝试通过
AppDomain.LoadAssembly("Hotfix1.dll")
AppDomain.LoadAssembly("Hotfix2.dll")
加载这两个dll，并且希望程序能正常运转。
但实际我测试的结果是有报错无法正常运行，不知道我如何才能做到这个效果？还是其实ILRuntime的设计根本不支持这样的做法，盼复！谢谢~
另外
我也尝试用ILMerge在生成了Hotfix1.dll和Hotfix2.dll后再合并成Hotfix.dll但是发现无法合并dll。

**Comment by liiir1985** [comment]
目前来说只要按照依赖顺序加载dll，是可以做到拆分的，不过根据其他朋友上报在部分泛型类型上可能会有问题，不过这种用法并不是ilruntime的设计使用方式和推荐的方式，所以需要自行尝试
