### ISSUE TITLE
遍历热更里的枚举时ILRunTime会报空指针，ILIntepreter.cs 3611行

### ISSUE THREAD

**Issue by aaa333000** [Ourpalm/ILRuntime#288]
热更Dll里面的代码：

        private enum ETest
        {
            TEST_1,
            TEST_2,
            TEST_3,
            TEST_4,
            TEST_5,
        }

        private void TestEnum()
        {
            ETest[] eTests = (ETest[])System.Enum.GetValues(typeof(ETest));
            foreach (var item in eTests)
            {
                Debug.LogError(item);
            }
        }

报的错误：
NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:3611)
Rethrow as ILRuntimeException: Object reference not set to an instance of an object
IL_001b: ldelem.i4

可以确定的东西：
eTests数组不是空的，打印出eTests.Length是5

**Comment by aaa333000** [comment]
补充：System.Enum.GetNames是正常的

**Comment by liiir1985** [comment]
已修复
