### ISSUE TITLE
Json : Object和Dictionary中对使用了Adaptor的类的处理

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#29]
测试用例如下：

	class MyTest1
	{
		public static void UnitTest_JsonMap()
		{
			string json = "{\"Items\":{\"one\":{\"Type\":\"OneType\"},\"two\":{\"Type\":\"TwoType\"}}}";
			MyTestDataMap data =JsonMapper.ToObject<MyTestDataMap> (json);
			Console.WriteLine("Type : "+data.Items["one"].Type);
		}
	}

	class MyTestDataItem : TestClass3
	{
		public string Type;
	}

	class MyTestDataMap : TestClass3
	{
		public Dictionary<string, MyTestDataItem> Items;
	}

**Comment by liiir1985** [comment]
已修复
