### ISSUE TITLE
在热更层，UnityEnegine.Object.Instantiate不可以复制MonoBehaviour

### ISSUE THREAD

**Issue by aaa333000** [Ourpalm/ILRuntime#290]
在热更层
class A : MonoBehaviour
{
    async void Awake()
    {
        await System.Threading.Tasks.Task.Delay(2000);
        //这句没问题，可以正常复制出一个GameObject
        GameObject mmm = GameObject.Instantiate<A>(this).transform.gameObject;
        //这句报错了，transform获取不到
        mmm.transform.name = Time.time.ToString();
    } 
}
会报错，如果改成：
GameObject mmm = GameObject.Instantiate<GameObject>(gameObject).transform.gameObject;就没事
注：Object.Instantiate没有被重定向，Component.get_transform有重定向，代码如下：

private static StackObject* GetTransform_1(ILIntepreter __intp, StackObject* __esp, IList<object> __mStack, CLRMethod __method, bool isNewObj)
        {
            AppDomain __domain = __intp.AppDomain;
            StackObject* __ret = ILIntepreter.Minus(__esp, 1);

            var ptr = ILIntepreter.Minus(__esp, 1);
            object component = StackObject.ToObject(ptr, __domain, __mStack);
            __intp.Free(ptr);

            if (component == null)
            {
                //上面那句Instantiate导致这里报错了，component的位置变成-2了，-1是空的
                Debug.LogError("UnityEngine_Component_Binding.GetTransform instance == null");
                throw new System.NullReferenceException();
            }

            UnityEngine.Transform transform = null;

            if (component is ILTypeInstance)
            {
                IL.MonoBehaviourAdapter.Adaptor adaptor = (component as ILTypeInstance).CLRInstance as IL.MonoBehaviourAdapter.Adaptor;
                transform = adaptor.transform;
            }
            else
            {
                transform = (component as UnityEngine.Component).transform;
            }

            return ILIntepreter.PushObject(__ret, __mStack, transform);
        }

**Comment by liiir1985** [comment]
原则上不建议热更层跨域继承MonoBehaviour， 需要特殊处理还有很多，也不准备完整支持
