### ISSUE TITLE
集成ILRuntime 打包iOS提交Apple Store 被拒4.3(机审)

### ISSUE THREAD

**Issue by JumpWu** [Ourpalm/ILRuntime#299]
已经有两个游戏,都集成了ILRuntime，都被苹果机审4.3了
A包：一直都接入了ILRuntime 一直都大概率4.3
B包：前期没有集成ILRuntime 没有4.3问题，后面集成ILRuntime导致大概率出现4.3

现在A、B包 Unity工程中ILRuntime代码占比超过85%

有什么方式修改ILRtuntime能够避免使用ILRuntime不同包之间的差异（A、B不同游戏）

**Comment by liiir1985** [comment]
最简单的方法是你将部分业务逻辑代码改个命名空间直接复制到主工程中，降低ILRuntime代码占比。然后写个静态public方法随便调几个，这个静态public方法不需要被调用。这样就行了
