### ISSUE TITLE
Json有多个Dictionary时类型处理不正确

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#30]
测试代码如下：

	class MyTest1
	{
		public static void UnitTest_JsonMap()
		{
			string json = "{\"Items1\":{\"one\":{\"Type\":1},\"two\":{\"Type\":2}},\"Items2\":{\"one\":{\"Type\":\"OneType\"},\"two\":{\"Type\":\"TwoType\"}}}";
			MyTestDataMap data =JsonMapper.ToObject<MyTestDataMap> (json);
			Console.WriteLine("Type : " + data.Items1["one"].Type);
			Console.WriteLine("Type : " + data.Items2["one"].Type);
		}
	}

	class MyTestDataItem1 // : TestClass3
	{
		public int Type;
	}

	class MyTestDataItem2 // : TestClass3
	{
		public string Type;
	}

	class MyTestDataMap //: TestClass3
	{
		public Dictionary<string, MyTestDataItem1> Items1;
		public Dictionary<string, MyTestDataItem2> Items2;
	}

在AddObjectMetadata()的时候，Items1和Items2的类型没有区分开来，当处理Items2的时候，ElementType用的还是MyTestDataItem1，因此会报错：
Can't assign value 'OneType' (type System.String) to type Type: Int32

**Comment by larlf** [comment]
对List也一样有影响，测试用例如下：

	class MyTest1
	{
		public static void UnitTest_Json()
		{
			//string json = "{\"Items1\":[{\"Type\":1},{\"Type\":2}]}";
			//string json = "{\"Items2\":[{\"Type\":\"OneType\"},{\"Type\":\"TwoType\"}]}";
			string json = "{\"Items1\":[{\"Type\":1},{\"Type\":2}],\"Items2\":[{\"Type\":\"OneType\"},{\"Type\":\"TwoType\"}]}";
			MyTestDataMap data =JsonMapper.ToObject<MyTestDataMap> (json);
			Console.WriteLine("Type : " + data.Items1[0].Type);
			Console.WriteLine("Type : " + data.Items2[0].Type);
		}
	}

	class MyTestDataItem1 // : TestClass3
	{
		public int Type;
	}

	class MyTestDataItem2 // : TestClass3
	{
		public string Type;
	}

	class MyTestDataMap //: TestClass3
	{
		public List<MyTestDataItem1> Items1;
		public List<MyTestDataItem2> Items2;
	}

**Comment by liiir1985** [comment]
已修复
