### ISSUE TITLE
协程内foreach执行不正常 

### ISSUE THREAD

**Issue by zhu1987** [Ourpalm/ILRuntime#301]
ILRumtime模式下，如果热更层协程函数体内使用foreach，并在作用域内使用yield return null，执行一次后就不能正常执行。

示例：
IEnumerator Test（）
{
    foreach（var item in list）
    {
        yield return null；//只能正常执行一次
    }
}

**Comment by NeoExplore** [comment]
> ILRumtime模式下，如果热更层协程函数体内使用foreach，并在作用域内使用yield return null，执行一次后就不能正常执行。
> 
> 示例：
> IEnumerator Test（）
> {
> foreach（var item in list）
> {
> yield return null；//只能正常执行一次
> }
> }

这个问题现在依然存在，不过目前可以用for循环，不会有这个问题

**Comment by greyhu** [comment]
+1
