### ISSUE TITLE
是否可以在WebGL的项目中使用这套热更方案

### ISSUE THREAD

**Issue by HyphyPan** [Ourpalm/ILRuntime#302]
我们的项目有跨平台的需求，需要编译到Android、IOS、WebGL。目前在Android跟IOS上都没有问题。但是在WebGL运行的时候报异常：NotSupportedException,具体内容是UnSupported internal call for IL2CPP:AppDomain::LoadAssemblyRaw-"This icall is not supported by il2cpp."

**Comment by liiir1985** [comment]
没有试过，原则上只要是能支持unsafe的c#能跑的地方就能支持
