### ISSUE TITLE
同一个方法体无法连续多次调用Invoke

### ISSUE THREAD

**Issue by lfs1023** [Ourpalm/ILRuntime#303]
public void Test(int a, string b)
    {
        Debug.LogError(a + " ---- " + b);
    }

    void Awake()
    {
        for(int i=0; i<5; i++)
        {
            System.Type T = this.GetType();
            T.GetMethod("Test").Invoke(this, new object[] { 1, "2" });
        }
    }

NullReferenceException: Object reference not set to an instance of an object.
ILRuntime.CLR.Method.CLRMethod.Invoke (ILRuntime.Runtime.Intepreter.ILIntepreter intepreter, ILRuntime.Runtime.Stack.StackObject* esp, System.Collections.Generic.IList`1[T] mStack, System.Boolean isNewObj) (at Assets/WMPlatform/HotCSharp/ILRuntime_master/ILRuntime/CLR/Method/CLRMethod.cs:309)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/WMPlatform/HotCSharp/ILRuntime_master/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1797)

**Comment by lfs1023** [comment]
void Awake()
    {
        for(int i=0; i<5; i++)
        {
            test()
        }
    }

    void test()
    {
        System.Type T = this.GetType();
        T.GetMethod("Test").Invoke(this, new object[] { 1, "2" });
    }


but change like this, it works fine

**Comment by liiir1985** [comment]
用最新版ILRuntime测试无法重现

**Comment by liiir1985** [comment]
关闭
