### ISSUE TITLE
CodeGenerationTools不能编译，InterfaceImplementation缺少Resolve方法

### ISSUE THREAD

**Issue by kofhero** [Ourpalm/ILRuntime#304]
最新Master分支的CodeGenerationTools不能编译，InterfaceImplementation缺少Resolve方法
另是否可以添加一下最新Master分支的示例啊，刚接触ILRuntime,使用的是Unity2019,使用老版本的示例方法不会报错，但也调用不了HotFix里的方法

**Comment by liiir1985** [comment]
那个工具是早已过时和不维护的工具了，也不需要去编译
建议你从https://github.com/Ourpalm/ILRuntimeU3D/
Demo入手，这个demo是新版的使用方法

**Comment by kofhero** [comment]
谢谢
