### ISSUE TITLE
生成clr自动绑定代码时，热更代码对主工程的调用无法被分析到

### ISSUE THREAD

**Issue by tinygridlock** [Ourpalm/ILRuntime#309]
class Aaaa
{
    public void FunA1<<T>T>()
    {
        FunA2<<T>T>();
    }

    private void FunA2<T>()
    {
        //在GenerateBindingCode时
        //如果class A先于class B进行Prewarm
        //则FunA2中对主工程的调用就会无法分析到
    }
}

class Bbbb
{
    public void FunB()
    {
        var a = new Aaaa();
        a.FunA1<<T>int>();
    }
}

**Comment by liiir1985** [comment]
你是在GenerateBinding的时候调用了Prewarm接口？

**Comment by tinygridlock** [comment]
我指的是BindingCodeGenerator.CrawlAppdomain里Prewarm相关的逻辑（BindingCodeGenerator.cs 351到375行）。这些逻辑重复执行一遍可以解决问题，原因是第一遍执行时有些泛型T的类型没有确定就跳过了，执行第二遍时泛型T的类型才确定。
