### ISSUE TITLE
Type的Equals()比较结果不正确

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#31]
测试用例如下：

		public static void UnitTest_Type()
		{
			if(typeof(MyTestDataItem1).Equals(typeof(MyTestDataItem2)))
			{
				Console.WriteLine("MyTestDataItem1 == MyTestDataItem2");
			}
			else
			{
				Console.WriteLine("MyTestDataItem1 != MyTestDataItem2");
			}
		}
	}

	class MyTestDataItem1
	{
		public int Type;
	}

	class MyTestDataItem2
	{
		public string Type;
	}

两个不同的类，Type比较的结果是一样的。

**Comment by liiir1985** [comment]
已修复
