### ISSUE TITLE
ILRuntime is still been develeoped, you should not use it in production enviorment yet!

### ISSUE THREAD

**Issue by developerjoy** [Ourpalm/ILRuntime#310]
我在文件上看到「ILRuntime is still been develeoped, you should not use it in production enviorment yet!」，請問現在還是處在開發階段，不能使用在商業產品上嗎？

謝謝。

**Comment by liiir1985** [comment]
英文文档已经2年多没更新过了， ILRuntime早已经可以用于商业产品了，并且用ilruntime已上线的大型项目也不少了
