### ISSUE TITLE
泛型二维数组T[][]运行时new失败

### ISSUE THREAD

**Issue by ldcf4** [Ourpalm/ILRuntime#311]
泛型二维数组T[][]在运行时会new失败;代码如下:
         T[][] _datas = new T[w][];
        for (int i = 0; i<w; i++)
        {
            _datas[i] = new T[h];//<--------ILRuntime new 失败
        }

**Comment by liiir1985** [comment]
T是什么类型？热更里的还是热更外的，是值类型还是引用类型，有没有跨域继承

**Comment by ldcf4** [comment]
T[][] _datas本身定义在一个泛型类中，类似下面这样，具体指定成为热更内定义的引用类型；
public class Array2DTest<T>
{
   T[][] _datas;
}
