### ISSUE TITLE
能不能出一个支持rider的ilruntime调试插件，另外目前的调试插件好像不能支持vs 2019

### ISSUE THREAD

**Issue by ch19751116** [Ourpalm/ILRuntime#315]

**Comment by liiir1985** [comment]
rider的ide插件开发跟vs完全不同，因此没办法支持，只能期待看社区有没有人愿意做了
VS2019的调试插件在群共享里面有，可以加群自取

**Comment by liiir1985** [comment]
Closed

**Comment by RuFengLONG** [comment]
使用rider打开HotFix_Project.sln代码没有高亮，也没有代码提示

**Comment by yyh9488** [comment]
[ILRuntime Rider 插件链接](https://github.com/yyh9488/ILRuntime-Rider-Degguer)
