### ISSUE TITLE
纯热更代码以单例方式调用时异常 InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by wang10998588** [Ourpalm/ILRuntime#318]
构造函数有参数时必定异常，无参数时无异常

class Program
    {
       
        public class TestA
        {
            private static TestA _instance;
            public static TestA Instance
            {
                 get
                 {
                      if (_instance== null)
                      {
                          _instance= new TestA("testerror");
                      }
                      return _instance;
                 }
            }

            private string name = "";
            public TestA(string name)
            {
                 this.name = name;
            }

            public void TestCall(string name)
            {
        
            }
        }

        static void Main()
        {
            TestA.Instance.TestCall("error test");
        }
    }

**Comment by liiir1985** [comment]
Master版ILRuntime测试无法重现

**Comment by wang10998588** [comment]
我刚刚在 Master版ILRuntime 的测试工程下测试确实无法重现，但是我拿最新着Master 版ILRuntime 到unity 的工程下测试 还是有该问题，unity 2018.4.8    scripting runtime version: .Net 4.x    api: .net standard 2.0

**Comment by wang10998588** [comment]
热更的dll 使用 release 编译，必现，以下是我在TestCases项目下的测试代码
public class TestError
    {
        private static TestError _testInstance;
        public static TestError testInstance
        {
            get
            {
                if (_testInstance == null)
                {
                    _testInstance = new TestError("haha");
                }
                return _testInstance;
            }
        }
        private string name = "";
        public TestError(string name)
        {
            this.name = name;
        }

        public void TestCall()
        {
            
        }

        public static void SingletonTest()
        {
            TestError.testInstance.TestCall();
            
        }
    }

**Comment by wang10998588** [comment]
> 
> 
> Master版ILRuntime测试无法重现

热更的dll 使用 release 编译，必现，以下是我在TestCases项目下的测试代码
public class TestError
{
private static TestError _testInstance;
public static TestError testInstance
{
get
{
if (_testInstance == null)
{
_testInstance = new TestError("haha");
}
return _testInstance;
}
}
private string name = "";
public TestError(string name)
{
this.name = name;
}

    public void TestCall()
    {
        
    }

    public static void SingletonTest()
    {
        TestError.testInstance.TestCall();
        
    }
}

**Comment by wang10998588** [comment]
我在RuntimeStack.cs 文件里 PopFrame 函数做如下修改可以解决报错，不确定是不是正解
原版的
if(ret->ObjectType == ObjectTypes.Object)
                {
                    ret->Value = mStackBase;
                    managedStack[mStackBase] = managedStack[returnVal->Value];
                    mStackBase++;
                }

修改后
if(ret->ObjectType == ObjectTypes.Object)
                {
                    managedStack[mStackBase] = managedStack[returnVal->Value];
                    ret->Value = mStackBase;
                    mStackBase++;
                }
