### ISSUE TITLE
如何实现完全接管Unity工程里的某个脚本或者某个方法，让Unity工程和Hotfix工程调用该接口都走到接管后的接口里去。

### ISSUE THREAD

**Issue by SturgeonDu** [Ourpalm/ILRuntime#320]
实际案例需求：
比如Unity项目里有一个类A里的某个函数里存在一个BUG，现在急需通过热更新的方式修复该问题。
类A可能是单例，MonoBehaviour,其他任何逻辑脚本balalala..
修复后的结果希望是无论Unity内部调用到该函数还的这个方法还是Hotfix工程里调用该函数都最终指向接管后的函数。
才刚刚接触ILRuntime两天，想到了三个方案：
方案一： 
使用CLRRedirection重定向的方式，把该接口重定向到新的接口里，发现只能在Hotfix工程里有效，Unity工程里还是调用的原来的函数。**不能达到热更新修复的目的。**
方案二：
使用跨域继承的方法，提前在Unity工程里写好继承适配器，遇到该脚本出现问题的话就在Hotfix工程里继承该脚本然后重写该函数。
但是这个方法目前我没有去测试，原因有二：
1.想要到Hotfix工程去继承该脚本需要提前些适配器，特别麻烦，工程里脚本那么多多麻烦。这个方法太笨了。
2.除了写适配器外还要给成员加virtual和protected巨麻烦。
方案三：
用Xlua埋点的方式去定点热更新。
也没有实验，因为考虑使用ILRuntime就是因为工程里全是C#的脚本 ，才考虑使用ILRuntime做热更新。如果用Xlua的话为何当初不直接采用tolua，不香吗？

我也是才接触ILRuntime 2天，可能有些东西还没了解透彻，大伙儿 有没有更好的建议？？

**Comment by liiir1985** [comment]
ILRuntime的正确用法是将业务逻辑直接写在热更当中，直接整个dll更新

当然也有类似XLua的解决方案，例如隔壁XIL，还有ET框架也实现了类似功能
