### ISSUE TITLE
GetInvocationList 返回的 Delegate[] Length 总是为1

### ISSUE THREAD

**Issue by woodzong** [Ourpalm/ILRuntime#322]
void LocalActionTest(int TestNum1)
            {
                Debug.Log($"LocalActionTest {TestNum1}");
            };
            System.Action<int> TestActionList = null;
            TestActionList += LocalActionTest;
            TestActionList += LocalActionTest;
            TestActionList.Invoke(1);
            System.Delegate[] DeleArr = TestActionList.GetInvocationList();
            Debug.Log($"DelegateArrNum {DeleArr.Length} {TestActionList.GetType()}");

上述代码, 在ILRuntime下跑.  DeleArr.Length 的值总是为1, 但按正常逻辑应该是2 才对, 在普通.net环境下跑, 也的确是2.  不知道是不是触发了某个bug.
P.S: 运行前, 要在主工程下注册:
appdomain.DelegateManager.RegisterMethodDelegate<System.Int32>();

**Comment by liiir1985** [comment]
ILRuntime的委托不是标准系统委托对象，因此不支持除了调用以外的功能
