### ISSUE TITLE
通过反射创建枚举异常

### ISSUE THREAD

**Issue by lvfoxx** [Ourpalm/ILRuntime#328]
private static object ParseString(string strValue, Type t) {
var cv = TypeDescriptor.GetConverter(t);
return cv.ConvertFromInvariantString(strValue);
}
当t为枚举类型时，cv.ConvertFromInvariantString(strValue) 抛出异常
ArgumentException: Type must be a type provided by the runtime.
Parameter name: enumType
Rethrow as ILRuntimeException: confirm is not a valid value for TextType.

private static object ParseString(string strValue, Type t) {
if (t.BaseType == typeof(Enum)) {
return Enum.Parse(t, strValue);
}
...
}
通过这种方式可以创建出枚举，但是用以下代码赋值之后
private static bool SetField(string fieldName, string val, FieldInfo[] fi, PropertyInfo[] pi, object destObject) {
...
for (int i = 0; i < pi.Length; ++i) {
var p = pi[i];
p.SetValue(destObject, ParseString(val, p.PropertyType), null);
}
...
}
调用时报空指针错误，定位到主工程的 AssignFromStackSub 函数 managedObjs数组为空

**Comment by lvfoxx** [comment]
private static object ParseString(string strValue, Type t) {
var cv = TypeDescriptor.GetConverter(t);
return cv.ConvertFromInvariantString(strValue);
}
当t为枚举类型时，cv.ConvertFromInvariantString(strValue) 抛出异常
ArgumentException: Type must be a type provided by the runtime.
Parameter name: enumType
Rethrow as ILRuntimeException: confirm is not a valid value for TextType.

private static object ParseString(string strValue, Type t) {
if (t.BaseType == typeof(Enum)) {
return Enum.Parse(t, strValue);
}
...
}
通过这种方式可以创建出枚举，但是用以下代码赋值之后
private static bool SetField(string fieldName, string val, FieldInfo[] fi, PropertyInfo[] pi, object destObject) {
...
for (int i = 0; i < pi.Length; ++i) {
var p = pi[i];
p.SetValue(destObject, ParseString(val, p.PropertyType), null);
}
...
}
调用时报空指针错误，定位到主工程的 AssignFromStackSub 函数 managedObjs数组为空

**Comment by lvfoxx** [comment]
经测试，修改ILTypeInstance.cs文件的public unsafe object this[int index] 函数相关内容为如下代码，可以正常运行。
var vt = value.GetType(); 
if (vt.IsPrimitive) 
{
	ILIntepreter.UnboxObject(esp, value, managedObjs, type.AppDomain); 
} 
else 
{ 
	bool isEnum = false; 
	if (value is ILTypeInstance) 
	{ 
		isEnum = ((ILTypeInstance) value).Type.IsEnum; 
	} 
	if (vt.IsEnum || isEnum) 
	{
		 esp->ObjectType = ObjectTypes.Integer; 
		 esp->Value = value.ToInt32(); 
		 esp->ValueLow = 0; 
	} 
	else 
	{ 
		esp->ObjectType = ObjectTypes.Object; 
		esp->Value = index; 
		managedObjs[index] = value; 
	} 
}

**Comment by bluesliu** [comment]
> 经测试，修改ILTypeInstance.cs文件的public unsafe object this[int index] 函数相关内容为如下代码，可以正常运行。 var vt = value.GetType(); if (vt.IsPrimitive) { ILIntepreter.UnboxObject(esp, value, managedObjs, type.AppDomain); } else { bool isEnum = false; if (value is ILTypeInstance) { isEnum = ((ILTypeInstance) value).Type.IsEnum; } if (vt.IsEnum || isEnum) { esp->ObjectType = ObjectTypes.Integer; esp->Value = value.ToInt32(); esp->ValueLow = 0; } else { esp->ObjectType = ObjectTypes.Object; esp->Value = index; managedObjs[index] = value; } }

枚举确实可以反射创建了，但是 event += 会报错。
原因是： `isEnum = ((ILTypeInstance) value).Type.IsEnum;` 这段代码中， `(ILTypeInstance) value`强转后值为null，加上非空判断就可以了。
