### ISSUE TITLE
try catch执行函数无法获取精确的出错堆栈

### ISSUE THREAD

**Issue by linchenrr** [Ourpalm/ILRuntime#329]
首先我封装了一个通用的消息处理函数管理类
类似
`using Cmd;
using Google.Protobuf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEngine;

public delegate void TestHandlerDelegate(object args);

public class TestHandlerGroup
{

    private LinkedList<TestHandlerDelegate> list_handler = new LinkedList<TestHandlerDelegate>();

    public void RegisterHandler(TestHandlerDelegate handler)
    {
        RemoveHandler(handler);
        list_handler.AddLast(handler);
    }

    public void RemoveHandler(TestHandlerDelegate handler)
    {
        var node = list_handler.First;
        while (node != null)
        {
            var nextNode = node.Next;
            if (node.Value == handler)
            {
                list_handler.Remove(node);
                break;
            }
            node = nextNode;
        }
    }

    public void CallHandler(object args)
    {
        var node = list_handler.First;
        while (node != null)
        {
            var nextNode = node.Next;
            try
            {
                node.Value(args);
            }
            catch (Exception e)
            {
                Debug.LogException(e);
                Debug.LogError(e.StackTrace);
            }
            node = nextNode;
        }
    }
}

`

然后模拟使用时报错情况
`using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using UnityEngine;
using UnityEngine.UI;

public class PanelB : ILPanel<string>
{

    private TestHandlerGroup testHandlerGroup = new TestHandlerGroup();
    protected override void Awake()
    {
        testHandlerGroup.RegisterHandler(handleA);
        testHandlerGroup.CallHandler(new object());
    }

    private void handleA(object args)
    {
        throw new Exception("sss");
    }

}

`

这时候打印出的异常信息为
System.Exception: sss
  at ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) [0x08be0] in C:\work\unity\Proj\trunk\projectStarlike\Assets\ILRuntime\ILRuntime\Runtime\Intepreter\ILIntepreter.cs:4142 
IL_0036: call System.Void UnityEngine.Debug::LogException(System.Exception)
at TestHandlerGroup.CallHandler(Object args) C:\work\unity\Proj\trunk\projectStarlike\Assets\ILScripts\Test\TestHandlerInfo.cs:Line 51
at PanelB.Awake() C:\work\unity\Proj\trunk\projectStarlike\Assets\ILScripts\Test\PanelB.cs:Line 17

UnityEngine.Debug:LogError(Object)
ILRuntimeManager:LogException(ILIntepreter, StackObject*, IList`1, CLRMethod, Boolean) (at Assets/ILRuntime/FrameWork/ILRuntimeManager.cs:449)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1802)
ILRuntime.Runtime.Intepreter.ILIntepreter:Execute(ILMethod, StackObject*, Boolean&) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1778)
ILRuntime.Runtime.Intepreter.ILIntepreter:Run(ILMethod, Object, Object[]) (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:96)
ILRuntime.Runtime.Enviorment.AppDomain:Invoke(IMethod, Object, Object[]) (at Assets/ILRuntime/ILRuntime/Runtime/Enviorment/AppDomain.cs:1106)
ILRuntime.Runtime.Intepreter.MethodDelegateAdapter:InvokeILMethod() (at Assets/ILRuntime/ILRuntime/Runtime/Intepreter/DelegateAdapter.cs:676)
ILBehaviourAdapter:Awake() (at Assets/ILRuntime/FrameWork/ILBehaviourAdapter.cs:68)
UnityEngine.Object:Instantiate(GameObject)
<>c__DisplayClass37_0:<LoadUIAsync>b__0(GameObject) (at Assets/Scripts/KLib/UI/UIManager.cs:353)
AssetLoadOperation`1:Done(GameObject) (at Assets/Scripts/KLib/common/AsyncOperations.cs:41)
<doLoadAsync>d__19`1:MoveNext() (at Assets/Scripts/KLib/common/ResourceManager.cs:260)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

只能定位到TestHandlerInfo的51行，而实际堆栈应该到PanelB的22行

**Comment by liiir1985** [comment]
自行try catch的异常 需要使用ex.Data["StackTrace"]获取实际的出错堆栈
