### ISSUE TITLE
请问在热更新代码中支持这两个库么？

### ISSUE THREAD

**Issue by ckcfcc** [Ourpalm/ILRuntime#343]
UniRX
UniTask

请问在热更里支持使用这两个库么？

**Comment by liiir1985** [comment]
由于没有用过这两个库因此也不知道使用会不会有问题， ILRuntime对于使用绝大多数的库是没问题的，唯一会产生问题的是序列化相关的（因为序列化库不知道热更的存在，因此没有热更相关的处理）
