### ISSUE TITLE
TryGetComponent导致闪退的问题

### ISSUE THREAD

**Issue by yomunsam** [Ourpalm/ILRuntime#344]
虽然我估计没人会这么干，emm，但姑且是记录一下有这么个问题吧（

故事是这样的，首先，在热更新工程里写一个属性：

``` csharp
public class HotCat
{
    public UnityEngine.UI.Button MyBtn {get;set;}
}
```

然后，在主工程里通过反射获取到这个`MyBtn`的Type，就是那个看起来是`Button`实际上是`ILRuntimeType`的Type.

然后交给[TryGetComponent](https://docs.unity3d.com/ScriptReference/GameObject.TryGetComponent.html)方法之后，整个引擎就会bia叽一下没了（

（不过想了一下，好像除了禁止这种写法之外，也没啥好的解决方法，吧

**Comment by liiir1985** [comment]
这个你可以参考Demo的MonoBehaviour示例，里面有个GetComponent的 重定向，对于这种需求都需要自行添加特殊处理的重定向才能好使
