### ISSUE TITLE
跨域继承的class包含有泛型字段，如果这个class的方法对这个泛型字段赋值，会把栈写坏

### ISSUE THREAD

**Issue by qiulirui** [Ourpalm/ILRuntime#346]
附带有例程，对泛型字段赋值之后，再调用基类的任何方法都会报错。可能是this指针被破坏了。
[跨域继承+泛型字段issue.zip](https://github.com/Ourpalm/ILRuntime/files/4857100/%2B.issue.zip)

**Comment by ungod** [comment]
+1
