### ISSUE TITLE
对象数组引用传递的问题

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#35]
当一个对象数组，在使用out参数传递时会出错，测试代码如下：

		public static void UnitTest_Out2()
		{
			Dictionary<string, TestClassC[]> data = new Dictionary<string, TestClassC[]>();
			data["key"] = new TestClassC[0];
			TestClassC[] item;
			data.TryGetValue("key", out item);
			Console.WriteLine("value : " + item);
		}

		class TestClassC
		{
		}

**Comment by liiir1985** [comment]
已修复
