### ISSUE TITLE
以下案例会导致ILRuntime报错，详见测试案例

### ISSUE THREAD

**Issue by kingdachong** [Ourpalm/ILRuntime#350]
namespace UIPP
{
    public abstract class BaseUIView
    {
        public virtual bool Init()
        {
            return true;
        }
        public abstract string GetPrefabPath();
        public virtual void Dispose() { }
    }

    public abstract class BaseUIPresenter
    {
        public BaseUIPresenter()
        {
        }
        public abstract void SetView(BaseUIView view);

        public virtual bool Init()
        {
            return true;
        }
        public virtual void Dispose()
        {
        }
    }
    public abstract class ContractUIPresenter<V> : BaseUIPresenter where V : BaseUIView
    {
        private V view = null;
        public V View
        {
            get { return this.view; }
        }
        public override bool Init()
        {
            if (base.Init() == false)
            {
                return false;
            }

            return true;
        }
        public override void Dispose()
        {
            base.Dispose();
        }
        public override void SetView(BaseUIView view)
        {
            this.view = view as V;
        }
    }
    public abstract class ContractUIView<P> : BaseUIView where P : BaseUIPresenter
    {
        private P presenter = null;
        public P Presenter
        {
            get { return this.presenter; }
        }
        public abstract P GetAttachPresenter();
        public override bool Init()
        {
            if (base.Init() == false)
            {
                return false;
            }
            this.presenter = GetAttachPresenter();
            if (this.presenter != null)
            {
                this.presenter.SetView(this);
            }
            return true;
        }
        public override void Dispose()
        {
            if (this.presenter != null)
            {
                this.presenter.SetView(null);
                this.presenter = null;
            }
            base.Dispose();
        }
    }

    public sealed class UI_Contract
    {
        public abstract class View : ContractUIView<Presenter>
        {
            public abstract void OnUpdate();
        }

        public abstract class Presenter : ContractUIPresenter<View>
        {
            public abstract void Skip();
            public abstract void OnUpdate();
        }
    }
    public sealed class UI_Presenter : UI_Contract.Presenter
    {
        public override void Skip()
        {
        }

        public override void OnUpdate()
        {
        }
    }

    public sealed class UI_View : UI_Contract.View
    {
        public override UI_Contract.Presenter GetAttachPresenter()
        {
            return null;
        }

        public override string GetPrefabPath()
        {
            return "";
        }

        public override void OnUpdate()
        {
            //throw new NotImplementedException();
        }
    }
}

var p = new UIPP.UI_Presenter(); // 这一行ILRuntime就会直接报错终止运行，1.4版本是没有问题的
var p2 = new UIPP.UI_View (); // 这一行ILRuntime就会直接报错终止运行，1.4版本是没有问题的

**Comment by liiir1985** [comment]
全部都在热更内定义还是有跨域继承

**Comment by kingdachong** [comment]
全部代码在热更层，没有跨域继承，经过测试发现是范型成员变量初值的问题，去掉 = null 就不会报错了

**Comment by liiir1985** [comment]
已修复
