### ISSUE TITLE
ref struct报错

### ISSUE THREAD

**Issue by VincentSai** [Ourpalm/ILRuntime#354]
用到个第三方库使用了ref struct，运行时会发生ILIntepreter的mStack ArgumentOutOfRangeException

[GameTest.zip](https://github.com/Ourpalm/ILRuntime/files/4918111/GameTest.zip)
附件放到热更工程编译后使用
appdomain.Invoke("HotFix_Project.GameTest", "Initialize", null, null);

**Comment by liiir1985** [comment]
ref struct不被支持
