### ISSUE TITLE
1.63版本 主工程中event类型 ，在热更工程中+= 注册使用，  clr绑定现在不生成绑定代码？ 

### ISSUE THREAD

**Issue by dylanisbest** [Ourpalm/ILRuntime#359]
主工程测试类：

class TestEventDemo
{
    private static TestEventDemo _singleton;
    public static TestEventDemo singleton
    {
        get
        {
            if (_singleton == null)
            {
                _singleton = new TestEventDemo();
            }
            return _singleton;
        }
    }

    public event Action testAction1;

}

热更新工程使用的类
class TestCase
{
    public static void TestEvent()
    {
        TestEventDemo.singleton.testAction1 += () => { 
        
        };
    }
}

**Comment by xiongjie1207** [comment]
也遇到这个问题，有什么解决办法？
