### ISSUE TITLE
值绑定相关 从Unity调用热更项目方法传入Vector2参数并使用时报NullReferenceException

### ISSUE THREAD

**Issue by ChaoYang-PengYuYan** [Ourpalm/ILRuntime#361]
[11_ValueTypeBinding.zip](https://github.com/Ourpalm/ILRuntime/files/4970304/11_ValueTypeBinding.zip)

压缩包内ValueTypeBindingDemo.cs是Unity代码,TestValueType.cs是热更项目代码.

报错信息:
NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Intepreter.ILIntepreter.CopyToStack (ILRuntime.Runtime.Stack.StackObject* dst, ILRuntime.Runtime.Stack.StackObject* src, System.Collections.Generic.IList`1[T] mStack) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:5137)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:268)
Rethrow as ILRuntimeException: Object reference not set to an instance of an object
IL_000d: ldarg.0
HotFix_Project.TestValueType.RunTest(Vector2 param) Assets/Samples/ILRuntime/1.6.2/Demo/HotFix_Project~/TestValueType.cs:Line 16

**Comment by liiir1985** [comment]
你试试master上的代码，修复了一个类似的问题，看看还有没有这个问题
