### ISSUE TITLE
访问热更层的泛型委托数组会报错

### ISSUE THREAD

**Issue by kingdachong** [Ourpalm/ILRuntime#362]
以下代码均在Hotfix层

public delegate U ValueCallBack<U>();
public class TestCallBack
{
	private ValueCallBack<int>[] callback_list = {
		callbackA,
		callbackB
	};
	
	public void Invoke()
	{
		callback_list[0].Invoke(); // 这句话会报错
	}
	
	private static int callbackA()
	{
		return 0;
	}
	private static int callbackB()
	{
	        return 1;
	}
}
var test = new TestCallBack();
test.Invoke();

调用以上热更代码就会报报错，用mono跑就没有问题

**Comment by kingdachong** [comment]
之前的描述有问题，我改了下

**Comment by liiir1985** [comment]
最新Master版无法重现
