### ISSUE TITLE
请教一下，适用于UnityEngine ScriptObject的跨域继承adapter应该怎么写

### ISSUE THREAD

**Issue by YDC923092666** [Ourpalm/ILRuntime#363]
是这样写吗？
`using UnityEngine;

using ILRuntime.CLR.Method;
using ILRuntime.Runtime.Enviorment;
using ILRuntime.Runtime.Intepreter;
using System;

namespace ILRuntime.Runtime.Adaptors
{
	public class ScriptableObjectAdaptors : CrossBindingAdaptor
    {
        public override Type AdaptorType
        {
            get
            {
                return typeof(Adaptor);
            }
        }

        public override Type BaseCLRType
        {
            get
            {
                return typeof(ScriptableObject);
            }
        }

        public override object CreateCLRInstance(Enviorment.AppDomain appdomain, ILTypeInstance instance)
        {
            return new Adaptor(appdomain, instance);
        }

        class Adaptor : ScriptableObject, CrossBindingAdaptorType
        {
            ILTypeInstance instance;
            ILRuntime.Runtime.Enviorment.AppDomain appdomain;

            IMethod mCreateInstance;

            public Adaptor()
            {

            }

            public Adaptor(ILRuntime.Runtime.Enviorment.AppDomain appdomain, ILTypeInstance instance)
            {
                this.appdomain = appdomain;
                this.instance = instance;
            }

            public ILTypeInstance ILInstance { get { return instance; } set { instance = value; } }

            public override string ToString()
            {
                IMethod m = appdomain.ObjectType.GetMethod("ToString", 0);
                m = instance.Type.GetVirtualMethod(m);
                if (m == null || m is ILMethod)
                {
                    return instance.ToString();
                }
                else
                    return instance.Type.FullName;
            }
        }
    }
}
`

**Comment by liiir1985** [comment]
能继承也没用， 所有你热更里定义的字段unity都不认，你也没法编辑
