### ISSUE TITLE
ILRuntime里用异步Task，多个异步嵌套会出现问题，严重的时候死机。

### ISSUE THREAD

**Issue by qq362946** [Ourpalm/ILRuntime#365]
ILRuntime里用异步Task。你们用着有问题吗，我怎么一嵌套Task就会出现问题，有时候回死机。
麻烦解决下，因为异步使用还是蛮多的，如果不支持，那这个热更我们没办法使用。

**Comment by liiir1985** [comment]
在最新master中修复一个Async的问题，重新生成CLR绑定后试一下是否已修复
