### ISSUE TITLE
热更Dll里包含如下语句，则 自动生成绑定代码的时候就会报错

### ISSUE THREAD

**Issue by kingdachong** [Ourpalm/ILRuntime#369]
OrderedDictionary<int, int> keyValuePairs = new OrderedDictionary<int, int>();
 var a = keyValuePairs[1];

只要在Hotfix曾任意处增加该代码，再用 ILRuntime.Runtime.CLRBinding.BindingCodeGenerator.GenerateBindingCode 函数生成绑定代码必然会报错。1.6.3可重现

**Comment by liiir1985** [comment]
OrderedDictionary在Unity中并不存在，你这是自己安装的nuget包扩展的吧

**Comment by kingdachong** [comment]
确实，这个是扩展，用的是以下的代码
https://github.com/jehugaleahsa/truncon.collections.OrderedDictionary/blob/master/Truncon.Collections/OrderedDictionary.cs

**Comment by liiir1985** [comment]
只能使用unity自带的或者以dll形式放在plugin目录里的类库，或者主工程的类型

**Comment by kingdachong** [comment]
这个类是在我的主工程里的，是ET框架Model层用的一个第三方的代码类
