### ISSUE TITLE
char类型转换成字符串的问题

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#37]
发现char类型在转换成字符串的时候，同样的代码生成的IL会有差异（但都是vs2015，原因还不清楚）
第一种：
		IL_00f2: ldloca.s c
		IL_00f4: call instance string [mscorlib]System.Char::ToString()
		IL_00f9: call string [mscorlib]System.String::Concat(string, string)
第二种：
		IL_00e6: ldloca.s c
		IL_00e8: constrained. [mscorlib]System.Char
		IL_00ee: callvirt instance string [mscorlib]System.Object::ToString()
		IL_00f3: call string [mscorlib]System.String::Concat(string, string)

第一种执行的结果正常，第二种字符转换成字符串后会变成数字。

**Comment by liiir1985** [comment]
已修复
