### ISSUE TITLE
热更域容器无法Add 主域持有的热更域对象

### ISSUE THREAD

**Issue by luojingzhao** [Ourpalm/ILRuntime#370]
#### 主域：

```c#
public interface IHostA
{
    void Add(object instance);
}

public interface IHostB
{
}


public class HostClass
{
    public IHostA hostA;

    public void Init(IHostB b)
    {
        hostA.Add(b);
    }
}


/*
 * IHostA 、IHotfix已生成跨域继承适配器
 */
```

#### 热更域

```C#
public class HotfixA : IHostA
{
	List<IHotfix> ls = new List<IHotfix>();

	public void Add(object instance)
    {
		if (instance is IHotfix hotfix)
        {
        	ls.Add(hotfix);
        }
	}
}

public interface IHotfix
{
}

public class HotfixClass : IHotfix, IHostB
{
}

public class Main
{
	public void Init()
    {
 		HostClass hotclass = new HostClass();
        hotclass.hostA = new HotfixA();
        hotclass.Init(new HotfixClass());
    }
}
```

#### 结果

> InvalidCastException: Specified cast is not valid.
> ILRuntime.Runtime.Generated.System_Collections_Generic_List_1_ILTypeInstance_Binding.Add_0 (ILRuntime.Runtime.Intepreter.ILIntepreter __intp, ILRuntime.Runtime.Stack.StackObject* __esp, System.Collections.Generic.IList`1[T] __mStack, ILRuntime.CLR.Method.CLRMethod __method, System.Boolean isNewObj) (CLRBinding/System_Collections_Generic_List_1_ILTypeInstance_Binding.cs:64)
> ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) 

测试发现是HotfixA的Add(object instance)方法中的instance对象是适配器对象

**Comment by liiir1985** [comment]
跨域继承就不能多继承了，会无法确定对象最终应该是何类型表达
