### ISSUE TITLE
Quaternion值类型绑定后，修改结构体Field数值不正确

### ISSUE THREAD

**Issue by Ojors** [Ourpalm/ILRuntime#372]
参考ILRuntimeU3D的Demo工程，用上面Examples里的QuaternionBinder进行值类型绑定，在修改结构体的Field数值时，会出现Field修改出错的问题，而Vector3类型的绑定没有这个问题

另外如果不进行这个值类型Binder的注册，用自动分析生成的CLR Binding代码，不会出现这个问题

主工程注册：
appdomain.RegisterValueTypeBinder(typeof(Quaternion), new QuaternionBinder());
 
热更工程测试代码：
Quaternion q = new Quaternion(0.1f, 0.2f, 0.3f, 1);
Debug.Log("New Quaternion = " + q);  // 此时数值正常
q.w = 0;
Debug.Log("Modify Quaternion = " + q);  // 数值修改出错，修改w，这里实际被修改的是z

该问题在最新的ILRuntimeU3D的Demo工程就能稳定复现

**Comment by liiir1985** [comment]
已修复，等1.6.4发布
