### ISSUE TITLE
在自动生成跨域继承适配器代码中 递归调用时 第2次及之后 会只调用基类(适配器)中的代码

### ISSUE THREAD

**Issue by devehuang** [Ourpalm/ILRuntime#376]
刚更新到1.6.4中还存在

原因：
CrossBindingMethodInfo::Invoke(){
  ...
  invoking = true // 因此值为true 在后续的递归调用中 将只调用到基类(适配器)中的方法
  ...
}

临时解决：
public class FxLogicBaseAdapter : CrossBindingAdaptor
{
	...
	public override void Restart()
	{
		if (!Global.Adapter_IgnoreInvokeFlag_FxLogic && mRestart_5.CheckShouldInvokeBase(this.instance))
			base.Restart();
		else
			mRestart_5.Invoke(this.instance);
	}
	...
Global.Adapter_IgnoreInvokeFlag_FxLogic = true;

**Comment by liiir1985** [comment]
这个并不能这么修复，跨域override的方法需要避免递归，否则会出现无限递归的问题，而且从ilruntime层面根本无法得知你的调用中是否会中断递归
