### ISSUE TITLE
GetClassName()不同类型生成名称重复

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#38]
下面两种不同的类型，用此方法生成的名称是一样的：

			typeof(Dictionary<string, ILTypeInstance>).GetClassName(out className, out realClassName, out isByRef);
			Console.WriteLine(className);
			typeof(Dictionary<string, ILTypeInstance[]>).GetClassName(out className, out realClassName, out isByRef);
			Console.WriteLine(className);

都是：
System_Collections_Generic_Dictionary_2_String_ILTypeInstance_Binding

**Comment by liiir1985** [comment]
已修复
