### ISSUE TITLE
LitJson  JsonMapper.ToObject<List<热更类型>> 报错

### ISSUE THREAD

**Issue by FingerCaster** [Ourpalm/ILRuntime#381]
![image](https://user-images.githubusercontent.com/31885840/93958583-62e8eb00-fd89-11ea-920d-9fbeb432c676.png)
![image](https://user-images.githubusercontent.com/31885840/93958601-6b412600-fd89-11ea-9d50-54d21627bba4.png)
![image](https://user-images.githubusercontent.com/31885840/93958560-582e5600-fd89-11ea-8e9a-0eadd7d28d8e.png)

**Comment by liiir1985** [comment]
请看Demo关于litjson的用法，没有注册对应的适配器
