### ISSUE TITLE
GC.Collect不起作用

### ISSUE THREAD

**Issue by huang8603543** [Ourpalm/ILRuntime#39]
我使用最新版的UnityDemo测试时发现GC.Collect无法回收堆内存。

测试代码：
using System.Collections.Generic;
using UnityEngine;

namespace HotFix_Project
{
    public static class TestGC
    {
        static DataManager dataManager;
        public static void Start()
        {
            Debug.Log("Start!");
            dataManager = new DataManager();
            dataManager.FillCollections();
        }

        public static void CallGC()
        {
            Debug.Log("CallGC!");
            dataManager.CallGC();
        }
    }

    public class DataManager
    {
        //ArrayCollectionA ca;
        //ArrayCollectionB cb;

        ListCollectionA ca;
        ListCollectionB cb;

        public void FillCollections()
        {
            //cb = new ArrayCollectionB();
            //ca = new ArrayCollectionA(cb);

            cb = new ListCollectionB();
            ca = new ListCollectionA(cb);
        }

        public void CallGC()
        {
            cb = null;
            ca = null;           
        }
    }

    public class ArrayCollectionA
    {
        int[] m_array;

        ArrayCollectionB m_tb;

        public ArrayCollectionA(ArrayCollectionB tb)
        {
            m_array = new int[100000000];

            m_tb = tb;
            m_tb.TestFun();
        }
    }

    public class ArrayCollectionB
    {
        int[] m_array;

        public ArrayCollectionB()
        {
            m_array = new int[100000000];
        }

        public void TestFun()
        {
            Debug.LogError("Fill Start");
        }
    }

    public class ListCollectionA
    {
        List<IntWarp> m_list;
        ListCollectionB lcb;

        public ListCollectionA(ListCollectionB lcb)
        {
            m_list = new List<IntWarp>(100000000);
            this.lcb = lcb;
            lcb.TestFun();
        }

    }

    public class ListCollectionB
    {
        List<IntWarp> m_list;

        public ListCollectionB()
        {
            m_list = new List<IntWarp>(100000000);
        }

        public void TestFun()
        {
            Debug.Log("Fill Start");
        }
    }

    public class IntWarp
    {
        public int i;
    }
}

修改了一下Unity工程中的代码：
using UnityEngine;
using System.Collections;
using System.IO;
using ILRuntime.Runtime.Enviorment;
using System.Reflection;
using System;

public class ReflectionDemo : MonoBehaviour
{
    ILRuntime.Runtime.Enviorment.AppDomain appdomain;
    Assembly assembly;
    void Start()
    {
        StartCoroutine(LoadHotFixAssembly());
        //StartCoroutine(LoadReflectorAssembly());
    }

    IEnumerator LoadHotFixAssembly()
    {
        appdomain = new ILRuntime.Runtime.Enviorment.AppDomain();
#if UNITY_ANDROID
        WWW www = new WWW(Application.streamingAssetsPath + "/HotFix_Project.dll");
#else
        WWW www = new WWW("file:///" + Application.streamingAssetsPath + "/HotFix_Project.dll");
#endif
        while (!www.isDone)
            yield return null;
        if (!string.IsNullOrEmpty(www.error))
            UnityEngine.Debug.LogError(www.error);
        byte[] dll = www.bytes;
        www.Dispose();
#if UNITY_ANDROID
        www = new WWW(Application.streamingAssetsPath + "/HotFix_Project.pdb");
#else
        www = new WWW("file:///" + Application.streamingAssetsPath + "/HotFix_Project.pdb");
#endif
        while (!www.isDone)
            yield return null;
        if (!string.IsNullOrEmpty(www.error))
            UnityEngine.Debug.LogError(www.error);
        byte[] pdb = www.bytes;
        using (System.IO.MemoryStream fs = new MemoryStream(dll))
        {
            using (System.IO.MemoryStream p = new MemoryStream(pdb))
            {
                appdomain.LoadAssembly(fs, p, new Mono.Cecil.Pdb.PdbReaderProvider());
            }
        }

        InitializeILRuntime();
        OnHotFixLoaded();

        yield return new WaitForSeconds(5.0f);
        ILCallGC();
    }

    IEnumerator LoadReflectorAssembly()
    {
#if UNITY_ANDROID
        WWW www = new WWW(Application.streamingAssetsPath + "/HotFix_Project.dll");
#else
        WWW www = new WWW("file:///" + Application.streamingAssetsPath + "/HotFix_Project.dll");
#endif
        while (!www.isDone)
            yield return null;
        if (!string.IsNullOrEmpty(www.error))
            UnityEngine.Debug.LogError(www.error);
        byte[] dll = www.bytes;
        www.Dispose();

#if UNITY_ANDROID
        www = new WWW(Application.streamingAssetsPath + "/HotFix_Project.pdb");
#else
        www = new WWW("file:///" + Application.streamingAssetsPath + "/HotFix_Project.pdb");
#endif
        while (!www.isDone)
            yield return null;
        if (!string.IsNullOrEmpty(www.error))
            UnityEngine.Debug.LogError(www.error);
        byte[] pdb = www.bytes;

        assembly = Assembly.Load(dll, pdb);

        OnReflectorAssemblyLoaded();

        yield return new WaitForSeconds(5.0f);
        ReflectionCallGC();
    }

    void InitializeILRuntime()
    {

    }

    void OnHotFixLoaded()
    {
        var it = appdomain.LoadedTypes["HotFix_Project.TestGC"];
        var m = it.GetMethod("Start", 0);
        appdomain.Invoke(m, null, null);       
    }

    void OnReflectorAssemblyLoaded()
    {
        Type t = assembly.GetType("HotFix_Project.TestGC");
        MethodInfo m = t.GetMethod("Start");
        m.Invoke(null, null);
    }

    void ILCallGC()
    {
        var it = appdomain.LoadedTypes["HotFix_Project.TestGC"];
        var m = it.GetMethod("CallGC", 0);
        appdomain.Invoke(m, null, null);
        GC.Collect();
        Debug.Log("GC Complete");
    }

    void ReflectionCallGC()
    {
        Type t = assembly.GetType("HotFix_Project.TestGC");
        MethodInfo m = t.GetMethod("CallGC");
        m.Invoke(null, null);
        GC.Collect();
        Debug.Log("GC Complete");
    }
}

发现使用Reflector模式GC回收正常，但是ILRuntime模式下不行

**Comment by liiir1985** [comment]
谢谢提供测试代码
对静态变量设置=null的时候的确有可能不即时释放，但是也不会出现泄露的问题，因为你替换成其他变量他也就被释放了
目前这个问题已修复
