### ISSUE TITLE
我在热更工程中传递Vector3，修改参数的值，会把原来的Vector3值修改

### ISSUE THREAD

**Issue by yongyoung888** [Ourpalm/ILRuntime#390]

**Comment by YonggangFeng** [comment]
![Snipaste_2020-10-16_20-27-41](https://user-images.githubusercontent.com/3353661/96258764-16db4000-0fef-11eb-8e44-c5778809cd36.png)
![Snipaste_2020-10-16_20-27-55](https://user-images.githubusercontent.com/3353661/96258770-180c6d00-0fef-11eb-96c0-b2d24ee67b0d.png)
