### ISSUE TITLE
枚举用Equals判断再ILRuntime Hotfix层运行时结果会错误

### ISSUE THREAD

**Issue by kingdachong** [Ourpalm/ILRuntime#391]
public class TestCase
 {
        enum enumInfo
        {
            en1 = 0,
            en2 = 1,
            en3 = 2,
        }

        public bool Test2()
        {
            enumInfo taskState = enumInfo.en2;
            //bool b = taskState.Equals(enumInfo.en2);
            if (taskState.Equals(enumInfo.en2))
            //if(b)
            {
                Log.Info("Test2 Success!");
                return true;
            }
            Log.Error("Test2 fail!");
            return false;
        }
    }

TestCase test = new TestCase();
test.Test2();

以上代码都在热更层

**Comment by liiir1985** [comment]
使用最新master版无法重现，更新一下试试吧
