### ISSUE TITLE
Texture.GetNativeTexturePtr()在热更新里面抛出异常

### ISSUE THREAD

**Issue by UtilXK** [Ourpalm/ILRuntime#394]
热更方法：
public void Test(){
    RenderTexture rt = RenderTexture.GetTemporary(Screen.width, Screen.height);
    IntPtr ptr = rt.GetNativeTexturePtr();
    //......do something
}
在Unity直接调用热更中的方法Test会抛出异常：（初步判断问题应该出在IntPtr）
NotImplementedException: The method or operation is not implemented.
ILRuntime.Runtime.Intepreter.ILIntepreter.UnboxObject (ILRuntime.Runtime.Stack.StackObject* esp, System.Object obj, System.Collections.Generic.IList`1[T] mStack, ILRuntime.Runtime.Enviorment.AppDomain domain) (at <90527e1455c04cd78bc6e24e081cffd6>:0)
ILRuntime.Runtime.Intepreter.ILIntepreter.PushObject (ILRuntime.Runtime.Stack.StackObject* esp, System.Collections.Generic.IList`1[T] mStack, System.Object obj, System.Boolean isBox) (at <90527e1455c04cd78bc6e24e081cffd6>:0)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <90527e1455c04cd78bc6e24e081cffd6>:0)
Rethrow as ILRuntimeException: The method or operation is not implemented.

**Comment by liiir1985** [comment]
不支持Inptr等需要严格要求内存布局和直接访问内存和操作系统的用法
