### ISSUE TITLE
返回在函数创建的一个泛型变量， 该变量会有问题

### ISSUE THREAD

**Issue by liuxinjia** [Ourpalm/ILRuntime#400]
创建变量：

    public class Creater<T>
    {
        public bool Test(T me, T other)
        {
            var idiot1 = me as Man;

            var idiot2 = other as Man;
            return idiot1.Test(idiot2);
        }
    }
    
在另一个函数使用这个变量会出错，例如：

        public void Test<T>(Creater<T> creater) where T : Man
        {
            var m1 = new Man(33);
            var m2 = new Man(33);

            T t1 = (T)m1;
            T t2 = (T)m2;

            //传入创建的create有问题
            if (creater.Test(t1, t2))  // Exception NullReference
                UnityEngine.Debug.Log(true);
            else
                UnityEngine.Debug.Log(false);
        }

😁

**Comment by liuxinjia** [comment]
附上报错位置：
![image](https://user-images.githubusercontent.com/24849085/98092353-87280380-1ec1-11eb-9b39-fdc546ba11d5.png)

**Comment by liiir1985** [comment]
测试用例不完整，无法重现问题

**Comment by liuxinjia** [comment]
// 测试用例
    public void Start()
    {
        var creater = TestCreate<Man>();
        Test(creater);
    }

**Comment by liuxinjia** [comment]
附上完整的测试用例：

```
public class TestILRunTime
{
    public class Creater<T>
    {
        public bool Test(T me, T other)
        {
            var idiot1 = me as Man;

            var idiot2 = other as Man;
            return idiot1.Test(idiot2);
        }
    }

    public class Man
    {
        int a;

        public Man(int a)
        {
            this.a = a;
        }

        public bool Test(Man other) => a == other.a;
    }

    public void Test<T>(Creater<T> creater) where T : Man
    {
        var m1 = new Man(33);
        var m2 = new Man(33);

        T t1 = (T)m1;
        T t2 = (T)m2;

        //传入创建的create有问题
        if (creater.Test(t1, t2))  // Exception NullReference
            UnityEngine.Debug.Log(true);
        else
            UnityEngine.Debug.Log(false);
    }

    public Creater<T> TestCreate<T>() => new Creater<T>();

    // 测试用例
    public void Start()
    {
        var creater = TestCreate<Man>();
        Test(creater);
    }

}
```
