### ISSUE TITLE
对象实例化后泛型变量typeof类型不正确

### ISSUE THREAD

**Issue by qn9663** [Ourpalm/ILRuntime#410]
类型失败,导致反射反序列出错.
```
enum MyEnum
{
 ea,
eb,
}
class a
{
  List<MyEnum> list = new List<MyEnum>();
}
```

object instance = Activator.CreateInstance(typeof(a));
instance .list is List<int>,

**Comment by liiir1985** [comment]
热更中的枚举对于系统来说就是int，因此你这里创建出来的是List<int> 这是设计如此 ，序列化库需要自行修改，可以看反射相关文档和例子
