### ISSUE TITLE
获取变量自定义属性Attribute不正确

### ISSUE THREAD

**Issue by qn9663** [Ourpalm/ILRuntime#414]
![(4%%R(@U~ACJ39(F(_SJVTN](https://user-images.githubusercontent.com/12034663/99863235-21818a00-2bd8-11eb-8f8a-2037c07c7cd5.png)
两个不同属性,明明不相等,还进来了
```
public override object[] GetCustomAttributes(Type attributeType, bool inherit)
        {
            if (customAttributes == null)
                InitializeCustomAttribute();

            List<object> res = new List<object>();
            for (int i = 0; i < customAttributes.Length; i++)
            {
                if (attributeTypes[i].Equals(attributeType))
                {
                    res.Add(customAttributes[i]);--<
                }
            }
            return res.ToArray();
        }
```

**Comment by qn9663** [comment]
public static object GetCustomAttributeILR(this ILRuntime.Reflection.ILRuntimeFieldInfo fieldInfo,Type t,bool inherit)
    {
        var array = fieldInfo.GetCustomAttributes(inherit);
        for (int i = 0; i < array.Length; i++)
        {
            var tt = array[i].GetType();
            if (tt.Equals(t))
            {
                return array[i];
            }
        }
        return null;
    }
自己加了一个函数是可以的,因为都是hot层的类对象.所以hot层加的.

**Comment by liiir1985** [comment]
需要提供测试用例
