### ISSUE TITLE
async方法会直接跳过“无”await的分支

### ISSUE THREAD

**Issue by RaymondKing123** [Ourpalm/ILRuntime#417]
`
namespace HotFix_Project
{
	class TestAsyncAwait
	{
        public static async void Start()
        {
            int i = await Test(0);
            Debug.Log(i); // 输出0

            i = await Test(1);
            Debug.Log(i); // 不输出，程序直接跑飞，但是也不报异常
        }

        public static async Task<int> Test(int i)
        {
            if (i > 0)
            {
                // 注意：这个分支没有await
                return 1;
            }
            else
            {
                await Task.Delay(1);
                return 0;
            }
        }
    }
}
`

**Comment by RaymondKing123** [comment]
@liiir1985  重新整理一下代码格式，请蓝大帮忙看下呢，是我写法有问题还是async/await的支持问题，谢谢：
```csharp
namespace HotFix_Project
{
    class TestAsyncAwait
    {
        public static async void Start()
        {
            int i = await Test(0);
            Debug.Log(i); // 输出0

            i = await Test(1);
            Debug.Log(i); // 不输出，程序直接跑飞，但是也不报异常
        }

        public static async Task<int> Test(int i)
        {
            if (i > 0)
            {
                // 注意：这个分支没有await
                return 1;
            }
            else
            {
                await Task.Delay(1);
                return 0;
            }
        }
    }
}
```

**Comment by liiir1985** [comment]
使用的ilruntime是哪个版本？

**Comment by RaymondKing123** [comment]
> 使用的ilruntime是哪个版本？

最新版：1.6.5，
系统环境是：Win10，Unity2019.4

**Comment by xiezi5160** [comment]
请问，这个问解决了吗？

**Comment by xiezi5160** [comment]
> 使用的ilruntime是哪个版本？

请问 这个问题修复了吗？

**Comment by liiir1985** [comment]
在最新master中修复一个Async的问题，重新生成CLR绑定后试一下是否已修复
