### ISSUE TITLE
IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by fujisheng** [Ourpalm/ILRuntime#423]
![QQ截图20201202151316](https://user-images.githubusercontent.com/24699142/100840915-829b3e80-34b1-11eb-984b-616ace3e528a.png)
![QQ截图20201202151336](https://user-images.githubusercontent.com/24699142/100840931-875ff280-34b1-11eb-8f35-cf72f5f1a899.png)
这种情况下会报错  其原因是给value 赋值了 default

**Comment by liiir1985** [comment]
使用当前最新master版已无法重现，可以更新一下试试
