### ISSUE TITLE
这种写法unity下是好的，Ios真机上就会出错，导致Instance实例不出来，求解答

### ISSUE THREAD

**Issue by surpassSelf** [Ourpalm/ILRuntime#425]
public class ILCSGiantsHegemonySchedule
{
    public static ILCSGiantsHegemonySchedule Instance = new ILCSGiantsHegemonySchedule();
    private Dictionary<GiantsHegemonySchedule, long> ScheduleDic = new Dictionary<GiantsHegemonySchedule, long>();
}

**Comment by liiir1985** [comment]
如果编辑器下没问题真机出问题，那一定是相关方法或者类型被 il2cpp剪裁掉了，每次出包前都必须做clr自动分析绑定已确保用到的都正确保留了，具体请看文档
