### ISSUE TITLE
热更项目方法无法使用UnityEvent<T>

### ISSUE THREAD

**Issue by so-sos-so** [Ourpalm/ILRuntime#428]
> 报错代码

       public void Start()
        {
            Toggle toggle = Object.FindObjectOfType<Toggle>();
            Debug.Log(toggle);
            AA(TBB, toggle.onValueChanged);
        }
        
        public void AA<T>(Action<T> t1, UnityEvent<T> aa)
        {
            
        }

        private void TBB(bool b)
        {
            
        }

> 报错堆栈

NullReferenceException: Object reference not set to an instance of an object
ILRuntime.CLR.TypeSystem.ILType.CheckGenericParams (ILRuntime.CLR.Method.ILMethod i, System.Collections.Generic.List`1[T] param, System.Boolean& match) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.5/CLR/TypeSystem/ILType.cs:854)
ILRuntime.CLR.TypeSystem.ILType.GetMethod (System.String name, System.Collections.Generic.List`1[T] param, ILRuntime.CLR.TypeSystem.IType[] genericArguments, ILRuntime.CLR.TypeSystem.IType returnType, System.Boolean declaredOnly) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.5/CLR/TypeSystem/ILType.cs:769

**Comment by liiir1985** [comment]
使用最新master版试试， 修正了几个泛型匹配的问题
