### ISSUE TITLE
 InvalidCastException Unable to cast object of type 'List`1' to type 'Dictionary`2'.

### ISSUE THREAD

**Issue by FengYunHuanYu** [Ourpalm/ILRuntime#437]
非必现。

ILRuntime.Runtime.Generated.System_Collections_Generic_Dictionary_2_Int32_ILTypeInstance_Binding.get_Item_4 (ILRuntime.Runtime.Intepreter.ILIntepreter __intp, ILRuntime.Runtime.Stack.StackObject* __esp, System.Collections.Generic.IList`1[T] __mStack, ILRuntime.CLR.Method.CLRMethod __method, System.Boolean isNewObj) (at <00000000000000000000000000000000>.0)
--
1 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
2 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
3 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
4 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
5 ILRuntime.Runtime.Intepreter.ILIntepreter.Run (ILRuntime.CLR.Method.ILMethod method, System.Object instance, System.Object[] p) (at <00000000000000000000000000000000>.0)
6 ILRuntime.Runtime.Enviorment.AppDomain.Invoke (ILRuntime.CLR.Method.IMethod m, System.Object instance, System.Object[] p) (at <00000000000000000000000000000000>.0)
7 ILRuntime.Runtime.Generated.System_Action_Binding.Invoke_0 (ILRuntime.Runtime.Intepreter.ILIntepreter __intp, ILRuntime.Runtime.Stack.StackObject* __esp, System.Collections.Generic.IList`1[T] __mStack, ILRuntime.CLR.Method.CLRMethod __method, System.Boolean isNewObj) (at <00000000000000000000000000000000>.0)
8 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
9 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
10 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
11 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
12 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
13 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
14 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
15 ILRuntime.Runtime.Intepreter.ILIntepreter.Run (ILRuntime.CLR.Method.ILMethod method, System.Object instance, System.Object[] p) (at <00000000000000000000000000000000>.0)
16 ILRuntime.Runtime.Enviorment.AppDomain.Invoke (ILRuntime.CLR.Method.IMethod m, System.Object instance, System.Object[] p) (at <00000000000000000000000000000000>.0)
17 Rethrow as ILRuntimeException. Unable to cast object of type 'List`1' to type 'Dictionary`2'.
18 Shark.DataInstance`1<Shark.Tab_DestinyBaseLevelUp>.GetDataById(Int32 id)
19 DestinyUI_NatalChart.IsMeetCondition(Int32 id)
20 DestinyUI_NatalChart.IsMeetCondition()
21 MiniMapLogic.UpdateDestinyRedPoint()
22 Rethrow as ILRuntimeException. Unable to cast object of type 'List`1' to type 'Dictionary`2'.
23 Shark.DataInstance`1<Shark.Tab_DestinyBaseLevelUp>.GetDataById(Int32 id)
24 DestinyUI_NatalChart.IsMeetCondition(Int32 id)
25 DestinyUI_NatalChart.IsMeetCondition()
26 MiniMapLogic.UpdateDestinyRedPoint()

在我们的表格加载文件中报错，不是必现，比较小的概率，应该是GetDataById中把mData当做了List类型，实际是Dictionary。
栈乱了？代码如下：
public class DataInstance<T> where T : IDataUnit, new()
    {
        public static DataInstance<T> Instance = new DataInstance<T>();
        private Dictionary<int, T> mData = new Dictionary<int, T>();
        public List<T> ListData = new List<T>();
        public void Load(string dataTable)
        {
            if(DataProvider.Instance.IsOnlineLoad)
            {
                Dictionary<int, T> mTmp = new Dictionary<int, T>();
                Load(dataTable,mTmp);
                mData = mTmp;
            }
            else
            {
                mData.Clear();
                Load(dataTable, mData);
            }
            ListData.Clear();
            Dictionary<int, T>.ValueCollection lst = mData.Values;
            ListData.AddRange(lst);
        }
        public void Load(string dataTable,Dictionary<int,T> dicContainer)
        {
            string[] rows = dataTable.Split('\n');
            int len = rows.Length;
            int nCurId = -1;
            for (int i = 0; i < len; i++)
            {
                if (rows[i].StartsWith("#")||rows[i].Equals(""))
                {
                    continue;
                }

                T unit = new T();
                unit.Load(rows[i]);
                int id = unit.GetId();
                if (id != -1)
                {
                    if (dicContainer.ContainsKey(id))
                    {
                        Console.ForegroundColor = ConsoleColor.Red;
                        Console.WriteLine("ID重复了   "+GetType().ToString() + " , id : " + id);
                        Console.ForegroundColor = ConsoleColor.White;
                    }
                    else
                    {
                        dicContainer.Add(id, unit);
                    }           

                }
            }
        }
        public T GetDataById(int id)
        {
            if (mData.ContainsKey(id))
                return mData[id];
            return default(T);
        }
        public Dictionary<int, T> GetData()
        {
            return mData;
        }
    }

另外，在Load函数中，ListData.AddRange(lst);一行也有小概率报错，错误堆栈如下：

0 ILRuntime.Runtime.Generated.System_Collections_Generic_List_1_ILTypeInstance_Binding.Clear_6 (ILRuntime.Runtime.Intepreter.ILIntepreter __intp, ILRuntime.Runtime.Stack.StackObject* __esp, System.Collections.Generic.IList`1[T] __mStack, ILRuntime.CLR.Method.CLRMethod __method, System.Boolean isNewObj) (at <00000000000000000000000000000000>.0)
--
1 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
2 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
3 ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at <00000000000000000000000000000000>.0)
4 ILRuntime.Runtime.Intepreter.ILIntepreter.Run (ILRuntime.CLR.Method.ILMethod method, System.Object instance, System.Object[] p) (at <00000000000000000000000000000000>.0)
5 ILRuntime.Runtime.Enviorment.AppDomain.Invoke (ILRuntime.CLR.Method.IMethod m, System.Object instance, System.Object[] p) (at <00000000000000000000000000000000>.0)
6 CoroutineAdapter+Adaptor.MoveNext () (at <00000000000000000000000000000000>.0)
7 UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>.0)
8 Rethrow as ILRuntimeException. Unable to cast object of type 'Dictionary`2' to type 'List`1'.
9 Shark.DataInstance`1<Shark.Tab_HuanLeXunBao>.Load(String dataTable)
10 Shark.DataProvider.LoadData(DataInstance`1 container, String relativePath)
11 Shark.DataProvider/<LoadAllClientData>d__1.MoveNext()

**Comment by liiir1985** [comment]
ILRuntime版本？

**Comment by yingbohui** [comment]
请问解决了吗
