### ISSUE TITLE
仅自动分析绑定，之后热更新中用到新的主工程类怎么办？

### ISSUE THREAD

**Issue by Jinngoo** [Ourpalm/ILRuntime#443]
“常见问题解答”中几次提到“请一定要注意是自动分析，而不是手动给type列表进行绑定”，那么当想要在某次热更版本中使用新的主工程类型时，新生成的CLR绑定无法应用于旧版客户端，那自动分析岂不是鸡肋了？有没有方法可以事先生成所有可以预见的CLR绑定？
另外，值类型绑定，没找到像自动分析那样的自动生成接口，要一个一个手写么？[害怕]

**Comment by liiir1985** [comment]
正常来说，项目上线的时候，该用的原生接口都已经全部用过一遍了，本身用到之前没有用到过的接口概率就很小，从我们过往项目经历来说，即便是遇到了，也一定能找到一个用过的方法绕过去，因此并不会构成问题。实在不放心可以使用unity的link.xml写规则多保留一些类型
