### ISSUE TITLE
uint转double值异常

### ISSUE THREAD

**Issue by NeoExplore** [Ourpalm/ILRuntime#444]
测试代码：
`uint u1 = 1607900000;
 uint u2 = 1609000000;
 double d1 = u1;
 double d2 = u2;

 Debug.Log($"{d1} {d2}");`
以下是输出结果：
1607900032 1608999936

经过粗略的测试，稍微小一点的数值，比如160790000不会有此问题；使用System.Convert.ToDouble进行转换的话也不会有问题

**Comment by liiir1985** [comment]
在标准C#环境中测试没有问题，应该是c#编译器较老导致转换时先转到float再转到double了

**Comment by NeoExplore** [comment]
> 在标准C#环境中测试没有问题，应该是c#编译器较老导致转换时先转到float再转到double了
较老的编译器版本？我测试的编译器版本是10.0.10011.16384，.NET Framework版本是4.7.1。
请问您说的“标准C#环境”是指什么环境？目前我的情况是，上述代码在CLR里面直接执行是正常的，但是在ILRuntime里面解释执行就会出现该问题

**Comment by NeoExplore** [comment]
> 在标准C#环境中测试没有问题，应该是c#编译器较老导致转换时先转到float再转到double了

较老的编译器版本？我测试的编译器版本是10.0.10011.16384，.NET Framework版本是4.7.1。
请问您说的“标准C#环境”是指什么环境？目前我的情况是，上述代码在CLR里面直接执行是正常的，但是在ILRuntime里面解释执行就会出现该问题
