### ISSUE TITLE
热更下使用协程发现WaitForSeconds失效

### ISSUE THREAD

**Issue by mister91jiao** [Ourpalm/ILRuntime#445]
在已经实现System.IDisposable，System.Collections.IEnumerator，System.Collections.Generic.IEnumerator<object>，这三个接口的适配器的情况下，使用非热更层一个继承MonoBehaviour的单例类去开启热更层的协程导致WaitForSeconds失效，具体表现为无论填多少秒都不会等待会直接执行后面的代码。

![~4V5119{{$TD)3I_@J}7BZ2](https://user-images.githubusercontent.com/47842835/103612783-2455f580-4f60-11eb-9fb0-11c672fdb35b.png)

![7K4ZO@F_I2@FXXS$KEN23XD](https://user-images.githubusercontent.com/47842835/103612798-2e77f400-4f60-11eb-8493-1818636256aa.png)

**Comment by mister91jiao** [comment]
ILRuntime版本1.6.6
Unity版本2019.4

**Comment by liiir1985** [comment]
请从package中导入Sample例程，有协程的示例，也有waitforseconds
