### ISSUE TITLE
1.6.6 热更工程 调用主工程 静态属性，会报查找不到方法

### ISSUE THREAD

**Issue by 827922094** [Ourpalm/ILRuntime#446]
![image](https://user-images.githubusercontent.com/31557380/103625649-3b9fdd80-4f76-11eb-9e54-c3ed582986c6.png)
![image](https://user-images.githubusercontent.com/31557380/103625691-48243600-4f76-11eb-937d-59b4f7d0a1af.png)
![image](https://user-images.githubusercontent.com/31557380/103626346-0647bf80-4f77-11eb-898a-96a1f83bfa97.png)
生成CLR绑定的时候就会报

**Comment by liiir1985** [comment]
master版本无法重现， 你这consts是不是放到什么特殊目录里导致不在一个程序集了，比如plugins
