### ISSUE TITLE
热更dll反射里带参数无法实例化

### ISSUE THREAD

**Issue by yuxiangyan** [Ourpalm/ILRuntime#456]
代码如下
mediator =Activator.CreateInstance(t2, new object[2] { key, win  }) as T;

mediator类的含有两个参数的构造器没有被调用。构造方法如下，参数都是基本类型
 public Mediator(string name,object view)
        {

        }

**Comment by liiir1985** [comment]
这段代码是写在热更还是主工程的？ 写在热更里在最新master版上测试并无问题
