### ISSUE TITLE
进行CLRbinding之后获取值类型存储数值会报出空引用错误

### ISSUE THREAD

**Issue by paidax79** [Ourpalm/ILRuntime#466]
代码截图：
![image](https://user-images.githubusercontent.com/60389207/109771740-24106880-7c38-11eb-887f-6021ccfec8a5.png)
错误截图：
![image](https://user-images.githubusercontent.com/60389207/109771797-34284800-7c38-11eb-81e1-f906644601fa.png)
如果不进行CLRbinding则表现为正常，调试插件在上述两种情况中都无法获取该值。

**Comment by liiir1985** [comment]
使用的ILRuntime是什么版本呢

**Comment by paidax79** [comment]
之前使用ILruntime1.6.5时存在该问题，后续升级到1.6.6，该问题依旧存在

**Comment by liiir1985** [comment]
对Vector3进行了值类型绑定吗？值类型绑定的注册时机是否在CLR绑定之前

**Comment by paidax79** [comment]
进行了值类型绑定，使用的是ILRuntimeDemo工程中的Vector3Binder,注册时机在进行CLRbinding之前，但是在各种Adapter绑定之后

**Comment by liiir1985** [comment]
我在1.6.6的ILRuntimeDemo里使用你提供的哪行代码并不能重现问题啊
