### ISSUE TITLE
同一个方法,多次await带有返回值的的泛型异步方法，会报aot错误(已自动CLR绑定)

### ISSUE THREAD

**Issue by StoneXM** [Ourpalm/ILRuntime#478]
//**问题发生在 LoadBranchInt,如果一个方法里有多次await带有返回值的泛型方法，会报错：**
Error Unity ExecutionEngineException: Attempting to call method 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]::Start<IAsyncStateMachineClassInheritanceAdaptor+IAsyncStateMachineAdaptor>' for which no ahead of time (AOT) code was generated. 
//await一次不会有问题，之前是只要嵌套和分支就有问题，最近的一次更新之后一个方法里有多次await带有返回值的泛型方法，就会报上面的错误。

//测试代码
public static async Task TestAwait()
        {
var test = await LoadBranchInt<int>(7);
            Logger.Info("ILRuntime Test complete!" + test);
}

public static async Task<int> LoadBranchInt<T>(int test) 
        {
            var tempVar = await LoadBranchInt1<T>(test);
            return await LoadBranchInt2<T>(test);
        }
        
        public static async Task<int> LoadBranchInt1<T>(int test) 
        {
            return test;
        }
        
        public static async Task<int> LoadBranchInt2<T>(int test)
        {
            await Task.Delay(1);
            return 4;
        }

**Comment by StoneXM** [comment]
经过多次测试，排除了其它原因，只要是泛型，就会报具体的使用类型的aot错误。

**Comment by StoneXM** [comment]
这个问题经过几天的反复测试了，嵌套和分支确实没问题了，确实是因为泛型引发的问题只能暂时把所有的泛型接口改为参数传type进去，但是还是会有很多不方便。希望蓝大能帮忙查看一下这块的问题。

**Comment by liiir1985** [comment]
AsyncTaskMethodBuilder<int>.Start<IAsyncStateMachineClassInheritanceAdaptor+IAsyncStateMachineAdaptor>()
你看一下你那边这个方法的CLR绑定方法是否已经生成？ 如果已经生成的话，对应的绑定代码是否已经注册，如果都有的话，那在主工程手动调用一下这个方法试试看是否能解决问题？

**Comment by StoneXM** [comment]
> AsyncTaskMethodBuilder.Start<IAsyncStateMachineClassInheritanceAdaptor+IAsyncStateMachineAdaptor>()
> 你看一下你那边这个方法的CLR绑定方法是否已经生成？ 如果已经生成的话，对应的绑定代码是否已经注册，如果都有的话，那在主工程手动调用一下这个方法试试看是否能解决问题？

都有生成也注册了，还是报一样的错。

**Comment by weacw** [comment]
同样问题，多次打包有时候会报出AOT有时候又能正常使用

**Comment by liiir1985** [comment]
应该已经修复CLR绑定生成代码了
