### ISSUE TITLE
vs2019编译hotfix后，使用ETTask，await等待不生效，但是使用Task，await等待是可以的

### ISSUE THREAD

**Issue by zhoujin1125** [Ourpalm/ILRuntime#481]
static async ETTask Test()
        {

            Log.Error("test   ||||||||||||        begain");
            TimerComponent timerComponent = ETModel.Game.Scene.GetComponent<TimerComponent>();
            await timerComponent.WaitAsync(1000);
            Log.Error("test   ||||||||||||        end");
        }
static async Task Test2()
        {

            Log.Error("test   ||||||||||||        begain");
            TimerComponent timerComponent = ETModel.Game.Scene.GetComponent<TimerComponent>();
            await timerComponent.WaitAsync(1000);
            Log.Error("test   ||||||||||||        end");
        }

**Comment by liiir1985** [comment]
使用的是哪个unity版本？ 有试过使用master最新版吗？

**Comment by zhoujin1125** [comment]
unity2018.4.14      试过ilruntime master最新版，也是不行的

**Comment by liiir1985** [comment]
用其他编译器编译hotfix会有这个问题吗？ ET相关的我这边没法测试，但是我们有使用跟ETTask类似的东西，并没有产生问题

**Comment by LiuOcean** [comment]
> static async ETTask Test()
> {
> 
> ```
>         Log.Error("test   ||||||||||||        begain");
>         TimerComponent timerComponent = ETModel.Game.Scene.GetComponent<TimerComponent>();
>         await timerComponent.WaitAsync(1000);
>         Log.Error("test   ||||||||||||        end");
>     }
> ```
> 
> static async Task Test2()
> {
> 
> ```
>         Log.Error("test   ||||||||||||        begain");
>         TimerComponent timerComponent = ETModel.Game.Scene.GetComponent<TimerComponent>();
>         await timerComponent.WaitAsync(1000);
>         Log.Error("test   ||||||||||||        end");
>     }
> ```

我之前碰到过这个问题， 你可以检查一下Mono 的版本， 我当时出现问题的Mono 版本是 6.12，使用 6.0 编译出来的 dll 是没有问题的。

**Comment by zhoujin1125** [comment]
> > static async ETTask Test()
> > {
> > ```
> >         Log.Error("test   ||||||||||||        begain");
> >         TimerComponent timerComponent = ETModel.Game.Scene.GetComponent<TimerComponent>();
> >         await timerComponent.WaitAsync(1000);
> >         Log.Error("test   ||||||||||||        end");
> >     }
> > ```
> > 
> > 
> > static async Task Test2()
> > {
> > ```
> >         Log.Error("test   ||||||||||||        begain");
> >         TimerComponent timerComponent = ETModel.Game.Scene.GetComponent<TimerComponent>();
> >         await timerComponent.WaitAsync(1000);
> >         Log.Error("test   ||||||||||||        end");
> >     }
> > ```
> 
> 我之前碰到过这个问题， 你可以检查一下Mono 的版本， 我当时出现问题的Mono 版本是 6.12，使用 6.0 编译出来的 dll 是没有问题的。

cs编译不是用的.net吗，那这个Mono版本是在哪里改的？

**Comment by liiir1985** [comment]
可以尝试使用最新版ILRuntime，并重新生成和注册CLR绑定再运行试试
