### ISSUE TITLE
Task无法使用

### ISSUE THREAD

**Issue by guoweidong1987** [Ourpalm/ILRuntime#483]
使用Testcase中的例子，实现了适配器，其中1，2打印了，3，4没有输出出来，是用法有什么问题么？
![image](https://user-images.githubusercontent.com/6338674/113236620-ca06cf80-92d7-11eb-8551-6185beb17cd3.png)

**Comment by guoweidong1987** [comment]
更新：清理工程后，Task.Delay方法可以执行了，但是参数为 0，1，2，3时可以执行下去，大于3以上的参数都不行
![image](https://user-images.githubusercontent.com/6338674/113697189-73e5c200-9705-11eb-906a-77fb3466f3d5.png)
![image](https://user-images.githubusercontent.com/6338674/113697275-8f50cd00-9705-11eb-92d3-dff1c5571fc8.png)

**Comment by liiir1985** [comment]
Master版中无法重现
