### ISSUE TITLE
更新到1.6.6和1.6.7后，生成CLR Binding时，报异常TypeLoadException: Failure has occurred while loading a type.

### ISSUE THREAD

**Issue by FallDC** [Ourpalm/ILRuntime#484]
打印日志，是在CLRMethod的InitParameters方法里。
if (type == null)
{
    UnityEngine.Debug.LogError("---------------------- " + i.ParameterType.FullName);
    throw new TypeLoadException();
}

输出日志：
---------------------- System.UInt32[][]&

查找代码后，是这个方法：
public static bool GetEventInfo(int eventType, out uint[][] conds)
{
    return _eventInfo.TryGetValue(eventType, out conds);
}

**Comment by liiir1985** [comment]
使用最新master版并未发现异常

**Comment by xiezhizhao** [comment]
Failure has occurred while loading a type.
最新master 线上跑也出现这个异常（异常日志也不是很多），随机出现。平时跑没问题

throw new TypeLoadException();
有点线索似乎是泛型方法的问题。或者Type.GetType没捞到主域类型， 没有头绪。
是不是可以在TypeLoadException里加点上下文

@liiir1985
