### ISSUE TITLE
在使用DOTween.To<>出现异常

### ISSUE THREAD

**Issue by oOtroyOo** [Ourpalm/ILRuntime#486]
![屏幕截图 2021-04-15 112434](https://user-images.githubusercontent.com/19978148/114810194-2260c580-9dde-11eb-80d1-7e6897edb9bc.png)

![屏幕截图 2021-04-15 110718](https://user-images.githubusercontent.com/19978148/114810189-212f9880-9dde-11eb-8a77-9202a34cc96a.png)

![屏幕截图 2021-04-15 111928](https://user-images.githubusercontent.com/19978148/114810198-22f95c00-9dde-11eb-8a72-90ca73888b14.png)

我想实现弹道轨迹的进度变化。（具体还没写完）
使用基础的DOTween.To<float, float, FloatOptions>对float值变化。
然后出现以下两个报错

猜测是没有识别出FloatPlugin这个参数。我也没带null啊。

**Comment by vsheyan** [comment]
和楼上一样同问

**Comment by vsheyan** [comment]
+1

**Comment by vsheyan** [comment]
看了下dotween 的源码   
DOScale这种就可以顺利运行
进去看了下这么写的

**DOTween.To(() => target.effectDistance, x => target.effectDistance = x, endValue, duration);**

这种形式就没事
你可以把你的也改写成这样的试试

**Comment by liiir1985** [comment]
> ![屏幕截图 2021-04-15 112434](https://user-images.githubusercontent.com/19978148/114810194-2260c580-9dde-11eb-80d1-7e6897edb9bc.png)
> 
> ![屏幕截图 2021-04-15 110718](https://user-images.githubusercontent.com/19978148/114810189-212f9880-9dde-11eb-8a77-9202a34cc96a.png)
> 
> ![屏幕截图 2021-04-15 111928](https://user-images.githubusercontent.com/19978148/114810198-22f95c00-9dde-11eb-8a72-90ca73888b14.png)
> 
> 我想实现弹道轨迹的进度变化。（具体还没写完）
> 使用基础的DOTween.To<float, float, FloatOptions>对float值变化。
> 然后出现以下两个报错
> 
> 猜测是没有识别出FloatPlugin这个参数。我也没带null啊。

解析方法参数时，FloatPlugin解析失败，FloatPlugin的定义是啥样，DoTween.To的定义又是啥样
