### ISSUE TITLE
AsyncTaskMethodBuilder相关的绑定代码生成有问题

### ISSUE THREAD

**Issue by niu-shuang** [Ourpalm/ILRuntime#487]
使用UniTask最新版，为了降低Value Task的Allocation，UniTask自己实现了AsyncUniTaskMethodBuilder。

使用扫描生成绑定代码的话会生成AsyncUniTaskMethodBuilder<value类型>的绑定代码。运行时表现为 await xxxTask 后会立即返回default value。注释掉绑定代码的注册之后运行正常。

建立了一个单独的工程来展示问题：https://github.com/niu-shuang/ILRuntimeTest

**Comment by liiir1985** [comment]
CLR代码生成中添加AsyncUniTaskMethodBuilder支持

**Comment by boooooommmmmm** [comment]
遇到了相同的问题，UniTask直接返回。老哥这个问题解决了吗，可以分享一下吗？
