### ISSUE TITLE
升级1.6.7之后Task<T> 使用await会中断的bug

### ISSUE THREAD

**Issue by redforesss** [Ourpalm/ILRuntime#488]
升级1.6.7之后Task<T> 在发布Release会中断，发布Debug能正常执行。在旧版本1.6.6时候Release也正常。

```
using System.Threading.Tasks;
using UnityEngine;

public class TestNest
{

    public static void Run()
    {
        Test1();
    }
 
    public static async void Test1()
    {
        Debug.Log("Start-------------Test1");
        var result = await GetCommon<int>("");
        Debug.Log("End---------------Test1");
    }
    
    public static async Task<T> GetCommon<T>(string path) where T : new()
    {
        Debug.Log("3333333333333333333333333333");
        await Task.Delay(100);
        Debug.Log("44444444444444444444");

        T result = new T();
        return result;
    }   
}
```

代码已生成绑定，发布Debug能顺利输出， 发布Release却不能输出 44444444444444444444

**Comment by poetao** [comment]
![image](https://user-images.githubusercontent.com/7285985/116374831-3e824f00-a841-11eb-8cdc-fa28e33d9387.png)
把303行注掉的这两行代码放开就行了。
因为Debug下 async/await 扩展生成的状态机方法是class类型的，而Release下是ValueType类型的，这里注掉了，Release下就不能正确生成instance, 所以断了

**Comment by liiir1985** [comment]
> ![image](https://user-images.githubusercontent.com/7285985/116374831-3e824f00-a841-11eb-8cdc-fa28e33d9387.png)
> 把303行注掉的这两行代码放开就行了。
> 因为Debug下 async/await 扩展生成的状态机方法是class类型的，而Release下是ValueType类型的，这里注掉了，Release下就不能正确生成instance, 所以断了

如果生成了绑定不应该走到这里面来

**Comment by redforesss** [comment]
303行注掉不管用，release结果还是一样，绑定代码是肯定的

**Comment by redforesss** [comment]
确实放开后realease就ok了

![image](https://user-images.githubusercontent.com/33017308/116500815-ee0efe00-a8e1-11eb-9b83-4e262aab1650.png)



代码绑定是肯定的
![image](https://user-images.githubusercontent.com/33017308/116500730-bacc6f00-a8e1-11eb-91b2-3d5a82655f32.png)
![image](https://user-images.githubusercontent.com/33017308/116500884-126ada80-a8e2-11eb-8157-ea60f99841c0.png)

**Comment by liiir1985** [comment]
你是不是没注册绑定，因为如果走了绑定就不应该走到你解开注释的那里

**Comment by liiir1985** [comment]
我在测试工程中测试并没有问题

**Comment by redforesss** [comment]
@liiir1985

我在测试工程里面并不行，Release还是一样，就是简单改了HelloWorld的例子测试

![image](https://user-images.githubusercontent.com/33017308/117436107-2c9b5d00-af61-11eb-9668-1d41b3aa2737.png)

**Comment by liiir1985** [comment]
那你试试最新的2.0的preview版的demo？ 已经把通过反射调用await的地方修正了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年5月7日 18:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Ourpalm/ILRuntime] 升级1.6.7之后Task<T> 使用await会中断的bug (#488)


@liiir1985<https://github.com/liiir1985>

我在测试工程里面并不行，Release还是一样，就是简单改了HelloWorld的例子测试

[image]<https://user-images.githubusercontent.com/33017308/117436107-2c9b5d00-af61-11eb-9668-1d41b3aa2737.png>

―
