### ISSUE TITLE
程序运行到Marshal.SizeOf(type); unity2019.4.14会直接崩溃

### ISSUE THREAD

**Issue by yicong1406410220** [Ourpalm/ILRuntime#493]
程序运行到Marshal.SizeOf(type); unity2019.4.14会直接崩溃 ilruntime1.6.6

using System.Runtime.InteropServices;

    [StructLayoutAttribute(LayoutKind.Sequential, CharSet = CharSet.Unicode, Pack = 1)]
    public class CMD_MB_LogonOtherPlatform
    {
        //系统信息
        public ushort wModuleID;                         //模块标识
        public UInt32 dwPlazaVersion;                   //广场版本
        public byte cbDeviceType;                       //设备类型

        //登录信息
        public byte cbGender;                          //用户性别
        public byte cbPlatformID;                      //平台编号

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = LEN_DEF.LEN_USER_UIN)]
        public string szUserUin;                       //用户Uin

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = LEN_DEF.LEN_NICKNAME)]
        public string szNickName;                      //用户昵称

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = LEN_DEF.LEN_COMPELLATION)]
        public string szCompellation;                   //真实名字

        //连接信息
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = LEN_DEF.LEN_MACHINE_ID)]
        public string szMachineID;                      //机器标识
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = LEN_DEF.LEN_MOBILE_PHONE)]
        public string szMobilePhone;                    //电话号码

        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = LEN_DEF.LEN_HEAD_URL)]
        public string szHeadUrl;                    //头像URL

        public long longitude;
        public long latitude;
        public byte isSimulator;            // 0 正常  1 模拟
        public byte networkType;            // 0 wifi  1 4G  2 未知    
        public byte batteryLevel;           //电量  
        public byte[] Pack()
        {
            Type type = GetType();
            Log.Debug(type.ToString());
            int length = Marshal.SizeOf(type);
            byte[] buffer;// = new byte[length];

            MemoryStream stream = new MemoryStream();
            NetUtil.PushValue(ref stream, wModuleID);
            NetUtil.PushValue(ref stream, dwPlazaVersion);
            NetUtil.PushValue(ref stream, cbDeviceType);
            NetUtil.PushValue(ref stream, cbGender);
            NetUtil.PushValue(ref stream, cbPlatformID);
            NetUtil.PushValue(ref stream, szUserUin, LEN_DEF.LEN_USER_UIN);
            NetUtil.PushValue(ref stream, szNickName, LEN_DEF.LEN_NICKNAME);
            NetUtil.PushValue(ref stream, szCompellation, LEN_DEF.LEN_COMPELLATION);
            NetUtil.PushValue(ref stream, szMachineID, LEN_DEF.LEN_MACHINE_ID); ;
            NetUtil.PushValue(ref stream, szMobilePhone, LEN_DEF.LEN_MOBILE_PHONE);
            NetUtil.PushValue(ref stream, szHeadUrl, LEN_DEF.LEN_HEAD_URL);
            NetUtil.PushValue(ref stream, longitude);
            NetUtil.PushValue(ref stream, latitude);
            NetUtil.PushValue(ref stream, isSimulator);
            NetUtil.PushValue(ref stream, networkType);
            NetUtil.PushValue(ref stream, batteryLevel);
            //if (length != stream.Length)
            //{
            //    Debug.LogError("pack length error: " + GetType().ToString() + "--length:" + length + "--stream:" + stream.Length);
            //    return null;
            //}
            //buffer = new byte[length];
            //stream.Seek(0, SeekOrigin.Begin);
            //stream.Read(buffer, 0, length);
            //return buffer;
            return null;
        }

    };

**Comment by liiir1985** [comment]
不支持直接跟硬件打交道的功能，例如Marshal和转指针
