### ISSUE TITLE
生成绑定代码，如果代码里有IntPtr会报错

### ISSUE THREAD

**Issue by yicong1406410220** [Ourpalm/ILRuntime#494]
生成绑定代码，如果代码里有IntPtr会报错无法生成。ilruntime1.6.6
![image](https://user-images.githubusercontent.com/20357196/116647324-d6e91280-a9ac-11eb-85d5-df35493e306e.png)
![image](https://user-images.githubusercontent.com/20357196/116647384-fda74900-a9ac-11eb-85e6-5931cc6ad7a9.png)

**Comment by liiir1985** [comment]
不支持跟硬件直接打交道的东西，比如IntPtr指针
