### ISSUE TITLE
LitJson中无法序列化基类属性的问题

### ISSUE THREAD

**Issue by yomunsam** [Ourpalm/ILRuntime#495]
# 复现方式

在**热更工程**中定义类型如下

![image](https://user-images.githubusercontent.com/24813704/116657689-6dbfca00-a9c1-11eb-81c5-d14e7159f976.png)

![image](https://user-images.githubusercontent.com/24813704/116657710-74e6d800-a9c1-11eb-8051-05728e0120ce.png)

运行后输出log如下：
![image](https://user-images.githubusercontent.com/24813704/116657805-9d6ed200-a9c1-11eb-98b7-c2d76798f94b.png)

基类中的属性没有被序列化

<br>

# 分析

经分析发现，问题在于`JsonMapper.cs`文件中，下图所示位置
![image](https://user-images.githubusercontent.com/24813704/116657938-d313bb00-a9c1-11eb-952a-e7574da58523.png)

`type.GetProperties()` 无法获取到基类的属性。

往下分析的原因是`ILRuntimeType.cs`中的`GetProperties`方法，在处理基类的时候，只对`ILRuntimeWrapperType`作了处理，而未对`ILRuntimeType`类型作处理

![image](https://user-images.githubusercontent.com/24813704/116658112-11a97580-a9c2-11eb-8700-ebafb609c0d3.png)

**Comment by liiir1985** [comment]
已Merge
