### ISSUE TITLE
NotSupportedException: Specified method is not supported.

### ISSUE THREAD

**Issue by leviyuan** [Ourpalm/ILRuntime#501]
[TestError.zip](https://github.com/Ourpalm/ILRuntime/files/6465353/TestError.zip)
任意场景直接启动即可触发报错
启动入口  Model.Launcher.Initialize

NotSupportedException: Specified method is not supported.
ILRuntime.Runtime.Stack.RuntimeStack.FreeValueTypeObject (ILRuntime.Runtime.Stack.StackObject* esp) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Stack/RuntimeStack.cs:419)
ILRuntime.Runtime.Intepreter.ILIntepreter.FreeStackValueType (ILRuntime.Runtime.Stack.StackObject* esp) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Intepreter/ILIntepreter.cs:5436)
ILRuntime.Runtime.Intepreter.ILIntepreter.Free (ILRuntime.Runtime.Stack.StackObject* esp) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Intepreter/ILIntepreter.cs:5421)
ILRuntime.Runtime.Intepreter.DelegateAdapter.ClearStack (ILRuntime.Runtime.Intepreter.ILIntepreter intp, ILRuntime.Runtime.Stack.StackObject* esp, ILRuntime.Runtime.Stack.StackObject* ebp, System.Collections.Generic.IList`1[T] mStack) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Intepreter/DelegateAdapter.cs:912)
ILRuntime.Runtime.Intepreter.DelegateAdapter.ILInvoke (ILRuntime.Runtime.Intepreter.ILIntepreter intp, ILRuntime.Runtime.Stack.StackObject* esp, System.Collections.Generic.IList`1[T] mStack) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Intepreter/DelegateAdapter.cs:855)
ILRuntime.Runtime.Intepreter.FunctionDelegateAdapter`2[T1,TResult].InvokeILMethod (T1 p1) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Intepreter/DelegateAdapter.cs:117)
System.Linq.Enumerable.Sum[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] selector) (at <351e49e2a5bf4fd6beabb458ce2255f3>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
ILRuntime.CLR.Method.CLRMethod.Invoke (ILRuntime.Runtime.Intepreter.ILIntepreter intepreter, ILRuntime.Runtime.Stack.StackObject* esp, System.Collections.Generic.IList`1[T] mStack, System.Boolean isNewObj) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/CLR/Method/CLRMethod.cs:316)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Library/PackageCache/com.ourpalm.ilruntime@1.6.7/Runtime/Intepreter/ILIntepreter.cs:1833)
Rethrow as ILRuntimeException: Exception has been thrown by the target of an invocation.
IL_005d: call System.Single System.Linq.Enumerable::Sum<UnityEngine.Vector3>(System.Collections.Generic.IEnumerable`1<!!0>,System.Func`2<!!0,System.Single>)
HotFix.HotFixLauncher.XXX() (at Assets/Scripts/HotFix/HotFixLauncher.cs:17)

**Comment by liiir1985** [comment]
已在2.0.0中修复

**Comment by Yellowchongqing** [comment]
请问2.0.0什么时候会发布，目前项目会偶发的触发这个问题
