### ISSUE TITLE
JITOnDemand模式值类型异常

### ISSUE THREAD

**Issue by kkvskkkk** [Ourpalm/ILRuntime#506]
public struct xxStruct
            {
                public string _name;
                public float _duration;

                public Anim(string name, float duration)
                {
                    this._name = name;
                    this._duration = duration;
                }
            }

void xxxCB()
{
   xxx犯罪函数();
}

 Transform xxx犯罪函数()
{

  Dictionary<int, xxStruct> datas = new ictionary<int, xxStruct>();
  var anims = spine动画某接口().Animations;  // ExposedList<Animation>类型 Animation 
  for (int i = 0; i < anims .Count; i++)
  {
    var item = anims.Items[i];
    var v1 = item.Name;   // getter string
    var v2 = item.Duration; // getter  float

    datas[i] = new xxStruct(v1, v2);  <------ 犯罪代码
   }
}

**Comment by kkvskkkk** [comment]
None 和 JITImmediately 我测试下是没出现过

**Comment by kkvskkkk** [comment]
我的操作是运行这个newobj的函数的 上一层函数 我手工点10次界面让他切换到jit模式。jit模式调用函数B 函数B执行循环调用触发newobj  第一次AllocExisting返回false 正常  第二次返回true gg

**Comment by liiir1985** [comment]
已修复
