### ISSUE TITLE
Vector2 与 Vector3 在新版本中绑定出现问题

### ISSUE THREAD

**Issue by HeNuoScott** [Ourpalm/ILRuntime#507]
旧版的UnityEngine.Vector3=>public struct Vector3 : IEquatable<Vector3>
新版的UnityEngine.Vector3=>public struct Vector3 : IEquatable<Vector3>,IFormattable

由于 新版unity对Vector3以及Vector2 进行了变动,在官方给出的Vector3Binder和Vector2Binder绑定后 
实际调用过程中会出现 
not found ValueTypeBinder:UnityEngine.Vector3
或者
not found ValueTypeBinder:UnityEngine.Vector2

**Comment by liiir1985** [comment]
新版本是多新？有具体的unity版本号吗

**Comment by HeNuoScott** [comment]
2021以后




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月19日(星期三) 上午10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ourpalm/ILRuntime] Vector2 与 Vector3 在新版本中绑定出现问题 (#507)





 
新版本是多新？有具体的unity版本号吗

**Comment by liiir1985** [comment]
2021.1.7f1c1上无法重现

**Comment by yqsas** [comment]
@HeNuoScott 请问解决了吗，我这边2020.3也遇到了

**Comment by yqsas** [comment]
我也遇到这个问题。
排查后发现要先注册值类型绑定，再注册CLR绑定，搞反了就会出现这个问题
