### ISSUE TITLE
同样的逻辑比lua慢好多

### ISSUE THREAD

**Issue by 892613744** [Ourpalm/ILRuntime#51]

**Comment by 892613744** [comment]
差不多慢一倍

**Comment by liiir1985** [comment]
ILRuntime的性能跟几个因素相关：
1、你编译的DLL是否是Release版
2、你是否在Unity编辑器中运行（编辑器中会慢很多，测试性能请发布到真机，并且关闭DevelopmentBuild）
3、跨域调用Unity和System的接口有没有进行CLRBinding

以上因素可以影响到10倍左右的性能

**Comment by 892613744** [comment]
好的 我在试一下  热更dll里面用到的方法都进行了绑定 dll也是release版的 但确实没有关闭devlopmentbuild 我在试一下 谢谢的你解答

**Comment by 892613744** [comment]
types.Add(typeof(DG.Tweening.Tweener));

        types.Add(typeof(BaseMessage));
        types.Add(typeof(GameUIManager));
        types.Add(typeof(Asgard.AsgardGame));
        types.Add(typeof(Asgard.DataDispatcher));
        types.Add(typeof(Asgard.ModuleManager));
        types.Add(typeof(Asgard.UI.UGUITools));
        types.Add(typeof(Asgard.EventTriggerListener));
        types.Add(typeof(MessageDataFactory));
        types.Add(typeof(MessageUtils));

        types.Add(typeof(GUIData));
        types.Add(typeof(ActivityShareData));
        types.Add(typeof(PlayerData.MONEY));
        types.Add(typeof(PlayerData));
        types.Add(typeof(CreateRoleModule));
        types.Add(typeof(PlayerRoleData));

        types.Add(typeof(PBMessage.CG_ASK_ACTIVENESSAWARD));
        types.Add(typeof(PBMessage.GC_REQ_ALL_ACTIVITY_STATE_RET));
        types.Add(typeof(PBMessage.GC_UPDATE_ACTIVITY_SPEED));
        types.Add(typeof(PBMessage.CG_BUY_YUANBAOGOODS));
        types.Add(typeof(PBMessage.GC_SHOP_BUY_MES));
        types.Add(typeof(PBMessage.GC_PUT_EXAM_ENCY));
        types.Add(typeof(PBMessage.GC_REQUEST_EXAM_EXCLUDE_RETURN));
        types.Add(typeof(PBMessage.CG_SYSTEMSHOP_SELL));
        types.Add(typeof(PBMessage.CG_HP_OPT));


        types.Add(typeof(GCGame.Table.TableManager));
        types.Add(typeof(GCGame.Table.Tab_ActivenessAward));
        types.Add(typeof(GCGame.Table.Tab_RoleBaseAttr));
        types.Add(typeof(GCGame.Table.Tab_CharModel));
        types.Add(typeof(GCGame.Table.Tab_ExamActivity));
        types.Add(typeof(GCGame.Table.StrDictionary));
        types.Add(typeof(GCGame.Table.Tab_CommonItem));
        types.Add(typeof(GCGame.Table.Tab_EquipSet));
        types.Add(typeof(GCGame.Table.Tab_BloodItem));

        //types.Add(typeof(GameUtils), "GameUtils");
        types.Add(typeof(Asgard.BundleUtils));
        //types.Add(typeof(GCGame.Table.Tab_PetInfo), "GCGame.Table.Tab_PetInfo");
        //types.Add(typeof(GCGame.Table.Tab_PetStarUpInfo), "GCGame.Table.Tab_PetStarUpInfo");

        types.Add(typeof(SFakeObject));
        types.Add(typeof(SFakeObjectFactory));
        types.Add(typeof(GameUtils));
        types.Add(typeof(ObjExportLua));

        types.Add(typeof(GlobalDefine.CharacterDefine));
        types.Add(typeof(GlobalDefine.GlobalVar));
        types.Add(typeof(GlobalDefine.GlobalEnum));

        types.Add(typeof(InfinityVerticalLayoutGroup));
        types.Add(typeof(ItemSlotLogic));
        types.Add(typeof(ModelDragLogic));
        types.Add(typeof(GameManager));
        types.Add(typeof(MessageBoxLogic));
        types.Add(typeof(Asgard.SimpleUIItem));
        types.Add(typeof(LP.LPTools));
        types.Add(typeof(LP.LPCommon));
        types.Add(typeof(TipsCommonLogic));
        types.Add(typeof(LoginUILogic));
        types.Add(typeof(PlayerPreferenceData));
        types.Add(typeof(NetStateHandler));
        types.Add(typeof(AccountData));
        types.Add(typeof(PlayerRoleData));
        types.Add(typeof(ServerInfoData));
        types.Add(typeof(ServerPageData));
        types.Add(typeof(PlatformHelper));
        types.Add(typeof(ClanModule));
        types.Add(typeof(TopMenuToggleChangeLogic));
        types.Add(typeof(LeftMenuToggleChangeLogic));
        types.Add(typeof(ToggleChangeBase));
        types.Add(typeof(Games.Item.GameItem));
        types.Add(typeof(UnityEngine.UI.ScrollPage));
        types.Add(typeof(PointGridLogic));
        types.Add(typeof(Games.Item.GameItemContainer));
        types.Add(typeof(Games.Item.ItemTool));
        types.Add(typeof(OtherPlayerData));
        types.Add(typeof(RoleViewModule));
        types.Add(typeof(ItemFlyModule));
        types.Add(typeof(PullDownMainLogic));
        types.Add(typeof(PullDownMainModule));
        types.Add(typeof(PullDownStairNode));
        types.Add(typeof(PullDownBtnLogic));
        types.Add(typeof(PullDownBtnItemLogic));
        types.Add(typeof(FlyItem));
        types.Add(typeof(CampModule));
        types.Add(typeof(MythicalAnimalsModule));
        types.Add(typeof(NatureItemLogic));
        types.Add(typeof(NewHandModule));
        types.Add(typeof(AddNumParam));
        types.Add(typeof(AddNumLogic));
        types.Add(typeof(Extend.ETransform));
        types.Add(typeof(LogModule));
        types.Add(typeof(ClanWarModule));
        types.Add(typeof(PlayerFrameModule));

        types.Add(typeof(UnityEngine.Events.UnityEventBase));
        types.Add(typeof(UnityEngine.Events.UnityEvent));
        types.Add(typeof(UnityEngine.Object));
        types.Add(typeof(UnityEngine.Component));
        types.Add(typeof(UnityEngine.Behaviour));
        types.Add(typeof(UnityEngine.MonoBehaviour));
        types.Add(typeof(UnityEngine.GameObject));
        types.Add(typeof(UnityEngine.Transform));
        types.Add(typeof(UnityEngine.RectTransform));
        types.Add(typeof(UnityEngine.Time));
        types.Add(typeof(Vector2));
        types.Add(typeof(Vector3));
        types.Add(typeof(Vector4));
        types.Add(typeof(UnityEngine.Quaternion));
        types.Add(typeof(UnityEngine.Debug));
        types.Add(typeof(UnityEngine.Mathf));
        types.Add(typeof(UnityEngine.Random));
        types.Add(typeof(UnityEngine.Resources));
        types.Add(typeof(UnityEngine.TextAsset));
        types.Add(typeof(UnityEngine.CanvasGroup));
        types.Add(typeof(UnityEngine.EventSystems.UIBehaviour));
        types.Add(typeof(UnityEngine.UI.Selectable));
        types.Add(typeof(UnityEngine.UI.Button));
        types.Add(typeof(UnityEngine.UI.MyButton));
        types.Add(typeof(UnityEngine.UI.Graphic));
        types.Add(typeof(UnityEngine.UI.MaskableGraphic));
        types.Add(typeof(UnityEngine.UI.Image));
        types.Add(typeof(UnityEngine.UI.RawImage));
        types.Add(typeof(UnityEngine.UI.Slider));
        types.Add(typeof(UnityEngine.UI.Text));
        types.Add(typeof(UnityEngine.UI.Toggle));
        types.Add(typeof(UnityEngine.UI.ToggleGroup));
        types.Add(typeof(UnityEngine.UI.Scrollbar));
        types.Add(typeof(UnityEngine.UI.GridLayoutGroup));
        types.Add(typeof(UnityEngine.UI.HorizontalLayoutGroup));
        types.Add(typeof(UnityEngine.UI.InputField));
        types.Add(typeof(UnityEngine.UI.VerticalLayoutGroup));
        types.Add(typeof(UnityEngine.UI.LayoutElement));
这些是注册类型 lua同样也是这些  现在按照你说的环境都是一样的（包括dll是否是release  ） 确实比lua慢一些 难道我哪里还有没注意到地方吗  因为development关闭 profiler连不上手机看不到分析数据 目测lua版的会快一些 之前在pc上测试 看主要消耗在 ILIntepreter的execute和invoke

**Comment by 892613744** [comment]
还有就是 那些unity类 基本上也和lua一样 注册的时候做了一些函数的剔除

**Comment by 892613744** [comment]
希望你帮我找到问题 由于ios禁止热更特意提到lua这一块 所以现在想换成il

**Comment by liiir1985** [comment]
关闭profiler你可以通过打时间戳来分析耗时
另外就是看你Lua是用的lua53还是luajit，luajit需要在iOS上进行测试（因为有没有jit是天壤之别，iOS无法开启jit）
然后就是看你具体做的什么操作。
如果是纯计算的操作（例如for 很多，然后加减乘除之类）
lua肯定会更快，但是如果是调用unity接口之类的居多，ilruntime肯定更快

如果你依然对性能这块有疑问，你可以提交一个测试用例，然后可以帮你分析性能开销在哪一块

**Comment by 892613744** [comment]
好的 谢谢 我在看一下

**Comment by 892613744** [comment]
我这边主要做的就是一些ui逻辑的热更新

**Comment by liiir1985** [comment]
你加QQ群512079820讨论吧，通过这个太费劲了

**Comment by 892613744** [comment]
好的 大神 哈哈
