### ISSUE TITLE
最新的1.6.7版本，里面也有好多.net 4.0新特性，在.net 2.0上用不了

### ISSUE THREAD

**Issue by jiezuowhu** [Ourpalm/ILRuntime#514]
比如method.ReturnType?.ReflectionType;这种还可以通过反编译找回.net 2.0的写法
还有就是IReadOnlyCollection（.net 2.0上是直接木有的）

**Comment by liiir1985** [comment]
这个跟你unity和热更工程选择的.net版本有关，跟ilruntime关系不大

**Comment by jiezuowhu** [comment]
> 这个跟你unity和热更工程选择的.net版本有关，跟ilruntime关系不大

后面是不再支持.net 3.5了么，Unity2017跟Unity5，都还是.net 3.5版本
