### ISSUE TITLE
当热更dll中包含字段包含 volatile 修饰符,自动分析热更DLL生成CLR绑定报错

### ISSUE THREAD

**Issue by walkmanilove123** [Ourpalm/ILRuntime#515]
当我尝试将第三方dll集成到我得热更中时,加载后并运行自动分析热更DLL生成CLR绑定时,抛出如下异常:Cannot find Type:System.UInt16 modreq(System.Runtime.CompilerServices.IsVolatile)
跟踪发现其中使用了volatile修饰字段,而ILRuntime没有处理这样的情况
请问在保留"volatile"修饰符情况下,ILRuntime能否处理下这样的情况,感谢!

**Comment by liiir1985** [comment]
不支持volatile等需要直接硬件支持的功能
