### ISSUE TITLE
热更工程中MethodInfo.CreateDelegate报错 NotSupportedException: Derived classes must provide an implementation.

### ISSUE THREAD

**Issue by fujisheng** [Ourpalm/ILRuntime#523]

**Comment by buffoonless** [comment]
同上，写了测试代码
`
public class Test
    {
        [NetEventBind(1)]
        public int A(bool a)
        {
            return 1;
        }

        public static void check()
        {
            //检测之前已经注册了appdomain.DelegateManager.RegisterFunctionDelegate<bool, int>();
            var typeInfoTest = typeof(Test);
            var methods = typeInfoTest.GetMethods();
            var instence = new Test();
            foreach (var method in methods)
            {
                var attributes = method.GetCustomAttributes(false);
                foreach (var item in attributes)
                {
                    if (item is NetEventBind netBind)
                    {
                        //这里会报ArgumentException: method return type is incompatible错误
                        var setter = (Func<bool, int>)Delegate.CreateDelegate(typeof(Func<bool, int>), instence, method);

                    }
                }
            }
        }
    }
`

**Comment by buffoonless** [comment]
写了测试代码
`public class Test
    {
        [NetEventBind(1)]
        public int A(bool a)
        {
            return 1;
        }

        public static void check()
        {
            //检测之前已经注册了appdomain.DelegateManager.RegisterFunctionDelegate<bool, int>();
            var typeInfoTest = typeof(Test);
            var methods = typeInfoTest.GetMethods();
            var instence = new Test();
            foreach (var method in methods)
            {
                var attributes = method.GetCustomAttributes(false);
                foreach (var item in attributes)
                {
                    if (item is NetEventBind netBind)
                    {
                        //这里会报ArgumentException: method return type is incompatible错误
                        var setter = (Func<bool, int>)Delegate.CreateDelegate(typeof(Func<bool, int>), instence, method);

                    }
                }
            }
        }
    }`

**Comment by liiir1985** [comment]
暂不支持通过反射创建热更内委托
