### ISSUE TITLE
热更新可变参函数 填入 热更新内定义的委托 报错

### ISSUE THREAD

**Issue by qq576067421** [Ourpalm/ILRuntime#529]
测试用例：
热更新中代码
        public delegate void LAction<in T1, in T2>(T1 arg1, T2 arg2);
        public void Start()
        {
            LAction<long, decimal> call = TTTTTest;
            test(call);
        }
        private void TTTTTest(long l, decimal s)
        {
            Debug.LogError("  sssss+" + l + " ttttt" + s);
        }
        private void test(params object[] p)
        {
            LAction<long, decimal> call = (LAction<long, decimal>)p[0];
            call(1, 2222222222222222222);
        }

**Comment by niu-shuang** [comment]
有注册委托生成器么

**Comment by liiir1985** [comment]
将热更内委托放入object[]会导致委托跨域，并marshal成Action<long, decimal>，这个操作不可逆，故请避免这种用法
