### ISSUE TITLE
标签赋值枚举属性报空指针异常

### ISSUE THREAD

**Issue by zouchenjin** [Ourpalm/ILRuntime#545]
![image](https://user-images.githubusercontent.com/70745946/127092438-52a6e92a-bff0-465f-b934-951f5b3a1f95.png)
标签赋值枚举属性报空指针异常。
![image](https://user-images.githubusercontent.com/70745946/127092620-8c8d4786-5443-4432-aad5-72a4b41d5586.png)
发现这里MemberInfo对象GetCustomAttributes出来的内容对应aindex字段是null

**Comment by liiir1985** [comment]
Attribute暂时只支持基础类型，如int, bool, string
