### ISSUE TITLE
调式器出现"ILRuntime Debugger version mismatch"的错误

### ISSUE THREAD

**Issue by wakin001** [Ourpalm/ILRuntime#546]
热更工程改动后，编译，再启动ILRuntime的dubugger，经常会出现"ILRuntime Debugger version mismatch"的错误。
重启电脑后会修复。

环境：
Unity2020.3.6f1
VS 2019 Community
ILRuntime 1.6.7 (Debugger: ILRuntimeDebugger_VS15_17_19.zip)

**Comment by wakin001** [comment]
补充：
出现"ILRuntime Debugger version mismatch"的错误后，重启电脑，却又出现“Cannot connect to ILRuntime”的错误。

**Comment by liiir1985** [comment]
出现version mismatch只能说明被其他程序占用了端口号，可以自行更换一个其他端口号。Cannot connect to ILRuntime需要自行检查DebugServer是否启动（执行过相关代码）且端口号匹配
