### ISSUE TITLE
热更新代码中 二维结构体数组赋值报错

### ISSUE THREAD

**Issue by ColinCollins** [Ourpalm/ILRuntime#548]
vs 2019, ILRuntime 1.6.7

热更新(Hotfix)测试代码：
struct Test
{
    public int X;
}
...
Test[,] tests = new Test[3,3];

热更新代码报错。
![image](https://user-images.githubusercontent.com/35832931/127323018-a9524d93-8e73-434e-a203-e6b84d69b3d6.png)

**Comment by JasonXuDeveloper** [comment]
本就不支持[,]，用[] []
