### ISSUE TITLE
GameObject.FindObjectsOfType<T(where T : MonoBehaviour)> 搜索结果错误

### ISSUE THREAD

**Issue by ColinCollins** [Ourpalm/ILRuntime#549]
![image](https://user-images.githubusercontent.com/35832931/127489460-54fa1c84-64ec-4f19-9f9a-2b535ed80403.png)

**Comment by liiir1985** [comment]
能否提供可复现问题的测试用例

**Comment by ColinCollins** [comment]
这三个类型都继承自 Monobehaviour, 我想大概是 Adaptor 的 type 的原因吧，暂时忙项目了，可能之后在研究吧，抱歉。
