### ISSUE TITLE
生成绑定代码的时候没有处理静态构造方法

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#55]
BindingCodeGenerator.cs
Line:307
CrawlAppdomain()方法里

                    foreach (var i in ((CLR.TypeSystem.ILType)type).GetConstructors())
                        methods.Add(i);

这里并没有包含StaticConstructor。
这样可能会导致一些在静态构造方法里创建的泛型类的构造方法不会生成到绑定代码中，导致在il2cpp下出错。

**Comment by liiir1985** [comment]
静态构造函数没有办法进行binding，因为并没有办法直接调用静态构造函数，默认情况静态方法里面用到的东西是不会被il2cpp剪裁的

**Comment by liiir1985** [comment]
已经加上
