### ISSUE TITLE
ILRuntime和AssetBundle结合，可以实现加载新的场景吗

### ISSUE THREAD

**Issue by guoguoguilai** [Ourpalm/ILRuntime#554]
作者大大你好，我在尝试在Unity中动态加载新的游戏场景，但是查阅资料后发现，AssetBundle中不存在于原始工程的脚本在加载Asset之后是无法执行的。所以我就在想，能否通过ILRuntime先把脚本加载到工程里，然后再加载AssetBundle。请问这个方案是否可行呢？

**Comment by liiir1985** [comment]
理论上可以，但是实际上不推荐热更Monobehaviour，并且你也没法直接把热更脚本保存到prefab里，会需要自己处理很多东西
