### ISSUE TITLE
字典获取值 的时候  out 进去的参数是数组 的时候返回出来的有时候是空值 

### ISSUE THREAD

**Issue by xjaksyt2008** [Ourpalm/ILRuntime#56]
if (!EntityDef.id2datatypes.TryGetValue(msgargtypes[i], out argtypes[i]))
  这样写,argtypes[i]有时候是空值

KBEDATATYPE_BASE n = null;
EntityDef.id2datatypes.TryGetValue(msgargtypes[i], out n);
 argtypes[i] = n;
要改成这样才行~~

**Comment by liiir1985** [comment]
Fixed
