### ISSUE TITLE
热更工程中delegate的BeginInvoke貌似直接报错

### ISSUE THREAD

**Issue by thinbug** [Ourpalm/ILRuntime#562]
大概代码是这样的
`
public delegate void AsyncConnectMethod(ConnectState state);
.......
                       AsyncConnectMethod asyncConnectMethod = new AsyncConnectMethod(this._asyncConnect);

			ConnectState state = new ConnectState();
			state.connectIP = ip;
			state.connectPort = port;
			state.connectCB = callback;
			state.userData = userData;
			state.socket = _socket;
			state.networkInterface = this;
			state.caller = asyncConnectMethod;

			Dbg.DEBUG_MSG("connect to " + ip + ":" + port + " ...");
			connected = false;
			
			// 先注册一个事件回调，该事件在当前线程触发
			Event.registerIn("_onConnectionState", this, "_onConnectionState");
			//Dbg.DEBUG_MSG("connect 2 " + ip + ":" + port + " ...");
			
			AsyncCallback back = new AsyncCallback(this._asyncConnectCB);
			asyncConnectMethod.BeginInvoke(state, back, state);
`

执行到asyncConnectMethod.BeginInvoke就直接报错了 , 但是asyncConnectMethod,state,back都不是空的

System.NullReferenceException: Object reference not set to an instance of an object

  at ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) [0x0329f] in H:\tapqueGit\dk_paintlyUnity\kbeUnity\Library\PackageCache\com.ourpalm.ilruntime@1.6.7\Runtime\Intepreter\ILIntepreter.cs:1790 
System.Reflection.MethodBase:Invoke (object,object[])

**Comment by JasonXuDeveloper** [comment]
热更工程不能BeginInvoke委托 只能Invoke

**Comment by liiir1985** [comment]
不支持BeginInvoke
