### ISSUE TITLE
现在是否还有必要为值类型写ValueTypeBinder

### ISSUE THREAD

**Issue by sagasarate** [Ourpalm/ILRuntime#564]
我用到了Rect类型，所以写了个ValueTypeBinder，但说实在的写ValueTypeBinder需要对IL指令的工作机制有所了解才行，我边摸索边写，目前还是有各种意料外的bug，不知道现在还有没有必要写ValueTypeBinder，因为我看到分析dll自动生成的绑定代码也对值类型的访问做了绑定。

**Comment by liiir1985** [comment]
ValueTypeBinder的作用并不是让你能使用这个类型，而是降低这个类型作为临时变量时，new时候的开销。 如果事先了ValueTypeBinder，对临时变量频繁new也不会产生任何内存分配。但是CLR绑定能做的仅仅是消除调用方法时的反射开销，并不能降低值类型临时变量频繁new时的开销
