### ISSUE TITLE
一个项目需要写适配器和重定向的地方太多了，有没有一键生成的方法，这样很难工程话啊~

### ISSUE THREAD

**Issue by zhanghaigang666** [Ourpalm/ILRuntime#566]
一个项目需要写适配器和重定向的地方太多了，有没有一键生成的方法，这样很难工程化啊~ 成本很高啊，非专人根本搞不懂，一个团队只有固定的人才能摸索写这东西  ，很烦啊  ~~~

**Comment by liiir1985** [comment]
为什么会需要写很多重定向？ 正常来说一个项目需要手动添加的重定向不应该超过3处
适配器你指的什么适配器？ 跨域继承适配器？ 跨域继承一个项目一样不应该多于3个类需要写适配器，如果有很多要写说明你用法不对

**Comment by zhanghaigang666** [comment]
就用MonoBehaviour跨域继承的方法，否则ilruntime还有多少优势？
