### ISSUE TITLE
和继承适配器有关的改动

### ISSUE THREAD

**Issue by sagasarate** [Ourpalm/ILRuntime#569]
我在自己的项目里使用了FairyGUI，为了实现它的自定义扩展，要在热更DLL内存声明类去继承外部的FairyGUI的组件类，然后再交给FairyGUI在加载UI的时候生成对象，是个挺绕的过程。
我先定义并注册了FairyGUI组件类的继承适配器，然后注册了对象生成用的委托到FairyGUI，测试下来能正确生成对象，但是获取的时候没有能正确拿到ILTypeInstance，看了下代码，是没有正确处理继承适配器，于是我改了下：
在处理OpCodeEnum.Box指令的地方，后面对于对象处理的地方加了
else if (obj is CrossBindingAdaptorType)
{
    esp = PushObject(objRef, mStack, (obj as CrossBindingAdaptorType).ILInstance, true);
}
还有一个地方：OpCodeEnum.Isinst指令，后面类似的地方加代码
                                                else if(obj is CrossBindingAdaptorType)
                                                {
                                                    ILTypeInstance ins = (obj as CrossBindingAdaptorType).ILInstance;
                                                    if (ins != null && ((ILTypeInstance)ins).CanAssignTo(type))
                                                    {
                                                        esp = PushObject(oriRef, mStack, ins);
                                                    }
                                                    else
                                                    {
#if !DEBUG || DISABLE_ILRUNTIME_DEBUG
                                                        oriRef->ObjectType = ObjectTypes.Null;
                                                        oriRef->Value = -1;
                                                        oriRef->ValueLow = 0;
#endif
                                                    }
                                                }
来返回继承适配器内部的ILTypeInstance，目前测试下来暂时能正常工作

**Comment by liiir1985** [comment]
在ILRuntime解译器内部不应该出现(obj is CrossBindingAdaptorType的这种情况，按道理说所有主工程往ilruntime传参数的时候都需要在进入ILRuntime前取ILInstance，如果出现了这种情况，那要么是你自己写的适配器或者对象生成委托在传参时没有事先取ILInstance，要么出现了bug，那就需要你提供测试用例。 这个问题不应该在解译器解译时处理
