### ISSUE TITLE
How to run tests properly?

### ISSUE THREAD

**Issue by kamyker** [Ourpalm/ILRuntime#578]
I've tried running tests from TestCase,dll in ILRuntimeTest but some of them fail. Am I doing something wrong?

![image](https://user-images.githubusercontent.com/9093037/131660076-0f610cd5-b5f2-42ec-af2b-77d94f1b5856.png)
![image](https://user-images.githubusercontent.com/9093037/131660194-b47ab189-8583-489a-9f79-c2e8f10f4eb7.png)
![image](https://user-images.githubusercontent.com/9093037/131660246-5703b783-cdd6-42ee-9ac2-2d67f950dc44.png)

**Comment by liiir1985** [comment]
You're not doing things wrong. Some test cases are failing, because it's impossible to implement at the time. And a few of them are supposed to fail, which are bad test cases, I'll correct them if I get time.
