### ISSUE TITLE
AppDomain.GetType()方法中对一些类型没有缓存

### ISSUE THREAD

**Issue by larlf** [Ourpalm/ILRuntime#60]
测试代码（脚本）：

        public static Dictionary<string, int> p3 = new Dictionary<string, int>();
        ... ...
                p3["1"] = 1;
                p3["2"] = 2;
                p3["3"] = 3;
                p3["4"] = 4;
                p3["5"] = 5;
                p3["6"] = 6;
                p3["7"] = 7;
                p3["8"] = 8;
                p3["9"] = 9;
                p3["10"] = 10;
                p3["11"] = 11;
                p3["12"] = 12;
            ... ...
            string key;
            Dictionary<string, int>.Enumerator enumerator = p3.GetEnumerator();
            while (enumerator.MoveNext())
            {
                key = enumerator.Current.Key;
            }

发现如下类型因为没有被缓存到mapType中，每次调用AppDomain.GetType()都会重新生成一次:

           System.Collections.Generic.KeyValuePair`2[[System.String, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.Int32, mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089

**Comment by liiir1985** [comment]
已修复
