### ISSUE TITLE
版本2.0.0 Preview 13 中连续多次Json解析错误（解析类型使用了泛型）

### ISSUE THREAD

**Issue by boswelyu** [Ourpalm/ILRuntime#612]
**Describe the bug**
描述bug现象：
在热更工程中执行 Dictionary<TKey, TValue> datas = LitJson.JsonMapper.ToObject<Dictionary<TKey, TValue>>(json);
第一次操作一定能成功，但是TKey和TValue换成不同的类型再运行的时候，就会出错。JsonMapper会还是试图把后面的json当做第一次的结构去解析。

**To Reproduce**
请描述重现步骤或上下文

1、下载演示工程：http://dayu_p1alpha.cmge.com/download/ILRuntimeDemo.zip
2、打开场景 10_LitJson
3、运行
4、先点击按钮 Load Data 1. 会看到数据1加载，有三条运行日志，但是没有异常。
5、后点击按钮 Load Data 2. 会看到在最后有一条异常报出：
Got Exception: LitJson.JsonException: Can't assign value '1001' (type System.Int32) to type HotFix_Project.LevelFloorData。 
但是实际上，type HotFix_Project.LevelFloorData 应该是Load Data 1 中使用的类型，Data 2的类型应该是 LevelConfigData

6、如果运行后先点击 Load Data 2， 会发现Data 2 也可以成功解析；然后再点击Load Data 1, 会看到错误：
Got Exception: System.ArgumentException: Object of type 'System.Collections.Generic.Dictionary`2[System.Int32,ILRuntime.Runtime.Intepreter.ILTypeInstance]' cannot be converted to type 'System.Collections.Generic.Dictionary`2[System.Int32,System.Collections.Generic.Dictionary`2[System.Int32,ILRuntime.Runtime.Intepreter.ILTypeInstance]]'.
这里同样的，试图转换的类型是首先点击的Data 2 的解析类型。

**Expected behavior**
请描述应有的行为

第二次加载不应该按照第一次的类型去解析，加载应该成功

**Unity Version**
Please fill in the version of Unity you're currently using
请填写使用的Unity版本
Unity 2020.3.11f1c1

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
请填写使用的ILRuntime版本（package版本或Git提交号或下载日期）
ILRuntime 2.0.0 Preview 13

**Comment by liiir1985** [comment]
测试用例的下载链接已经失效……

**Comment by 0x2CA** [comment]
同样问题
[Test.zip](https://github.com/Ourpalm/ILRuntime/files/7672691/Test.zip)
