### ISSUE TITLE
关于InvalidCastException: Unable to cast object of type 'XXX' to type 'YYY' 的问题分析

### ISSUE THREAD

**Issue by Ojors** [Ourpalm/ILRuntime#613]
- 这个问题是个偶现问题，翻了下历史 Issues，也有人提过，但最后没有结果，ILRuntime 版本1.6.7

- 具体必现路径和出现原因暂时还没完全分析到，但通过收集相关报错反馈和对 ILCode 分析大概有以下猜想：
  1. 部分堆栈中都有 "ClassA/ClassB" 这样的内容，原因是这边有使用到不少 **内部类** 的写法，而内部类对应的 ILCode，微软官方有以下说明：
    > if the MyNamespace.MyClass class contains a nested class named NestedClass, the nested class is identified as follows: class MyNamespace.MyClass/NestedClass.
  2. 另外一类堆栈是没能明确看出问题，但分析后都有使用 **foreach** 的共性，反编译 foreach 成 ILCode 后发现，在获取 Enumerator 上也是有 ClassA/ClassB 的特点，例如：
```c#
List<int> list = new List<int>();
foreach(int i in list) // IL_0007: callvirt instance valuetype System.Collections.Generic.List`1/Enumerator<!0> class System.Collections.Generic.List`1<int32>::GetEnumerator()
{
}
```
- 所以得出最后的猜想：
  - 这类报错是否是因为解析这类 ClassA/ClassB 的 ILCode 时，在某个位置出现了解析异常，导致最后拿到的类型错误，强转失败？

**Comment by L-Fone** [comment]
ILRuntime 版本1.6.7 确实存在此问题，映射的类型不对，如图所示。
![1](https://user-images.githubusercontent.com/23207097/142598668-78d2df89-cb07-4463-8a2a-2ac9c0c09b7b.png)

**Comment by BesureChen-USTAR** [comment]
我们遇到过这个问题，ILType.cs类里面有个GetFieldIndex方法，里面token调用的GetHashCode有问题，hashcode会有重复的情况，导致OpCode执行的非预期

**Comment by liiir1985** [comment]
这个异常大多数情况是跟跨域继承相关的，内部类在执行时不会反复解析类型，跟这个应该没有关系
如果发现了可复现问题的用例，欢迎继续补充
