### ISSUE TITLE
在dll里写如下类型 然后在 untiy里点击动态生成时 会报错

### ISSUE THREAD

**Issue by gaochoa** [Ourpalm/ILRuntime#62]
public static Dictionary<EAttrType, EAttrType[]> dicAttrConver5 = new Dictionary<EAttrType, EAttrType[]>() { 
         { 
             EAttrType.Strength,new EAttrType[]{ EAttrType.Dexterity}},
        
        };
在 untiy里点击动态绑定 生成时 会报错 ArgumentException:failed to convert parmeters

**Comment by liiir1985** [comment]
已修复
