### ISSUE TITLE
CheckAndInvokeToInteger(T)的return ToInteger(val)在三星部分机型上会容易出现崩溃

### ISSUE THREAD

**Issue by hmh925** [Ourpalm/ILRuntime#620]
unity版本是2019.4.1f1，ilruntime版本是1.64，目前在部分三星手机上出现了这崩溃情况，都为同一原因导致，不清楚是触发了unity引擎的什么bug还是ilruntime的问题。
但根据有堆栈定位到0000000000c1f8e8 这一行的cpp代码对应到c#中的代码是
System.Int32 ILRuntime.Runtime.Enviorment.PrimitiveConverter`1<System.UInt64>::CheckAndInvokeToInteger(T)方法下的 return ToInteger(val);

backtrace:
PrimitiveConverter_1_CheckAndInvokeToInteger_m097B6C18F132550E929E943F7238A2CBE4D6AE58_gshared
PrimitiveConverter_1_CheckAndInvokeToDouble_m11E59D863926DF2C0B768829A4D5EAA40C6737BE_gshared
PrimitiveConverter_1_CheckAndInvokeFromFloat_mEEDBC5DF2A29B050F73F1D4B22BA98EF8927D83A_gshared
_ZL155WaitHandle_tFD46B5B45A6BB296EA3A104C91DF2A7C03C10AC6_CustomAttributesCacheGenerator_WaitHandle_get_SafeWaitHandle_m9BA6EA0D8DBD059147DE77EE1E36181EEB5A8AB1P21CustomAttributesCache

上报日志的两款三星机型
galaxy S21 running android 12  
galaxy S21 Ultra 5G

两份崩溃日志：
Fatal Exception: java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2019.4.1f1
Device model      : samsung SM-G991U
Device fingerprint: samsung/o1qsqw/o1q:12/SP1A.210812.016/G991USQU4BUKF:user/release-keys

Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.1f1 (009608a86eb7)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'samsung/o1qsqw/o1q:12/SP1A.210812.016/G991USQU4BUKF:user/release-keys'
Revision: '14'
ABI: 'arm64'
Timestamp: 2021-12-09 00:11:29-0600
pid: 6651, tid: 6768, name: UnityMain  >>> com.gametaiwan.idnew <<<
uid: 10002
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x29
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000001  x3  0000000000000055
    x4  0000000000000021  x5  0000000000000000  x6  731f64716e6c1f6c  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000001  x9  97e90950b7c05641  x10 0000000000000001  x11 0000000000000001
    x12 0000006e7130bc90  x13 000000000000004d  x14 0000000000000000  x15 0000000034155555
    x16 0000006e74a14a48  x17 000000720872ea84  x18 000000710df58068  x19 0000006e74a55e00
    x20 000000720b1e7fe0  x21 0000006e74a55ea8  x22 0000000000000005  x23 0000006e74a45250
    x24 0000000000000010  x25 0000000000000023  x26 0000000000000023  x27 0000006e74a46a86
    x28 0000000000000018  x29 0000000000003234
    sp  0000006e7130d6e0  lr  0000006e7403e8a0  pc  0000006e7403e8e8

backtrace:
      #00 pc 0000000000c1f8e8  /data/app/~~IZAv7KSolQXkfVvqPFtXVw==/com.gametaiwan.idnew-0EIaYW7Hg7g_jj0Hhgmnng==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #01 pc 0000000000c1f488  /data/app/~~IZAv7KSolQXkfVvqPFtXVw==/com.gametaiwan.idnew-0EIaYW7Hg7g_jj0Hhgmnng==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #02 pc 0000000000c1f3d8  /data/app/~~IZAv7KSolQXkfVvqPFtXVw==/com.gametaiwan.idnew-0EIaYW7Hg7g_jj0Hhgmnng==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #03 pc 0000000000408b24  /data/app/~~IZAv7KSolQXkfVvqPFtXVw==/com.gametaiwan.idnew-0EIaYW7Hg7g_jj0Hhgmnng==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #04 pc 000000<truncated: 174 chars>
       at split_config.0xc1f8e8()
       at split_config.0xc1f488()
       at split_config.0xc1f3d8()
       at split_config.0x408b24()
       at split_config.0x10fec50()
	   
--------------------------------------------------------------------------------------
Fatal Exception: java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2019.4.1f1
Device model      : samsung SM-G998U
Device fingerprint: samsung/p3qsqw/p3q:12/SP1A.210812.016/G998USQU4BUK9:user/release-keys

Caused by java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.1f1 (009608a86eb7)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
Build fingerprint: 'samsung/p3qsqw/p3q:12/SP1A.210812.016/G998USQU4BUK9:user/release-keys'
Revision: '20'
ABI: 'arm64'
Timestamp: 2021-12-08 20:18:19-0500
pid: 31619, tid: 31759, name: Loading.Preload  >>> com.gametaiwan.idnew <<<
uid: 10491
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x3d9
Cause: null pointer dereference
    x0  0000000000000000  x1  0000000000000000  x2  0000000000000001  x3  0000000000000055
    x4  0000000000000021  x5  0000000000000000  x6  731f64716e6c1f6c  x7  7f7f7f7f7f7f7f7f
    x8  0000000000000001  x9  8f6a7f263a527a0c  x10 0000000000000001  x11 0000000000000001
    x12 0000007a4d4daaa0  x13 000000000000004d  x14 0000000000000000  x15 0000000034155555
    x16 0000007ae1036a48  x17 0000007e7d26ba84  x18 0000007da75701fb  x19 0000007ae1077e00
    x20 00000079f74c0280  x21 0000007ae1077ea8  x22 000000000000007b  x23 0000007ae1067250
    x24 0000000000000010  x25 000000000000004a  x26 000000000000004a  x27 0000007ae1068a86
    x28 0000000000000018  x29 0000000000003234
    sp  0000007a4d4dc4f0  lr  0000007ae06608a0  pc  0000007ae06608e8

backtrace:
      #00 pc 0000000000c1f8e8  /data/app/~~bRGOPmHpRyrExR07c_n0wQ==/com.gametaiwan.idnew-dFBH7XuGxRJws6A-yxayZQ==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #01 pc 0000000000c1f488  /data/app/~~bRGOPmHpRyrExR07c_n0wQ==/com.gametaiwan.idnew-dFBH7XuGxRJws6A-yxayZQ==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #02 pc 0000000000c1f3d8  /data/app/~~bRGOPmHpRyrExR07c_n0wQ==/com.gametaiwan.idnew-dFBH7XuGxRJws6A-yxayZQ==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #03 pc 0000000000408b24  /data/app/~~bRGOPmHpRyrExR07c_n0wQ==/com.gametaiwan.idnew-dFBH7XuGxRJws6A-yxayZQ==/split_config.arm64_v8a.apk (BuildId: c3e2101a555e6cf98180a04016b63f5ba7df0ba2)
      #04 <truncated: 2599 chars>
       at split_config.0xc1f8e8()
       at split_config.0xc1f488()
       at split_config.0xc1f3d8()
       at split_config.0x408b24()
       at split_config.0x567e18()
       at split_config.0xc2b0fc()
       at split_config.0xc37590()
       at split_config.0x619460()
       at split_config.0x6107ec()
       at split_config.0x6109a4()
       at split_config.0x50f9fc()
       at split_config.0x231b08()
       at split_config.0x511c88()
       at split_config.0x511ad4()
       at split_config.0x511a40()
       at split_config.0x589b80()
       at libc.__pthread_start(void*)(__pthread_start:264)
       at libc.__start_thread(__start_thread:68)

**Comment by liiir1985** [comment]
可能是unity的bug， 尝试升级一下unity的版本看看能不能解决问题？ 
只在三星的机器上出现？

**Comment by hmh925** [comment]
> 可能是unity的bug， 尝试升级一下unity的版本看看能不能解决问题？ 只在三星的机器上出现？

谢谢，确认是unity的问题，升级到2019.4.34后就解决了，是安卓12下的问题
