### ISSUE TITLE
可以支持VS2022么 ?

### ISSUE THREAD

**Issue by flaidxu** [Ourpalm/ILRuntime#621]
可以支持VS2022么 ?

**Comment by AshaSalorina** [comment]
#661 希望可以帮到你

**Comment by Endures** [comment]
master分支现在已支持vs2022，虽然扩展包还没有发布，但是可以自己生成。使用vs2022生成工程 ILRuntime/Debugging/VS2022/ILRuntimeDebuggerLauncher2022/ILRuntimeDebuggerLauncher2022.csproj

**Comment by JT1990** [comment]
按照提示已经生成了ILRuntimeDebuggerLauncher2022.csproj,然后怎么操作

**Comment by AshaSalorina** [comment]
> 

使用发布来打包vs拓展程序，然后安装就可以了

**Comment by JiekeZhu** [comment]
> 求作者支持VS2022啊

1. 用VS2022打开ILRuntime.sln，这时会自动安装VS插件开发库。
2. 安装完成后，切换的Release。
3. 右键工程中的Debugging/VS2022/ILRuntimeDebuggerLauncher2022项目，点击Rebuild重新生成，就能找到插件
ILRuntime-master\Debugging\VS2022\ILRuntimeDebuggerLauncher2022\bin\Release\ILRuntimeDebuggerLauncher2022.vsix
4. 安装插件，开始调试。
