### ISSUE TITLE
调试插件点attach报错

### ISSUE THREAD

**Issue by lenovo734646** [Ourpalm/ILRuntime#622]
有时候报Debugger Version mismatch。是在这里的1.6.7版release里下的调试插件。
有时候是直接报找不到.cs文件，这个cs文件是addressable包，我把它放在另外一个目录下面，然后通过导入本地package的方式加入的，
我看报错是去Library下面的packageCache下面去找了。本地方式packageCache下面确实没有。
我这边没有成功过，就报这两个错中的一个。

**Comment by liiir1985** [comment]
Debugger version mismatch说明有其他软件占用了调试端口，调试器连上的不是ilruntime而是其他什么软件，导致协议不匹配

然后报找不到.cs文件通常是无效的断点（源文件移动了位置之类的），这个错误可以无视，可以通过调试->删除所有断点清除
