### ISSUE TITLE
IL2.0 开启JITOnDemand Quaternion会报错

### ISSUE THREAD

**Issue by CxDtreeg** [Ourpalm/ILRuntime#629]
**Describe the bug**
会抛出错误

**To Reproduce**
开启了JITOnDemand之后报错
定义了static Quaternion属性然后多次赋值给类里面的Quaternion属性导致报错，如果每次都new一个Quaternion赋值就没有问题
```
public class PosAndRotate
{
        public Vector3 Pos;
        public Quaternion Rot;
        public float Scale;
}
public static Quaternion RotateQ = new Quaternion(180, 90, 0, 0);
```

**Expected behavior**
InvalidCastException: Specified cast is not valid.
ILRuntime.Runtime.Generated.UnityEngine_Quaternion_Binding.CopyToStack_x_0 (System.Object& o, ILRuntime.Runtime.Intepreter.ILIntepreter __intp, ILRuntime.Runtime.Stack.StackObject* __ret, System.Collections.Generic.IList`1[T] __mStack) (at Assets/Dependencies/ILRuntime/Generated/UnityEngine_Quaternion_Binding.cs:145)
ILRuntime.CLR.TypeSystem.CLRType.CopyFieldToStack (System.Int32 hash, System.Object target, ILRuntime.Runtime.Intepreter.ILIntepreter intp, ILRuntime.Runtime.Stack.StackObject*& esp, System.Collections.Generic.IList`1[T] mStack) (at Assets/Dependencies/ILRuntime/ILRuntime/CLR/TypeSystem/CLRType.cs:415)
ILRuntime.Runtime.Intepreter.ILIntepreter.ExecuteR (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/Dependencies/ILRuntime/ILRuntime/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:3086)
Rethrow as ILRuntimeException: Specified cast is not valid.
IL_00bb: ldfld System.Single UnityEngine.Quaternion::x(JIT_0034:ldfld r9, r9, 0x200000145553B800)

**Unity Version**
Unity2020.3.17f1c1

**ILRuntime Version**
Master版本

**Comment by liiir1985** [comment]
能提供能复现问题的用例吗？
