### ISSUE TITLE
ILRuntime PC版本打包无法加载dll文件 System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.

### ISSUE THREAD

**Issue by Frostorder26** [Ourpalm/ILRuntime#635]
ILRuntime PC版本打包无法加载dll文件 System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.

部分电脑打包后无法加载，检查电脑环境信息一致，初使用时打包后加载Dll文件无异常，后面无法加载

Unity版本 2018.4.4    2019.4.33

IL版本2.0
[log.txt](https://github.com/Ourpalm/ILRuntime/files/7792300/log.txt)

**Comment by liiir1985** [comment]
这个意思是加载的dll有问题，建议调用Appdomain接口前检查一下流的长度是否正确

**Comment by Frostorder26** [comment]
已经找到问题，和dll，程序，代码，打包，环境等原因没关系，也和流的长度没关系






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ourpalm/ILRuntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 中午11:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ourpalm/ILRuntime] ILRuntime PC版本打包无法加载dll文件 System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid. (Issue #635)





 
这个意思是加载的dll有问题，建议调用Appdomain接口前检查一下流的长度是否正确
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SpicyWonton** [comment]
> 已经找到问题，和dll，程序，代码，打包，环境等原因没关系，也和流的长度没关系
> […](#)

@Frostorder26 大佬你好，我也遇到了同样的问题，能说下是怎么解决的吗

**Comment by Frostorder26** [comment]
> > 已经找到问题，和dll，程序，代码，打包，环境等原因没关系，也和流的长度没关系
> > […](#)
> 
> [@Frostorder26](https://github.com/Frostorder26) 大佬你好，我也遇到了同样的问题，能说下是怎么解决的吗

我这边的问题是因为文件夹名称，不能出现特殊符号
