### ISSUE TITLE
Dictionary的TryGetValue 如果他的value是个跨域继承的热更类 则在TryGetValue之后访问value的字段报错

### ISSUE THREAD

**Issue by huangjunxiang1** [Ourpalm/ILRuntime#639]
![image](https://user-images.githubusercontent.com/88924054/149275265-2afccc31-0a00-45fb-b140-f33903b4b39c.png) 这个是热更类，
![image](https://user-images.githubusercontent.com/88924054/149275322-ca936fa3-a654-4166-8ce2-1a5b880f0240.png)
这个是测试代码

**Comment by liiir1985** [comment]
在PR #655 中已修复
