### ISSUE TITLE
请问有没有加入类似于XLua的热补丁特性的计划呢？

### ISSUE THREAD

**Issue by jiezuowhu** [Ourpalm/ILRuntime#64]
参见https://github.com/Tencent/xLua/blob/master/Assets/XLua/Doc/hotfix.md，可以在运行时把C#实现（方法，操作符，属性，事件等等）替换成lua实现。原理也就是在函数前面打标签，然后在编译时注入一段判断语句。如果能加入这个特性，ILRuntime的优势一定会更大！

**Comment by liiir1985** [comment]
目前没有这个计划，因为AOP热补丁更新在实际使用中局限性非常大，能够修改的bug及其有限，因此实用性并不是很高
