### ISSUE TITLE
泛型Equals比对有概率会失败     List方法有概率识别错误

### ISSUE THREAD

**Issue by bjlnly** [Ourpalm/ILRuntime#641]
**Describe the bug**
请描述Bug的现象
1.Equals比对失败源码:
失败案例:list比对获取index,根据index去RemoveAt, 然后发现index==-1. 改为Remove未有再复现
```
            var listCount = list.Count;
            for (int i = 0; i <listCount; i++)
                if (list[i].Equals(obj))
                    return i;
```
2.异常错误内容:Unable to cast object of type 'int32' to type 'List`1'
异常代码:
```
        IEnumerator Test()
        {
            while (true)
            {
                int num = 0;
                var statesCount = StateManager.States.Count;
                yield return null;
            }
        }
```
**To Reproduce**
请描述重现步骤或上下文
1.第一个问题比较随机,目前看似乎枚举触发的可能较大;
2.第二个问题,list是多重继承的基类的Field,list的内容是一个自定义基类,怀疑跟这个有关
3.上述两个非必现的问题一旦触发,除非退出apk  否则本次的运行的结果都是一致的错误结果
**Expected behavior**
请描述应有的行为
1. 比对正确返回对应index
2. 不会出现类型匹配错误问题
**Unity Version**
Please fill in the version of Unity you're currently using
请填写使用的Unity版本
2019.4.27f1
**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
请填写使用的ILRuntime版本（package版本或Git提交号或下载日期）
1.607.2

**Comment by liiir1985** [comment]
2.0版有修复过类似的问题，可以尝试一下用新版本该问题是否还可以复现
