### ISSUE TITLE
热更工程调用主工程可空类型 如 int? bool? 报错

### ISSUE THREAD

**Issue by cjhxajh** [Ourpalm/ILRuntime#642]
热更工程调用主工程可空类型 如 int? bool? 报错
已生成CLR绑定

//主工程代码
public class MTest
{
  public int? a;
  public bool? b;
}

//热更工程调用代码
//测试int?
var test1 = new Test();
 test1.a = 22; //能正常赋值
 test1.a = null; //赋值错误 NotImplementedException: The method or operation is not implemented.                   

//测试bool?
var test2 = new Test();
test.b = true;  //赋值错误 InvalidCastException: Specified cast is not valid.

**ILRuntime Version**
ILRuntime2.0.2

**Comment by liiir1985** [comment]
nullable需要生成clr绑定后才能使用
