### ISSUE TITLE
函数调用错误

### ISSUE THREAD

**Issue by goodman8080** [Ourpalm/ILRuntime#646]
**Describe the bug**
跨域继承调用错误
继承关系如下：
CPlugin : MonoBehaviour   ---框架层, CPlugin 生成了Adaptor
CCommon:CPlugin    --应用层

CPluginAdaptor.Adaptor中实现了 OnApplicationFocus(bool bifFocus) 函数
            CrossBindingMethodInfo<bool> mOnApplicationFocus_37 = new CrossBindingMethodInfo<bool>("OnApplicationFocus");
            public void OnApplicationFocus(bool bIfFocus)
            {
                mOnApplicationFocus_37.Invoke(this.instance, bIfFocus);
            }

运行后发现如下错误
NotSupportedException: Cannot invoke CLRMethod
ILRuntime.Runtime.Enviorment.AppDomain.BeginInvoke (ILRuntime.CLR.Method.IMethod m) (at Assets/ILRuntime/ILRuntime/Runtime/Enviorment/AppDomain.cs:1517)
ILRuntime.Runtime.Enviorment.CrossBindingMethodInfo`1[T].Invoke (ILRuntime.Runtime.Intepreter.ILTypeInstance instance, T arg) (at Assets/ILRuntime/ILRuntime/Runtime/Enviorment/CrossBindingMethodInfo.cs:658)
ILRuntime.Runtime.Generated.PluginAdaptor+Adaptor.OnApplicationFocus (System.Boolean bIfFocus) (at Assets/ILRuntime/ILRuntime/AdaptorList/PluginAdaptor.cs:464)
UnityEditorInternal.InternalEditorUtility:OnGameViewFocus(Boolean)
UnityEditor.HostView:OnLostFocus()

**Unity Version**
unity 2021.2.2f1

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
ILRunTime 2.02

**Comment by liiir1985** [comment]
OnApplicationFocus 既不是virtual也不是abstract，无法通过 CrossBindingMethodInfo 桥接
