### ISSUE TITLE
开启寄存器模式后，运行报错，关闭能正常运行，大神们进来指点下哇

### ISSUE THREAD

**Issue by hina90** [Ourpalm/ILRuntime#647]
开启寄存器模式后： appdomain = new ILRuntime.Runtime.Enviorment.AppDomain(ILRuntimeJITFlags.JITOnDemand);

调用过程如下：

函数：
public T GetDatabase<T>() where T : IDatabase, new()
{
	T result = new T();
          if (m_Databases.ContainsKey(result.TypeID()))
	{
              return (T)m_Databases[result.TypeID()];
	}
	return default(T);
}
外部调用上面函数：
ConfigDataManager.Instance.GetDatabase<AbilityopenDatabase>();

然后报错：
执行以下代码会报错：NullReferenceException: Object reference not set to an instance of an object.
ILRuntime.Runtime.Intepreter.ILIntepreter.ExecuteR (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Library/PackageCache/com.ourpalm.ilruntime@2.0.2/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:3955)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <67bbede196d54d91bb0ca9922511a90c>:0)

另外：
appdomain = new ILRuntime.Runtime.Enviorment.AppDomain(ILRuntimeJITFlags.None);
或者
appdomain = new ILRuntime.Runtime.Enviorment.AppDomain(ILRuntimeJITFlags.NoJIT);

可以正常运行

请问这是什么问题造成的呢，哪位大神指点下

**Unity Version**
2020.3.14

**ILRuntime Version**
2.0.2

**Comment by liiir1985** [comment]
跟 #648 应该是同一个问题，跟泛型约束有关，我近期看一下

**Comment by hina90** [comment]
> 好的，近期刚从1.6 换到 2.0.2  就是想用下这个寄存模式的复杂运算优化，结果就遇到这个问题，坐等大神更新

**Comment by liiir1985** [comment]
> 

你可以对需要复杂运算优化的方法或者类型上标注ILRuntimeJIT标签来仅启用那个类型或方法的jit，缩小影响范围。 详细方法可以看文档

**Comment by hina90** [comment]
> 你可以对需要复杂运算优化的方法或者类型上标注ILRuntimeJIT标签来仅启用那个类型或方法的jit，缩小影响范围。 详细方法可以看文档

试过了，在主工程没问题，但是很多需要优化的update是在热更工程里的，热更工程 加不了这个标签，原因是引用不了，我把IlRuntime plugin里的dll  拷贝到热更工程里引用后还是 不能引用这个标签呢，哪里有问题吗？

**Comment by liiir1985** [comment]
如果你是用的vs工程编译热更dll，引用里添加ILRuntime.dll就可以打那个标签了

**Comment by hina90** [comment]
> 如果你是用的vs工程编译热更dll，引用里添加ILRuntime.dll就可以打那个标签了

好的，感谢大神解答~

**Comment by hina90** [comment]
> 如果你是用的vs工程编译热更dll，引用里添加ILRuntime.dll就可以打那个标签了

已经OK了，最后还想请教个问题，B类继承了A类，jit的标签是放在父类里就可以让所有的继承类的update方法生效吗？ 还是必须在每个子类的update的方法上都打标签呢？

**Comment by liiir1985** [comment]
如果是virtual的那是需要在子类上标的
另外其实Update自身不算计算密集型， 要看代码里做了些什么，大型for循环加各种加减乘除才是优化对象
如果update里只是调了下unityapi， 那并不会产生什么优化

**Comment by hina90** [comment]
> 如果是virtual的那是需要在子类上标的 另外其实Update自身不算计算密集型， 要看代码里做了些什么，大型for循环加各种加减乘除才是优化对象 如果update里只是调了下unityapi， 那并不会产生什么优化

了解，再次感谢大神~
