### ISSUE TITLE
请求增加自定义异常处理

### ISSUE THREAD

**Issue by lanchong101** [Ourpalm/ILRuntime#649]
**Describe the bug**
在使用自定义异常类型时，会抛出 NotImplementedException

**To Reproduce**
请描述重现步骤或上下文
1. 任意自定义异常

**Expected behavior**
请描述应有的行为

**Unity Version**
Please fill in the version of Unity you're currently using
请填写使用的Unity版本

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
1.6.7

**Comment by liiir1985** [comment]
自定义异常类型是支持的，请提供具体的错误信息？
