### ISSUE TITLE
ilruntime 在 webgL上 async ,Task<T>不能同时使用

### ISSUE THREAD

**Issue by zyq20130111** [Ourpalm/ILRuntime#652]
在WebGl平台里出现如下问题，步骤如下

1.热更DLL中定义下列函数
        public static async Task<T> SendMessgeAsync<T>(IMessage msg) where T: class, IMessage
        {
            var obj = await SendAsync(msg);
            return obj as T;
        }
2.然后调用
HandshakeResp handshakeResp = await NetModule.SendMessgeAsync(gateHandshake) as HandshakeResp;
后报错如下
![image](https://user-images.githubusercontent.com/19948772/151645571-42006e2b-77bf-4b11-a3f5-008b41e34a20.png)

**Comment by liiir1985** [comment]
webgl平台为何需要用ilruntime？ 不是很懂，不是js文件吗，直接就能热更吧

**Comment by chaoslife** [comment]
主要是多平台代码一致性的考虑吧，而且WebGL打包时间比较久。
我们现在是ios android uwp pc webgl同一套lua，也是想转ILR能不能也使用同一套，不知能否支持

**Comment by chaoslife** [comment]
主要是多平台代码一致性的考虑吧，而且WebGL打包时间比较久。
我们现在是ios android uwp pc webgl同一套lua，也是想转ILR能不能也使用同一套，不知能否支持

**Comment by liiir1985** [comment]
从你的错误截图来说是webgl的c#运行时缺少了某些核心的功能GetGenericMethodDefinition这个方法无法使用，这种就属于平台限制了，只能绕开
