### ISSUE TITLE
JITCompiler:Compile重复添加Key值

### ISSUE THREAD

**Issue by jtabibito** [Ourpalm/ILRuntime#656]
ArgumentException: An item with the same key has already been added. Key: 0
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <e1319b7195c343e79b385cd3aa43f5dc>:0)
ILRuntime.Runtime.Intepreter.RegisterVM.JITCompiler.Compile (System.Int32& stackRegisterCnt, System.Collections.Generic.Dictionary`2[System.Int32,System.Int32[]]& switchTargets, System.Collections.Generic.Dictionary`2[TKey,TValue] addr, System.Collections.Generic.Dictionary`2[System.Int32,ILRuntime.Runtime.Intepreter.RegisterVM.RegisterVMSymbol]& symbols) (at Assets/ThirdParty/ILRuntime/ILRuntime/Runtime/Intepreter/RegisterVM/JITCompiler.cs:295)
ILRuntime.CLR.Method.ILMethod.InitCodeBody (System.Boolean register) (at Assets/ThirdParty/ILRuntime/ILRuntime/CLR/Method/ILMethod.cs:541)
ILRuntime.CLR.Method.ILMethod.get_BodyRegister () (at Assets/ThirdParty/ILRuntime/ILRuntime/CLR/Method/ILMethod.cs:297)
ILRuntime.Runtime.Intepreter.ILIntepreter.ExecuteR (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ThirdParty/ILRuntime/ILRuntime/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:86)
ILRuntime.Runtime.Intepreter.ILIntepreter.ExecuteR (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ThirdParty/ILRuntime/ILRuntime/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:2864)

可以确定的问题是多线程重复调用相同方法时，线程正在处理的ILMethod会出现内存引用问题。
![1644462376(1)](https://user-images.githubusercontent.com/34726874/153329522-789acf57-e4f4-4b1d-b436-1ec48ce2d524.jpg)

**ILRuntime Version**
ILRuntime2.0.2

**Comment by jtabibito** [comment]
我的临时解决方案是在DoJob对ILMethod.InitCodeBody()处理结束前保持对jobs加锁

**Comment by liiir1985** [comment]
ILRuntime不是严格线程安全的，如需多线程访问同1方法，需要提前使用appdomain.Prewarm方法对涉及的类型和方法预热，你即便再这个地方加锁，也会在其他地方遇到概率性的问题
