### ISSUE TITLE
[Wanna] ILDebugger For Visual Studio 2022

### ISSUE THREAD

**Issue by AshaSalorina** [Ourpalm/ILRuntime#661]
望提供调试连接器对vs2022（核心编辑器17.0.*）的支持
我有尝试直接切换项目目标版本进行编译，但是会出现xaml绑定错误。没有做过编辑器拓展，不是很了解问题原因（代码无报错，运行出错）

**Comment by AshaSalorina** [comment]
折腾了老半天，更新项目依赖后调整了一下引用，似乎能正常工作了，不清楚会不会有什么奇怪的问题。
大体流程如下：
1. 所有项目目标框架更换为4.,7.2
2. 把debugluncher的工程输出改为核心[16.0, 18.0]，目标改为社区版17.0 （这里直接选好用默认就行，2022必须要求x86和amd64明确指定，这里是都指定了）
3. 通过nuget更新程序依赖包到最新版本（部分包会更新失败，不用管，通过第四步来解决）
4. 手动调整debugluncher项目的引用，将3中更新失败的依赖（似乎是微软的锅，有个分析器没有写兼容，无法自动更新）和所有同名但版本号不同的引用改为只保留最新版本 
5. 输出release版本即可

**Comment by JohnSmithCloned** [comment]
> 折腾了老半天，更新项目依赖后调整了一下引用，似乎能正常工作了，不清楚会不会有什么奇怪的问题。 大体流程如下：
> 
> 1. 所有项目目标框架更换为4.,7.2
> 2. 把debugluncher的工程输出改为核心[16.0, 18.0]，目标改为社区版17.0 （这里直接选好用默认就行，2022必须要求x86和amd64明确指定，这里是都指定了）
> 3. 通过nuget更新程序依赖包到最新版本（部分包会更新失败，不用管，通过第四步来解决）
> 4. 手动调整debugluncher项目的引用，将3中更新失败的依赖（似乎是微软的锅，有个分析器没有写兼容，无法自动更新）和所有同名但版本号不同的引用改为只保留最新版本
> 5. 输出release版本即可

求编译出来的成品 谢谢大佬 (伸手)
