### ISSUE TITLE
能否开发一个osx系统上可用的debugger插件

### ISSUE THREAD

**Issue by SidneyZhou** [Ourpalm/ILRuntime#666]
现在debugger插件只有vs版本，且只能用在win系统上，可否开发一个适配vs for mac的插件，或者其他跨平台IDE的插件？

**Comment by liiir1985** [comment]
有VS Code调试插件的计划，不过暂时没ETA

**Comment by ckcfcc** [comment]
mac上用rider的比较多，可否考虑支持rider

**Comment by liiir1985** [comment]
rider没有调试器插件的开发文档或示例因此并不知道如何开发

另外VSCode的调试插件已上架vscode插件市场，需配合最新master版使用
