### ISSUE TITLE
如何让热更工程支持unity内置宏比如 UNITY_EDITOR

### ISSUE THREAD

**Issue by diyigeng** [Ourpalm/ILRuntime#667]
**Describe the bug**
在热更工程中不能用UNITY内置宏吗？

**Comment by liiir1985** [comment]
vs里修改热更工程的工程设置，里面预编译宏可以自行定义需要的Unity宏，也可以在打包脚本里调用MSBuild之类命令行编译命令时根据平台指定需要的宏
