### ISSUE TITLE
ILRuntime可以用在MAUI上吗？

### ISSUE THREAD

**Issue by StarkShang** [Ourpalm/ILRuntime#670]
在MAUI项目中使用ILRuntime，可以调用dll中的代码，但是创建MAUI的页面时会出现报错：

> Exception has been thrown by the target of an invocation.

**Comment by liiir1985** [comment]
ILRuntime并没有限定运行时，可以在unity也可以在.net core或者其他c#环境，请确保先过一遍文档和unity的实例代码工程。报错不知道为什么的话请发完整错误不要只发个message
