### ISSUE TITLE
两个正的长整数执行除法以后可能出现负数

### ISSUE THREAD

**Issue by ZHOURUIH** [Ourpalm/ILRuntime#675]
**Describe the bug**
两个正的长整数执行除法以后可能出现负数

**To Reproduce**
public static void setExp(long exp, long maxExp)
{
  float percent = (float)exp / maxExp;
  Debug.Log("maxExp:" + maxExp + ",exp:" + exp + ", exp / maxExp:" + percent);
}
// 在任意热更工程中添加上述代码,然后调用此函数,setExp(20176515, 2400000000);
// 打印结果maxExp:2400000000,exp:20176515, exp / maxExp:0.008406881

**Expected behavior**
在普通的C#中是正数

**Unity Version**
2020.3.23f1

**ILRuntime Version**
2022.3.21早上1点下载

**Comment by ZHOURUIH** [comment]
打印结果那里粘贴错了,粘贴的是对的结果

**Comment by ZHOURUIH** [comment]
追踪堆栈看起来像是取函数参数的时候就已经是int了,本来应该是long

**Comment by liiir1985** [comment]
在master和Demo工程均无法重现
