### ISSUE TITLE
更新最新git库2.0.2，使用调试功能弹窗“Cannot connect to ILRuntime”

### ISSUE THREAD

**Issue by d3dx9meng** [Ourpalm/ILRuntime#687]
更新最新git库2.0.2，使用调试功能弹窗“Cannot connect to ILRuntime”

把unity Demo(ILRuntimeU3D-master.zip)里的IL类库拷贝过去，才能可以调试了
类库里面的文件修改时间为2020.1.3
环境：
Unity2019.3.30f1
VS 2019 Community
ILRuntime 2.0.2最新代码 (Debugger: ILRuntimeDebuggerLauncher)

**Comment by liiir1985** [comment]
目前master上的代码为2.1.0-beta版， 由于调试协议已经变更，如果需要调试最新版需要自行编译最新调试器插件，或等待2.1.0正式版发布，应该在4月内会发布

**Comment by d3dx9meng** [comment]
好的，明白了，等2.1.0发布了我再更新一下
