### ISSUE TITLE
热更类同时实现热更接口和主工程接口在特定情况下报异常

### ISSUE THREAD

**Issue by tinysnake** [Ourpalm/ILRuntime#693]
**Describe the bug**
当一个类`X`实现了热更接口`H`和主工程接口`M`时，如果在热更代码里往`List<H>`添加`X`实例将会报InvalidCastException。

**To Reproduce**
当前有2个类：
```
// 热更接口
public interface IMainInterface {}

// 主工程接口
public interface IHotfixInterface {}

// 实现类
public class TestClass : IMainInterface, IHotfixInterface
{
}

// IMainInterfaceAdapter代码省略

// 执行代码
public static void RunTest()
{
    var tc = new TestClass();
    var list = new System.Collections.Generic.List<IHotfixInterface>();
    list.Add(tc); // throws InvalidCastException here.
}
```

上懒人包：
[Assets.zip](https://github.com/Ourpalm/ILRuntime/files/8552306/Assets.zip)
关键代码：
```
Assets/Lib/ITestInterface.cs
Assets/Hotfix/IHotfixInterface.cs
Assets/Hotfix/TestClass.cs
Assets/Lib/Adapters/ITestInterfaceAdapter.cs
Assets/Scripts/HotfixRunner.cs
```
进入`Assets/Scenes/SampleScene.unity`运行即可复现bug。

**Expected behavior**
运行如预期

**Unity Version**: 2019.4

**ILRuntime Version**: 2.0.2

**Comment by liiir1985** [comment]
如果跨域继承，容器类只能接受该类继承的第一个主工程类作为泛型参数，其他都不行，这个属于跨域继承的限制
