### ISSUE TITLE
注册委托的问题

### ISSUE THREAD

**Issue by jiezuowhu** [Ourpalm/ILRuntime#70]
请问这个appDomain.DelegateManager.RegisterMethodDelegate<int, float>();委托的注册可以放到热更的DLL中么。
从泛型函数的角度来讲，原理上应该是不可以的啊。但是我测试了下，好像也没什么问题。所以想了解下这个是否真的可以。谢谢

**Comment by liiir1985** [comment]
appdomain下的注册函数都必须在主工程调用，不能在热更中调用，因为这些注册本来的意义就是为了避免IL2CPP剪裁

**Comment by jiezuowhu** [comment]
但是我测试了，放到热更中调用运行起来也是没问题的（IOS端）。所以就有点搞不懂了

**Comment by liiir1985** [comment]
ILRuntime强制需要你注册这个并不是因为ILRuntime需要，而是为了预防IL2CPP剪裁导致开发期没发现但是发布之后出现问题。 你在ILRuntime里面进行注册仅仅是绕开了ILRuntime的检测，并不能起到让il2cpp保留类型的作用， 也许你项目其他地方用到了这个类型，所以被il2cpp保留了，但是并不能保证一定没问题
