### ISSUE TITLE
OnApplicationQuit調用問題

### ISSUE THREAD

**Issue by juicefish** [Ourpalm/ILRuntime#700]
Unity主工程中調用Application.Quit() 
然後在主工程上MonoBehaviour的OnApplicationQuit中透過ILRuntime的接口調用函數
導致 App Freeze 

預期可以正常結束App後 讓使用者點App可以重新啟用App

僅在iOS真機上會重現
Android真機沒有影響

Unity Version  2020.3.29f1
ILRuntime 2.0.2 異常
ILRuntime 1.6.6 可以正常Quit
XCode 13.2.1

**Comment by liiir1985** [comment]
需要在OnApplicationQuit中执行完毕后，调用AppDomain的.Dispose销毁后台线程
