### ISSUE TITLE
不重启Unity更新ILRuntime逻辑

### ISSUE THREAD

**Issue by jimmmmmmmmmyfunnnnnnny** [Ourpalm/ILRuntime#701]
怎么不重启Unity更新ILRuntime逻辑

**Comment by liiir1985** [comment]
新new 一个appdomain，老的等gc

**Comment by jimmmmmmmmmyfunnnnnnny** [comment]
老的appdomain里面的数值没有转移到new出来的新的这边，会引起一堆bug。怎么把旧appdomain里的内存数值转移到新new出来的appdomain？
