### ISSUE TITLE
如何在pc上应用ILRunTime?

### ISSUE THREAD

**Issue by zangputi** [Ourpalm/ILRuntime#704]
如题

**Comment by wenbingzhang** [comment]
https://ourpalm.github.io/ILRuntime/public/v1/guide/tutorial.html  找到“从Visual Studio开始”

**Comment by yogioh123456** [comment]
PC直接加载dll就行了吧

**Comment by liiir1985** [comment]
ILRuntime在不同平台上的使用并没有什么不同
