### ISSUE TITLE
特殊情况下报Cannot find ValueTypeBinder for type:UnityEngine.Vector3异常

### ISSUE THREAD

**Issue by liyimin289324** [Ourpalm/ILRuntime#708]
**Describe the bug**

报错：Cannot find ValueTypeBinder for type:UnityEngine.Vector3
Vector3Binder 都有注册 但还是会报这个错

**To Reproduce**

1. 运行unity，点击模型
2. 按键盘'A'
3. 报错Cannot find ValueTypeBinder for type:UnityEngine.Vector3
4. ModelOperater.cs   Camera.main.transform.DOMove(ModelManager.Instance.SingleShowCameraPos, duration);
5. hotfix_program path:Assets/ETconfigLoader/Hotfix/HotFix_Project~

**Expected behavior**
不应该有报错

**Unity Version**
Please fill in the version of Unity you're currently using
2019.4.6f1

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
Version2.0.2  January 04,2022
qq_1126024346

**Comment by liyimin289324** [comment]
[_ATUnityCopy.zip](https://github.com/Ourpalm/ILRuntime/files/8883116/_ATUnityCopy.zip)

**Comment by liyimin289324** [comment]
经过测试发现

**Comment by liiir1985** [comment]
该例子中并没有运行注册Vector3Binder的代码，且CLRBinding的初始化时机有误。CLRBinding.Initialize需要在所有初始化操作完毕后最后执行，其他初始化操作也应当在加载热更DLL之后进行
