### ISSUE TITLE
使用github上的ILRuntime生成2022调试器报错。

### ISSUE THREAD

**Issue by jimmmmmmmmmyfunnnnnnny** [Ourpalm/ILRuntime#711]
使用的Visiual Studio2022的版本
![9U9J~ABA))KO@{WFPDO4~@X](https://user-images.githubusercontent.com/26768352/176161190-d000a67a-dd43-44c3-9e10-ebd64b1be07c.png)

报错截图
![%)K`P5QU7U)OL5WV4AHJR@W](https://user-images.githubusercontent.com/26768352/176161283-85a9fa3d-8e0d-46c5-ba30-447e2ec0c194.png)

报错卡住编辑器然后闪退了。

**Comment by liiir1985** [comment]
ILRuntime运行时也需要用最新的master版或者2.1.0-preview.1以上版本
