### ISSUE TITLE
没有办法在VS2022上面安装ILRuntime Debugger，在VS2022拓展里面搜索的ILRuntime Debugger版本与调试版本不一致，无法调试

### ISSUE THREAD

**Issue by MainLiyulong** [Ourpalm/ILRuntime#716]
**Describe the bug**
请描述Bug的现象

**To Reproduce**
请描述重现步骤或上下文

**Expected behavior**
请描述应有的行为

**Unity Version**
Please fill in the version of Unity you're currently using
请填写使用的Unity版本

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
请填写使用的ILRuntime版本（package版本或Git提交号或下载日期）

**Comment by JiekeZhu** [comment]
可以自己下载源码，编译所有相关的库，调试插件。我这边，自己编译出的插件，在Visual Sutido Preview 2022上都可以正常工作。

**Comment by liiir1985** [comment]
VS商店中的插件需要配合当前master最新运行时，或者npm源的2.1.0-preview以上版本
