### ISSUE TITLE
寄存器模式下，list.sort函数中用值类型比较产生报错

### ISSUE THREAD

**Issue by XingHong** [Ourpalm/ILRuntime#717]
**问题描述**
在寄存器模式下，hotfix调用list.sort函数，如果比较的类中的值类型，发生报错，如下图：

**图1**
![20220718163617](https://user-images.githubusercontent.com/4038425/179474256-408f40d8-c532-4954-80d5-87809b944ef1.png)

**添加的测试代码**
hotfix中，在TestValueType中添加了RunTest4；  
主工程中，修改了ValueTypeBindingDemo，让它可以调用hotfix中的RunTest4，并且添加新的值类型structs和对应的值类型绑定代码（在文件夹11_ValueTypeBinding中）

**重现步骤:**
打开11_ValueTypeBinding.unity运行即可  
不太确定是绑定代码的问题还是其它问题，不过在非寄存器模式下运行是不会报错的。

**Unity Version**
2020.3.32f1

**ILRuntime Version**
2.1.0-preview.1
**已经构建好项目**
[NewILruntime.zip](https://github.com/Ourpalm/ILRuntime/files/9130520/NewILruntime.zip)

**Comment by liiir1985** [comment]
测试用例中的Fixed64Binder写的有问题，NewFixed64方法内栈不平衡
