### ISSUE TITLE
JIT模式下引用变量值错误

### ISSUE THREAD

**Issue by corinegy** [Ourpalm/ILRuntime#721]
Describe the bug
JIT模式下引用变量值错误

public static void Set(ref long x)
{
  x++;
}

public static void StaticFunTest()
{
  long srcX = 10;

  for (var index = 0; index < 10; index++)
  {
    long x = srcX;

    UnityEngine.Debug.Log(x);

    Set(ref x);
  }
}

预期:log为 10 10 10 10...
实际:log为 10 11 12 13...

Unity Version
2020.3.27

ILRuntime Version
2.0.2

**Comment by liiir1985** [comment]
已修复
