### ISSUE TITLE
开启按需JIT模式后有些方法被编译成寄存器代码后报错 目测是Vector3 的normalized方法出现问题

### ISSUE THREAD

**Issue by z1293271436** [Ourpalm/ILRuntime#722]
**Describe the bug**
请描述Bug的现象

**To Reproduce**
请描述重现步骤或上下文

**Expected behavior**
![image](https://user-images.githubusercontent.com/37893466/181159316-ff3c7717-f154-4732-828d-0336b449414b.png)
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.List`1[T].set_Item (System.Int32 index, T value) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
ILRuntime.Runtime.Intepreter.ILIntepreter.CopyToRegister (ILRuntime.Runtime.Intepreter.RegisterFrameInfo& info, System.Int16 reg, ILRuntime.Runtime.Stack.StackObject* val, System.Collections.Generic.List`1[T] mStackSrc) (at Assets/Wwj/Plugins/ILRuntime/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:5494)
ILRuntime.Runtime.Intepreter.ILTypeInstance.CopyToRegister (System.Int32 fieldIdx, ILRuntime.Runtime.Intepreter.RegisterFrameInfo& info, System.Int16 reg) (at Assets/Wwj/Plugins/ILRuntime/Runtime/Intepreter/ILTypeInstance.cs:462)
ILRuntime.Runtime.Intepreter.ILIntepreter.ExecuteR (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/Wwj/Plugins/ILRuntime/Runtime/Intepreter/RegisterVM/ILIntepreter.Register.cs:3120)
Rethrow as ILRuntimeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
IL_007b: ldfld UnityEngine.Vector3 Game.Role/<>c__DisplayClass41_0::myPosition(JIT_0024:ldfld r10, r3, 0x1000033D00000002)
Game.Role.MoveToTarget(Game.Role target, System.Action afterCall) (at Assets/script/component/Battle/Role.cs:397)
BattleInstance/<>c__DisplayClass55_0.<ReadBattleDataNotify>b__0() (at Assets/script/component/Battle/BattleInstance.cs:424)
BattleInstance.SkillCastEffect(PlanTable.Magic skill, UnityEngine.Vector3 castRole, System.Action endAction) (at Assets/script/component/Battle/BattleInstance.cs:575)
BattleInstance.ReadBattleDataNotify(LogicSer.BattleRoundData data) (at Assets/script/component/Battle/BattleInstance.cs:409)
BattleInstance.BattleUpdate() (at Assets/script/component/Battle/BattleInstance.cs:340)
BattleInstance/<>c__DisplayClass45_0.<InitState>b__3(TaskHelper+GameTaskCell _) (at Assets/script/component/Battle/BattleInstance.cs:278)
IL_007b: ldfld UnityEngine.Vector3 Game.Role/<>c__DisplayClass41_0::myPosition(JIT_0024:ldfld r10, r3, 0x1000033D00000002)
Game.Role.MoveToTarget(Game.Role target, System.Action afterCall) (at Assets/script/component/Battle/Role.cs:397)
BattleInstance/<>c__DisplayClass55_0.<ReadBattleDataNotify>b__0() (at Assets/script/component/Battle/BattleInstance.cs:424)
BattleInstance.SkillCastEffect(PlanTable.Magic skill, UnityEngine.Vector3 castRole, System.Action endAction) (at Assets/script/component/Battle/BattleInstance.cs:575)
BattleInstance.ReadBattleDataNotify(LogicSer.BattleRoundData data) (at Assets/script/component/Battle/BattleInstance.cs:409)
BattleInstance.BattleUpdate() (at Assets/script/component/Battle/BattleInstance.cs:340)
BattleInstance/<>c__DisplayClass45_0.<InitState>b__3(TaskHelper+GameTaskCell _) (at Assets/script/component/Battle/BattleInstance.cs:278)
Rethrow as ILRuntimeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
IL_007b: ldfld UnityEngine.Vector3 Game.Role/<>c__DisplayClass41_0::myPosition(JIT_0024:ldfld r10, r3, 0x1000033D00000002)
Game.Role.MoveToTarget(Game.Role target, System.Action afterCall) (at Assets/script/component/Battle/Role.cs:397)
BattleInstance/<>c__DisplayClass55_0.<ReadBattleDataNotify>b__0() (at Assets/script/component/Battle/BattleInstance.cs:424)
BattleInstance.SkillCastEffect(PlanTable.Magic skill, UnityEngine.Vector3 castRole, System.Action endAction) (at Assets/script/component/Battle/BattleInstance.cs:575)
BattleInstance.ReadBattleDataNotify(LogicSer.BattleRoundData data) (at Assets/script/component/Battle/BattleInstance.cs:409)
BattleInstance.BattleUpdate() (at Assets/script/component/Battle/BattleInstance.cs:340)
BattleInstance/<>c__DisplayClass45_0.<InitState>b__3(TaskHelper+GameTaskCell _) (at Assets/script/component/Battle/BattleInstance.cs:278)
IL_007b: ldfld UnityEngine.Vector3 Game.Role/<>c__DisplayClass41_0::myPosition(JIT_0024:ldfld r10, r3, 0x1000033D00000002)
Game.Role.MoveToTarget(Game.Role target, System.Action afterCall) (at Assets/script/component/Battle/Role.cs:397)
BattleInstance/<>c__DisplayClass55_0.<ReadBattleDataNotify>b__0() (at Assets/script/component/Battle/BattleInstance.cs:424)
BattleInstance.SkillCastEffect(PlanTable.Magic skill, UnityEngine.Vector3 castRole, System.Action endAction) (at Assets/script/component/Battle/BattleInstance.cs:575)
BattleInstance.ReadBattleDataNotify(LogicSer.BattleRoundData data) (at Assets/script/component/Battle/BattleInstance.cs:409)
BattleInstance.BattleUpdate() (at Assets/script/component/Battle/BattleInstance.cs:340)
BattleInstance/<>c__DisplayClass45_0.<InitState>b__3(TaskHelper+GameTaskCell _) (at Assets/script/component/Battle/BattleInstance.cs:278)
IL_007b: ldfld UnityEngine.Vector3 Game.Role/<>c__DisplayClass41_0::myPosition(JIT_0024:ldfld r10, r3, 0x1000033D00000002)
Game.Role.MoveToTarget(Game.Role target, System.Action afterCall) (at Assets/script/component/Battle/Role.cs:397)
BattleInstance/<>c__DisplayClass55_0.<ReadBattleDataNotify>b__0() (at Assets/script/component/Battle/BattleInstance.cs:424)
BattleInstance.SkillCastEffect(PlanTable.Magic skill, UnityEngine.Vector3 castRole, System.Action endAction) (at Assets/script/component/Battle/BattleInstance.cs:575)
BattleInstance.ReadBattleDataNotify(LogicSer.BattleRoundData data) (at Assets/script/component/Battle/BattleInstance.cs:409)
BattleInstance.BattleUpdate() (at Assets/script/component/Battle/BattleInstance.cs:340)
BattleInstance/<>c__DisplayClass45_0.<InitState>b__3(TaskHelper+GameTaskCell _) (at Assets/script/component/Battle/BattleInstance.cs:278)

**Unity Version**
Please fill in the version of Unity you're currently using
2019

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
2.0.2

**Comment by z1293271436** [comment]
![image](https://user-images.githubusercontent.com/37893466/181159204-f104ffe5-df47-44ad-b134-cad598acfc45.png)

**Comment by liiir1985** [comment]
最近修复了几个registervm的bug，可以试试master版还能否重现，如果还能重现的话再重新打开该Issue
