### ISSUE TITLE
CLR绑定代码在PC真机Mono环境下运行游戏会闪退

### ISSUE THREAD

**Issue by hongyouzi** [Ourpalm/ILRuntime#727]
**Describe the bug**
使用ILRuntime.Other.UncheckedList<object>集合的CLR绑定代码在PC真机环境下运行会闪退。
1、测试下来若添加CLR绑定代码，用mono环境打包会闪退，IL2CPP不会。
![image](https://user-images.githubusercontent.com/10858461/189018518-d548e115-c1a4-45b3-9553-90211519533a.png)
2、若在mono环境下，删除CLR绑定代码在PC真机上运行，也不会闪退。

**Unity Version**
Unity2018.4.36

**ILRuntime Version**
 Aug 5, 2022  075a4805251f6c5bbe59f6398d7e4ac9160fdd16

**Comment by liiir1985** [comment]
这个一般都是Unity自己的bug导致的，要么尝试升级unity版本，要么使用IL2CPP来打包（使用mono的话可以直接使用Assembly.Load，不需要使用ilruntime）
