### ISSUE TITLE
有时候的报错是报错在插件脚本里的，无法快速定位错误是哪个脚本哪行代码造成的？有什么技巧吗？

### ISSUE THREAD

**Issue by hina90** [Ourpalm/ILRuntime#728]
**Describe the bug**
1.ILRuntime 有时候报错的报错无法定位的问题，请问有什么好的技巧可以节省定位错误的时间吗？比如下图这种错误，只有靠到处加打印试着定位错误。
2.尝试在ILRuntime的插件脚本里 加try catch 打印  结果保存运行后，没打印，最后发现插件脚本把代码还原了，修改不了插件代码。

![1](https://user-images.githubusercontent.com/20185862/190857915-f0672e97-61ce-4cb6-97b9-fc873b8060d4.png)
#
希望能帮助快速定位错误。

**Unity Version** 
2020.3.21f

**ILRuntime Version**
 2.0.2

**Comment by liiir1985** [comment]
正常情况是会打印热更内栈的，如果没有只有3种情况
1、打印错误时只取了ex.StackTrace，正确的打印方式为ex.ToString()
2、async void方法默认没打印热更内栈是unity没按约定输出日志导致的，暂时没有很好的办法，只有在async方法内自己try catch
3、热更内try catch的话，需要通过ex.Data["StackTrace"]和ex.Data["Message"]来取错误信息和热更内栈
