### ISSUE TITLE
有人做过这个RegisterFunctionDelegate自动生成工具嘛

### ISSUE THREAD

**Issue by VkingLangzi** [Ourpalm/ILRuntime#749]
![E5KYCFH{0XB6FLYZ1CUY RL](https://user-images.githubusercontent.com/33446085/226170064-1828619b-4088-4368-9936-d3f3a87105c1.jpg)
感觉这一块可以自动化呀，老板当时没有考虑做自动化，是有考虑什么难点或者风险不。我计划搞一个，但是怕走弯路，搞之前先请教一下。

**Comment by liiir1985** [comment]
没做自动化的主要原因是因为不是所有委托调用都需要，如果全量注册会有一些运行时overhead（几乎每次创建委托都会产生）。外加上这个列表随着项目开发进程进行，最后需要新增的频率会越来越低，项目后期基本几个月都不会新增一条，这种情况下可以维持一个平衡，上线后即便用到一些之前没用到的，也可以通过实现注册几个<object,object,object>之类的万能类型绕过
