### ISSUE TITLE
泛型类绑定不了？？？

### ISSUE THREAD

**Issue by SunHailang** [Ourpalm/ILRuntime#754]
大佬们，ILRuntime 泛型类怎么绑定？ 
`appdomain.RegisterCrossBindingAdaptor <IType>(new XXXX<IType>);`无法支持

**Comment by liiir1985** [comment]
泛型跨域继承的话，就是把泛型参数T替换成具体的类型，每个不同的T都需要独立绑定。 如果T是一个热更内的类型（没有跨域继承的情况下），则可以直接使用ILTypeInstance代替全部
