### ISSUE TITLE
疑问: 是否支持运行时 c# 生成 IL ？

### ISSUE THREAD

**Issue by sesky4** [Ourpalm/ILRuntime#755]
Hi, 感谢你们开源 ILRuntime❤️ 

我有一个使用场景，是运行时支持在 ios 客户端(不支持 jit )编辑代码并 reload。

因此需要:
1.运行时将 c# 代码字符串生成 dll 并交由 ILRuntime 执行
2.运行时将 c# 代码字符串生成 IL 并交由 ILRuntime 执行

在文档中似乎没有提及类似场景，不知道 ILRuntime 是否支持这样的功能？或者有没有相关想法？

谢谢

**Comment by liiir1985** [comment]
ILRuntime本身并不包含C#编译器，但是你可以使用其他C#编译器库实现这样的功能，比如微软官方的C#编译器，Rosyln，就是开源的，可以直接在运行时生成dll然后塞给ILRuntime，这样是没问题的
