### ISSUE TITLE
可空类型不生成clr绑定的情况下以下代码会报错

### ISSUE THREAD

**Issue by fujisheng** [Ourpalm/ILRuntime#756]
![image](https://user-images.githubusercontent.com/24699142/233932141-e0af0f53-8121-4aba-b100-6c52de03db0b.png)
![image](https://user-images.githubusercontent.com/24699142/233932216-eaba9ee4-018c-4fb2-b7af-1e0793b5c2bd.png)

**Comment by xushunwang** [comment]
就是不支持的

**Comment by liiir1985** [comment]
可空类型必须生成绑定后才能正常工作
