### ISSUE TITLE
在一个表达式多次使用‘?.’操作符时，会有不稳定的情况

### ISSUE THREAD

**Issue by xueyan123** [Ourpalm/ILRuntime#760]
不完全支持可空值类型，但是在一个表达式多次使用‘?.’操作符时，会有不稳定的情况
例如：
private class Testaa
{
    public int value;

    public Testbb testbb;

    public GameObject GetGO()
    {
        return null;
    }

    public Testbb GetBb()
    {
        return null;
    }
}

private class Testbb
{
    public int value;
}

private static void Start()
{
     Testaa testaa = new Testaa();

      Debug.LogError(testaa.GetGO()?.name ?? "111");      //111
      Debug.LogError(testaa.GetBb()?.value ?? -1);        //-1

      testaa = null;

      Debug.LogError(testaa?.value ?? -2);                //-2
      Debug.LogError(testaa?.GetGO()?.name ?? "aa");      //aa
      Debug.LogError(testaa?.GetBb()?.value ?? -5);       //Rethrow as ILRuntimeException: Object reference not set to an instance of an object.
                                                          //IL_00d4: call System.Boolean System.Nullable`1 < System.Int32 >::get_HasValue()

      if (10 == (testaa?.value ?? 10))
      {
          Debug.LogError("%");                            //%
      }

      if (10 == (testaa?.testbb?.value ?? 10))
      {
          Debug.LogError("!");                            //Rethrow as ILRuntimeException: Object reference not set to an instance of an object.
                                                          //IL_00f1: call System.Boolean System.Nullable`1 < System.Int32 >::get_HasValue()
      }
}

**Unity Version**
2021.3.9f1

**ILRuntime Version**
2.1.0

**Comment by liiir1985** [comment]
用到可空类型是必须进行CLR自动分析绑定将用到的可空类型全部绑定后才能工作正常，且非基础类型的struct的可空类型无法正常工作
