### ISSUE TITLE
有什么办法对大量创建对象进行优化？

### ISSUE THREAD

**Issue by sagasarate** [Ourpalm/ILRuntime#762]
因为需要对服务器发送过来的数据进行反序列化，数据有可能比较大，因而会进行大量的对象的创建，而且不都是值对象，这个过程对比原生c#会非常慢，有什么优化手段没？反序列化成的对象类型是在ILRuntime运行的dll内定义的。

**Comment by liiir1985** [comment]
这个可能没有特别多的优化方法，你可以尝试对对象进行缓存，同一个协议的序列化对象通过对象池反复循环利用
