### ISSUE TITLE
开启ILRuntimeJITFlags.JITOnDemand模式下，热更工程Update中for循环会出现越界报错问题

### ISSUE THREAD

**Issue by lzy3760** [Ourpalm/ILRuntime#764]
**Describe the bug**
打开寄存器模式下，for循环出现越界报错问题。关闭寄存器模式，一切恢复正常，报错消失

**To Reproduce**  
请描述重现步骤或上下
重现步骤：
1.通过Unity Tools/ILRuntime/OpenHotProject打开热更工程，编译dll
2.Tools/ILRuntime/UpdateHotfixbytes 更新dll
3.Tools/Generate 生成绑定代码
4.运行Unity ,出现报错

报错截图:
![image](https://github.com/Ourpalm/ILRuntime/assets/43442905/4e91ad1c-f280-42c1-8cb6-3b5fe1adde9b)

热更工程update方法：
![image](https://github.com/Ourpalm/ILRuntime/assets/43442905/ace473a1-1c8b-483b-abfc-5569b4c2675d)
SingleModule Update方法:
![image](https://github.com/Ourpalm/ILRuntime/assets/43442905/b2fb8ca1-953a-444e-a78a-62b04c847fec)
主工程Update 方法，该方法通过Mono Update调用
![image](https://github.com/Ourpalm/ILRuntime/assets/43442905/a407cb55-2c43-4f82-af11-b888013dc053)

**Expected behavior**
在运行后会出现11个越界报错，但报错似乎并不影响正常运行

**Unity Version**
Please fill in the version of Unity you're currently using
Unity version 2021.3.28f1c1

**ILRuntime Version**
Please fill in the version of ILRuntime you're currently using(package version or git commit hash or repository download date)
ILRuntime 2.1.0

https://gitee.com/sayeyijiu/my-frame-work/tree/ILRuntime/
GameApp场景运行，报错位置在热更工程中的SingleModule脚本中的update方法中,for循环那一行.
通过Unity Tools/ILRuntime/OpenHotProject打开热更工程

**Comment by shuoshuochendragonplus** [comment]
![1](https://github.com/Ourpalm/ILRuntime/assets/100413681/8ad35943-e4f4-4792-8e8a-401a62894ccd)
不知道和我遇到的问题是不是一样的，我也是for循环，代码跑着跑着就乱了报越界错误，后来发现token.GetHashCode会返回同样的一个数，导致代码错乱了，我现在把这里的优化改了就好了，如上图所示

**Comment by liiir1985** [comment]
Clone下来提供的仓库后运行并没有发现报错，并且也没有找到任何ILRuntime相关的代码， 复现工程给对了嘛？

**Comment by lzy3760** [comment]
是这个工程，ILRuntime分支，我看其他issue也有人提到了这个问题。

**Comment by lzy3760** [comment]
https://github.com/Ourpalm/ILRuntime/issues/733，这个是其他人遇到的相同问题

**Comment by lzy3760** [comment]
是这个工程，ILRuntime分支，GameApp运行。是不是分支没切对，确定是ILRuntime分支吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ourpalm/ILRuntime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 晚上7:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Ourpalm/ILRuntime] 开启ILRuntimeJITFlags.JITOnDemand模式下，热更工程Update中for循环会出现越界报错问题 (Issue #764)





 
Clone下来提供的仓库后运行并没有发现报错，并且也没有找到任何ILRuntime相关的代码， 复现工程给对了嘛？

**Comment by lzy3760** [comment]
我修改下试试看，谢谢大兄弟




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月19日(星期四) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ourpalm/ILRuntime] 开启ILRuntimeJITFlags.JITOnDemand模式下，热更工程Update中for循环会出现越界报错问题 (Issue #764)





 

 不知道和我遇到的问题是不是一样的，我也是for循环，代码跑着跑着就乱了报越界错误，后来发现token.GetHashCode会返回同样的一个数，导致代码错乱了，我现在把这里的优化改了就好了，如上图所示

**Comment by lzy3760** [comment]
Appdomain在主工程的HotfixModule初始化，行数是68行左右

**Comment by liiir1985** [comment]
NullReferenceException: 无效的package
FrameWork.Resource.ResourceModule.GetValidPackage (System.String uniqueKey) (at Assets/Scripts/FrameWork/Module/Resource/ResourceModule.cs:104)
FrameWork.Resource.ResourceModule.LoadAssetSync[T] (System.String uniqueKey) (at Assets/Scripts/FrameWork/Module/Resource/ResourceModule.cs:141)
FrameWork.HotfixModule.Start () (at Assets/Scripts/FrameWork/Module/HotifxComponent/HotfixModule.cs:56)
FrameWork.GameApp.OnStart () (at Assets/Scripts/Singleton/GameApp.cs:36)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <eef08f56e2e042f1b3027eca477293d9>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <56073df97ede4f769c2cc45d546d986d>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <56073df97ede4f769c2cc45d546d986d>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <56073df97ede4f769c2cc45d546d986d>:0)

无法启动GameApp场景，会报无效的package

**Comment by lzy3760** [comment]
拉取更新一下，我昨天晚上改了下，把报错都修复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月20日(星期五) 上午10:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Ourpalm/ILRuntime] 开启ILRuntimeJITFlags.JITOnDemand模式下，热更工程Update中for循环会出现越界报错问题 (Issue #764)





 
NullReferenceException: 无效的package
 FrameWork.Resource.ResourceModule.GetValidPackage (System.String uniqueKey) (at Assets/Scripts/FrameWork/Module/Resource/ResourceModule.cs:104)
 FrameWork.Resource.ResourceModule.LoadAssetSync[T] (System.String uniqueKey) (at Assets/Scripts/FrameWork/Module/Resource/ResourceModule.cs:141)
 FrameWork.HotfixModule.Start () (at Assets/Scripts/FrameWork/Module/HotifxComponent/HotfixModule.cs:56)
 FrameWork.GameApp.OnStart () (at Assets/Scripts/Singleton/GameApp.cs:36)
 System.Runtime.CompilerServices.AsyncMethodBuilderCore+<&gt;c.b__7_0 (System.Object state) (at :0)
 UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <56073df97ede4f769c2cc45d546d986d&gt;:0)
 UnityEngine.UnitySynchronizationContext.Exec () (at <56073df97ede4f769c2cc45d546d986d&gt;:0)
 UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <56073df97ede4f769c2cc45d546d986d&gt;:0)
 
无法启动GameApp场景，会报无效的package

**Comment by liiir1985** [comment]
已修复，修复方法看提交记录
