### ISSUE TITLE
开启寄存器模式后，属性被内联后多个if 生成的执行码转跳错误

### ISSUE THREAD

**Issue by durianCultivator** [Ourpalm/ILRuntime#766]
一个方法内调用了一个int属性，开启寄存器后，该属性返回值发生了错误，查看生成的寄存器模式代码后发现bgei指令的转跳错误
请描述Bug的现象

**步骤：**
*1.定义一个字段和一个属性，例：*
```
  int a;
  
  int A
  {
      get
      {
          if (a > 10)
              return 10;
  
          if (a < 2)
              return 2;
  
          return a;
      }
  }
```
*2.调用该属性，并保证a的值能使这个属性即能够走到最后一个return，例：*
```
void Update()
  {
      if (Input.GetKeyDown(KeyCode.Space))
      {
          a = 8;
          Debug.LogError(A);
      }
  }
```

**应该得到的值是8，实际上是 HotFix.TestWnd，这个是上述代码定义所在的类**

断点得到寄存器模式的操作码如下图 (并非上述代码生成，但是内联部分的bug相同)。可以看到第8行的blei第三个参数12，转跳到 第二个if 的 ldfld 所在行；而13行的blei是第三个参数16 转跳到了第二个return的br19操作上了，导致17 18行没有执行，mStack上的值错误，应该跳到17才对。
![屏幕截图 2023-12-15 160813](https://github.com/Ourpalm/ILRuntime/assets/34263961/741672ad-9ebd-4cba-a371-63b63a7430d8)

**unity verision 2018.4.32f1**

**Git提交号 e997f03fda5c401c5dfd22c04686985c8a617e1c**

**Comment by liiir1985** [comment]
> 这个bug这么修貌似修多了，其他代码会跑错的 ![20240108-201432](https://private-user-images.githubusercontent.com/3616339/294895092-64f0c22b-14c9-4784-99cb-d60d70a0cddf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NzA2NzMsIm5iZiI6MTcwNDc3MDM3MywicGF0aCI6Ii8zNjE2MzM5LzI5NDg5NTA5Mi02NGYwYzIyYi0xNGM5LTQ3ODQtOTljYi1kNjBkNzBhMGNkZGYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMDMxOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM3OTZmYmRlOTkxNzFiNmNiNDljMzhiYTQ2YjMwZThlMjBlMmJlZTE2ZmY1YzcyMTk3NGQwZmQzMzdhMDBiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-AfMPg8sqVC7A8xknH3ShonOX92hj8psf4QKPnbU_Y0) 这么简单的修下 就可以了

可以麻烦补一个会导致问题的测试用例吗？
