### ISSUE TITLE
在ILRuntime工程中使用Enum.Parse方法时报错

### ISSUE THREAD

**Issue by Runsl** [Ourpalm/ILRuntime#768]
使用Enum类中public static object Parse(Type enumType, string value) 去解析一个字符串转化为对应枚举类型时正常
使用Enum类中public static objectParse(Type enumType, string value, bool ignoreCase) 去解析就会报错
枚举类型是热更工程里定义的
报错内容Type must be a type provided by the runtime
是为什么？ILRumtime环境下不支持第二个重载么？

ILRumtime是1.6

**Comment by liiir1985** [comment]
Enum相关方法需要特殊处理才能正常使用，目前ILRuntime内部内置处理的只有前者那个重载，所以直接调用第二个重载是不能成功的，如果想要让第二个重载生效的话需要参照ILRuntime源码的CLRRedirections.cs里对Enum.Parse处理对第二个重载自行添加以下处理
