### ISSUE TITLE
Visual Studio 2022调试时报错：ILRunTime Debugger version mismatch

### ISSUE THREAD

**Issue by zyt-ssx** [Ourpalm/ILRuntime#769]
使用Visual Studio 2022调试时报错：ILRunTime Debugger version mismatch，使用的端口号没有被占用

**Comment by liiir1985** [comment]
需要确认一下ILRuntime版本和调试器版本是否匹配，VS市场中下载的调试器需要配合ILRuntime2.0以上版本使用，老版本ILRuntime则必须使用Github Release页面里对应版本的调试器插件
