### ISSUE TITLE
此工程中出现 访问类的字段时发生转换异常

### ISSUE THREAD

**Issue by asheigithub** [Ourpalm/ILRuntime#77]
[Bug_Cannot_cast.zip](https://github.com/Ourpalm/ILRuntime/files/1460300/Bug_Cannot_cast.zip)

此工程中的热更代码会导致ILRT抛出
InvalidCastException: Cannot cast from source type to destination type.异常

**Comment by liiir1985** [comment]
public virtual void OnHotFixLoaded()
	{
		Debug.Log("[ILRTTest] Loaded");

		var hfMain = appdomain.GetType("HotFixProto.Main");
		s_HFInitialize = hfMain.GetMethod("Initialize", 0);
		s_HFUpdate = hfMain.GetMethod("Update", 0);
		appdomain.Invoke(s_HFInitialize, hfMain, null); 《-------------------你这里把typeof(Main)当成new Main传进去了，根本就不是一个Main的实例

		InitedILRuntime = true;
	}
