### ISSUE TITLE
Quaternion.Euler使用了ValueTypeBinder之后报错

### ISSUE THREAD

**Issue by ghostwolfliu** [Ourpalm/ILRuntime#78]
直接用demo里ValueTypeBinder代码
反射工程这样写
    public class MainStart
    {

        private static Quaternion q;

        public static void OnFirstEnter()
        {
            q = Quaternion.Euler(0, 0, 0);
        }

    }
启动就直接报错,堆栈信息
NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Stack.RuntimeStack.AllocValueType (ILRuntime.Runtime.Stack.StackObject* ptr, IType type) (at Assets/Scripts/ILRuntime/Runtime/Stack/RuntimeStack.cs:181)
ILRuntime.Runtime.Intepreter.ILIntepreter.AllocValueType (ILRuntime.Runtime.Stack.StackObject* ptr, IType type) (at Assets/Scripts/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:4587)
QuaternionBinder.PushQuaternion (UnityEngine.Quaternion& vec, ILRuntime.Runtime.Intepreter.ILIntepreter intp, ILRuntime.Runtime.Stack.StackObject* ptr, IList`1 mStack) (at Assets/Scripts/ILRuntime/Other/QuaternionBinder.cs:333)
QuaternionBinder.Quaternion_Euler2 (ILRuntime.Runtime.Intepreter.ILIntepreter intp, ILRuntime.Runtime.Stack.StackObject* esp, IList`1 mStack, ILRuntime.CLR.Method.CLRMethod method, Boolean isNewObj) (at Assets/Scripts/ILRuntime/Other/QuaternionBinder.cs:243)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/Scripts/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1674)
Rethrow as ILRuntimeException: Object reference not set to an instance of an object
MainGame.MainStart.OnFirstEnter()

**Comment by liiir1985** [comment]
更新最新的ILRuntime就没这问题了
