### ISSUE TITLE
aysn  关键字修饰的方法  在release  模式的dll中会报错

### ISSUE THREAD

**Issue by shiliupingGitHub** [Ourpalm/ILRuntime#79]
当一个方式用aysn  修饰勾  在debug的dll  中没问题  但一用release的dll    ilruntime  把这个方法当变量用了  然后就报错了

**Comment by shiliupingGitHub** [comment]
我用vs2017   unity  版本为201700.1.2

**Comment by liiir1985** [comment]
已修复

**Comment by winddyhe** [comment]
`    class AsyncAwaitTest
    {
        public async static void TestRun()
        {
            await TestRunSub1();
        }
        
        async static Task TestRunSub1()
        {
            Console.WriteLine("Start: TestRunSub1..");
            await TestRunSub();
            Console.WriteLine("Result: TestRunSub1 complete..");
        }

        async static Task TestRunSub()
        {
            int cnt = 0;
            var res = await Task.Run<int>(() =>
            {
                for (int i = 0; i < 100000; i++)
                    cnt++;

                return cnt;
            });

            Console.WriteLine($"Result:{res}");
        }
    }`
这个测试用例跑不过，不会执行Console.WriteLine("Result: TestRunSub1 complete..");这句

**Comment by liiir1985** [comment]
已经修复
