### ISSUE TITLE
泛型展开的问题

### ISSUE THREAD

**Issue by xujieming** [Ourpalm/ILRuntime#80]
测试代码
放在热更工程中

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace HotFix_Project.Protocol
{
    public class Test
    {
        public void Func()
        {
            List<Dictionary<string, object>> content = new List<Dictionary<string, object>>();
            Dictionary<string, object> dic = new Dictionary<string, object>();
            dic.Add("key1", 1000);
            content.Add(dic);

            this.SetValue<string, object>(content);
        }

        public void SetValue<K, V>(Dictionary<K, V> value)
        {
            UnityEngine.Debug.LogError(value.Count);
        }

        public void SetValue<K, V>(List<Dictionary<K, V>> value)
        {
            UnityEngine.Debug.LogError(value.Count);
        }

        public void SetValue<K, V>(Dictionary<K, List<V>> value)
        {
            UnityEngine.Debug.LogError(value.Count);
        }
    }
}
`

![image](https://user-images.githubusercontent.com/3971050/33420536-f360a8e6-d5e9-11e7-9608-aeb8f7887792.png)

![image](https://user-images.githubusercontent.com/3971050/33420551-fc97bde6-d5e9-11e7-8ed1-639c45451103.png)

本来要调用的是第二个重载函数
调到第三个了

**Comment by liiir1985** [comment]
ILRuntime中只能做到Dictionary和List区分，但是如果都是Dictionary的2种情况，暂时没有办法匹配

目前这个测试用例可以正常调用了，但是如果你是Dictionary，那依然可能调用到错误的方法
