### ISSUE TITLE
bug for CLR binding Generator Tools

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#82]
public static void CodeGenerateError()
        {

            var a = new int[0][];  //Assets/ILRuntime/Generated/System_Int32_Binding_Array.cs(26,78): error CS0178: Invalid rank specifier, expecting `,' or `]'
            var b = new int[0][][]; //Assets/ILRuntime/Generated/System_Int32[]_Binding_Array.cs
        }

**Comment by liiir1985** [comment]
Fixed
