### ISSUE TITLE
Bugs for Equals And System.Array.IndexOf

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#83]
public static void Test_01()
        {
            Equals2(new int[] { 1 }, 2); //NotSupportedException: Not supported opcode Readonly
            Equals(1, new object()); //InvalidCastException: Cannot cast from source type to destination type.
            IndexOf(new byte[] { }, (byte)1); //NullReferenceException: Object reference not set to an instance of an object
        }

        static bool Equals2<T>(T[] a, T b)
        {
            return a[0].Equals(b);
        }

        static bool Equals<T>(T a, object b)
        {
            return a.Equals(b);
        }

        static void IndexOf<T>(T[] array, T value)
        {
            System.Array.IndexOf(array, value);
        }

**Comment by liiir1985** [comment]
Fixed
