### ISSUE TITLE
继承CLR里的对象后，如果增加一个成员，就会出错

### ISSUE THREAD

**Issue by wyyayy** [Ourpalm/ILRuntime#84]
在官方的继承例子里，这么修改：

```
    public class TestInheritance : TestClassBase
    {
        protected int _a;  /// 这是新加的成员
```

**再运行就会出错，堆栈：**
NullReferenceException: Object reference not set to an instance of an object
ILRuntime.Runtime.Intepreter.ILTypeInstance.InitializeFields (ILRuntime.CLR.TypeSystem.ILType type) (at Assets/ILRuntime/Runtime/Intepreter/ILTypeInstance.cs:243)
ILRuntime.Runtime.Intepreter.ILTypeInstance..ctor (ILRuntime.CLR.TypeSystem.ILType type, System.Boolean initializeCLRInstance) (at Assets/ILRuntime/Runtime/Intepreter/ILTypeInstance.cs:153)
ILRuntime.CLR.TypeSystem.ILType.Instantiate (System.Boolean callDefaultConstructor) (at Assets/ILRuntime/CLR/TypeSystem/ILType.cs:926)
ILRuntime.Runtime.Enviorment.AppDomain.Instantiate (System.String type, System.Object[] args) (at Assets/ILRuntime/Runtime/Enviorment/AppDomain.cs:881)
ILRuntime.Runtime.Enviorment.AppDomain.Instantiate[T] (System.String type, System.Object[] args) (at Assets/ILRuntime/Runtime/Enviorment/AppDomain.cs:862)
Inheritance.OnHotFixLoaded () (at Assets/Scripts/Examples/04_Inheritance/Inheritance.cs:104)
Inheritance+<LoadHotFixAssembly>c__Iterator0.MoveNext () (at Assets/Scripts/Examples/04_Inheritance/Inheritance.cs:79)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by liiir1985** [comment]
这个是这个示例中才会发生的问题，因为实例中有演示如果没有注册跨域继承适配器会报错的情况，在报错的时候因为确实适配器字段没初始化成功，所以后面会出现报错（示例是为了演示强行让适配器生效，正常情况是发现缺少适配器，编辑代码加上了之后重新运行），正常使用的时候不会发生这个异常，因此关闭Issue

**Comment by wyyayy** [comment]
明白了，感谢回复！
