### ISSUE TITLE
带泛型的方法无法被找到 KeyNotFoundException: Cannot find method:SeekUI in type:MainGame.Test.TestClass, token=T

### ISSUE THREAD

**Issue by ghostwolfliu** [Ourpalm/ILRuntime#95]
类中用了带泛型的方法在ilruntime的环境下无法被找到，使用纯反射执行就可以正常执行成功

完整报错如下:
KeyNotFoundException: Cannot find method:SeekUI in type:MainGame.Test.TestClass, token=T MainGame.Test.TestClass::SeekUI<T>(UnityEngine.Transform,System.String)
ILRuntime.Runtime.Enviorment.AppDomain.GetMethod (System.Object token, ILRuntime.CLR.TypeSystem.ILType contextType, ILRuntime.CLR.Method.ILMethod contextMethod, System.Boolean& invalidToken) (at Assets/ILRuntime/Runtime/Enviorment/AppDomain.cs:1131)
ILRuntime.CLR.Method.ILMethod.InitToken (ILRuntime.Runtime.Intepreter.OpCodes.OpCode& code, System.Object token, System.Collections.Generic.Dictionary`2[TKey,TValue] addr) (at Assets/ILRuntime/CLR/Method/ILMethod.cs:384)
ILRuntime.CLR.Method.ILMethod.InitCodeBody () (at Assets/ILRuntime/CLR/Method/ILMethod.cs:258)
ILRuntime.CLR.Method.ILMethod.get_Body () (at Assets/ILRuntime/CLR/Method/ILMethod.cs:180)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:104)
ILRuntime.Runtime.Intepreter.ILIntepreter.Execute (ILRuntime.CLR.Method.ILMethod method, ILRuntime.Runtime.Stack.StackObject* esp, System.Boolean& unhandledException) (at Assets/ILRuntime/Runtime/Intepreter/ILIntepreter.cs:1697)
Rethrow as ILRuntimeException: Cannot find method:SeekUI in type:MainGame.Test.TestClass, token=T MainGame.Test.TestClass::SeekUI<T>(UnityEngine.Transform,System.String)
IL_000e: call T MainGame.Test.TestClass::SeekUI<UnityEngine.UI.Text>(System.String)
MainGame.Test.TestClassB.Init()
MainGame.MainStart.OnFirstEnter()
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
ILRStart:Start() (at Assets/ILRStart.cs:28)

完整工程附件:
[ILTest.zip](https://github.com/Ourpalm/ILRuntime/files/1603313/ILTest.zip)

**Comment by liiir1985** [comment]
用最新版无法复现错误，更新试试吧

**Comment by li959598874** [comment]
最新版还是有这个问题
