### ISSUE TITLE
CLRMethod.IsStatic null reference error

### ISSUE THREAD

**Issue by maxzhou0** [Ourpalm/ILRuntime#99]
if CLRMethod is a constructor method ,call IsStatic  would be error.

`        static int GetParamCount(CLRMethod method)
        {
            return (method.IsConstructor || method.IsStatic) ? method.ParameterCount : (method.ParameterCount + 1); //ok
            return (method.IsStatic|| method.IsConstructor ) ? method.ParameterCount : (method.ParameterCount + 1); //error

        }`

**Comment by liiir1985** [comment]
已修复
